### ISSUE TITLE
Multiple signature verification

### ISSUE THREAD

**Issue by flamsmark** [micahflee/torbrowser-launcher#113]
When checking signatures on new TBB binaries, require a more complex signature set than just Mike Perry. Perhaps Mike Perry and one of these several others.

**Comment by micahflee** [comment]
It looks like the official `Tor Browser Developers (signing key)` with fingerprint `EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290` is the only signing key now.
