### ISSUE TITLE
If download error occurs, propose to launch old version of TBB

### ISSUE THREAD

**Issue by u451f** [micahflee/torbrowser-launcher#130]
Hi,

With the new version of TBL and Tor's change of locations of files, i thought that it would be cool, if TBL suggested to launch the old version which i still have installed if for whatever reason there is a download problem. This might in some cases be insecure, if there really is a new version of TBB available, but i still see a useful addition here.

What do you think?

**Comment by micahflee** [comment]
Since #198 this is no longer an issue.
