### ISSUE TITLE
dh-apparmor not in use / not including local AppArmor profile

### ISSUE THREAD

**Issue by adrelanos** [micahflee/torbrowser-launcher#136]
I did just build `v0.1.5` from source using `./build_deb.sh`.

In the AppArmor profiles I was missing the usual

```
  # Site-specific additions and overrides. See local/README for details.
  #include <local/...>
```

at the bottom.

Looking at the postinst script revealed, that the usual dh_apparmor autogenerated code was missing.

(Example dh_apparmor autogenerated code:)

```
# Automatically added by dh_apparmor
if [ "$1" = "configure" ]; then
    APP_PROFILE=/etc/apparmor.d/usr.bin.torbrowser-launcher
    if [ -f "$APP_PROFILE" ]; then
        # Add the local/ include
        LOCAL_APP_PROFILE=/etc/apparmor.d/local/usr.bin.torbrowser-launcher

        test -e "$LOCAL_APP_PROFILE" || {
            tmp=`mktemp`
        cat <<EOM > "$tmp"
# Site-specific additions and overrides for usr.bin.torbrowser-launcher.
# For more details, please see /etc/apparmor.d/local/README.
EOM
            mkdir `dirname $LOCAL_APP_PROFILE` 2>/dev/null || true
            mv -f "$tmp" "$LOCAL_APP_PROFILE"
            chmod 644 "$LOCAL_APP_PROFILE"
        }

        # Reload the profile, including any abstraction updates
        if [ -x /usr/sbin/aa-status ] && aa-status --enabled 2>/dev/null; then
            apparmor_parser -r -T -W "$APP_PROFILE" || true
        fi
    fi
fi
# End automatically added section
# Automatically added by dh_apparmor
```

Probably because I didn't build from the Debian branch.

I am wondering if these inconsistencies could be a bad surprise to some? Anything that could be done about this?

Could you please provide signed git tags for the Debian branch releases as well?

But even if I would build from the Debian branch, the `#include <local/...>` would not be added?

**Comment by intrigeri** [comment]
That's https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=751451, patches are welcome.

**Comment by h01ger** [comment]
Micah, please close this issue - you've merge the debian patch for #751451 as git commit c00f8b559  into 0.2.3.

**Comment by intrigeri** [comment]
This was fixed 2 years ago, please close :)
