### ISSUE TITLE
check gpg exit code after gpg key import

### ISSUE THREAD

**Issue by adrelanos** [micahflee/torbrowser-launcher#137]
https://github.com/micahflee/torbrowser-launcher/blob/master/torbrowser_launcher/common.py#L178

If gpg key import fails, it goes unnoticed.

**Comment by adrelanos** [comment]
@isislovecruft Thank you for working on this! Sorry, I never found time to look into this, never found time to do real testing. Here is a theoretic consideration by reading your proposed code.

```
(output.find('GOODSIG')
```

I am not sure, this is save. Seems like simple matching. An adversary could add an OpenPGP notation that contains the string `GOODSIG` and it would match. For example, in `grep` terms, I would suggest to consider a regex like this.

```
'^\[GNUPG:\] VALIDSIG 8738A680B84B3031A630F2DB416F061063FEE659$'
```

Do you think should `[GNUPG:]  TRUST_[...]` be checked also?

What did you think through what would happen in cases if there were multiple mixed, perhaps valid and invalid signatures inside the same [adversary tampered with] signature file?

**Comment by h01ger** [comment]
Micah, you never commented on this bug…?!?
