### ISSUE TITLE
After auto-update, failed start of TBB is silently ignored

### ISSUE THREAD

**Issue by pmocek** [micahflee/torbrowser-launcher#140]
After an automatic update of Tor Browser Bundle (TBB), torbrowser-launcher starts TBB but does not report that TBB failed to start, instead exiting as if there was no problem.

Sample output:

    $ torbrowser-launcher 
    Tor Browser Launcher
    By Micah Lee, licensed under GPLv3
    version 0.1.4
    https://github.com/micahflee/torbrowser-launcher
    Initializing Tor Browser Launcher
    Successfully loaded mirrors from /usr/share/torbrowser-launcher/mirrors.txt
    Warning: can't load mirrors from /home/pmocek/.config/torbrowser/mirrors.txt
    Importing keys
    gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
    gpg: Total number processed: 1
    gpg:              unchanged: 1
    Starting launcher dialog
    LATEST VERSION 4.0
    Checked for update within 24 hours, skipping
    TBB is out of date, attempting to upgrade to 4.0
    Running task: download_sha256
    Downloading https://www.torproject.org/dist/torbrowser/4.0/sha256sums.txt
    Updating over Tor
    Finished receiving body: Response body fully received
    Running task: download_sha256_sig
    Downloading https://www.torproject.org/dist/torbrowser/4.0/sha256sums.txt.asc
    Updating over Tor
    Finished receiving body: Response body fully received
    Running task: download_tarball
    Downloading https://www.torproject.org/dist/torbrowser/4.0/tor-browser-linux64-4.0_en-US.tar.xz
    Updating over Tor
    Finished receiving body: Response body fully received
    Running task: verify
    Verifying signature
    gpg: Signature made Wed 15 Oct 2014 03:07:06 PM PDT using RSA key ID 63FEE659
    gpg: Good signature from "Erinn Clark <erinn@torproject.org>"
    gpg:                 aka "Erinn Clark <erinn@debian.org>"
    gpg:                 aka "Erinn Clark <erinn@double-helix.org>"
    gpg: WARNING: This key is not certified with a trusted signature!
    gpg:          There is no indication that the signature belongs to the owner.
    Primary key fingerprint: 8738 A680 B84B 3031 A630  F2DB 416F 0610 63FE E659
    Running task: extract
    Extracting tor-browser-linux64-4.0_en-US.tar.xz
    Running task: run
    Running /home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser

    $ echo $?
    0

    $ # Note: There was no GUI indication of any trouble.  Updater window
    $ # closed.  TBB did not appear.

    $ /home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser 
    Launching Tor Browser for Linux in /home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser...
    XPCOMGlueLoad error for file /home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/libxul.so:
    /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/libxul.so)
    Couldn't load XPCOM.
    Tor Browser exited abnormally.  Exit code: 255

    $ ll /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    lrwxrwxrwx 1 root root 19 Oct  6 16:17 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 -> libstdc++.so.6.0.19

    $ ll /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19
    -rw-r--r-- 1 root root 979056 Apr  5  2014 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19

    $ dpkg -s libstdc++6
    Package: libstdc++6
    Status: install ok installed
    Priority: important
    Section: libs
    Installed-Size: 1211
    Maintainer: Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com>
    Architecture: amd64
    Multi-Arch: same
    Source: gcc-4.8
    Version: 4.8.2-19ubuntu1
    Depends: gcc-4.8-base (= 4.8.2-19ubuntu1), libc6 (>= 2.17), libgcc1 (>= 1:4.1.1)
    Pre-Depends: multiarch-support
    Breaks: gcc-4.1, gcc-4.3 (<< 4.3.6-1), gcc-4.4 (<< 4.4.6-4), gcc-4.5 (<< 4.5.3-2)
    Conflicts: scim (<< 1.4.2-1)
    Description: GNU Standard C++ Library v3
     This package contains an additional runtime library for C++ programs
     built with the GNU compiler.
     .
     libstdc++-v3 is a complete rewrite from the previous libstdc++-v2, which
     was included up to g++-2.95. The first version of libstdc++-v3 appeared
     in g++-3.0.
    Homepage: http://gcc.gnu.org/
    Original-Maintainer: Debian GCC Maintainers <debian-gcc@lists.debian.org>

    $ uname -a
    Linux 5dz7f12 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by micahflee** [comment]
I don't think this issue is relevant anymore, with recent code changes.
