### ISSUE TITLE
Downloads again if hard-shutdown on Debian Jessie

### ISSUE THREAD

**Issue by djon3s** [micahflee/torbrowser-launcher#143]
For the Torbrowser update to 4.0, I shutdown computer (I cannot recall method - `sudo shutdown now` perhaps, could have been hard-poweroff) and on re-launching, torbrowser-launcher downloaded the sig and the browser again.

I am using the torbrowser-launcher from the debian jessie repo

From the apt cache:

```
Package: torbrowser-launcher
Version: 0.1.4-2
Installed-Size: 319
Maintainer: Anonymity Tools Debian Maintainers <pkg-anonymity-tools@lists.alioth.debian.org>
Description-md5: a2c6e1e2b71558a7ee26f9813f4f843c
```

**Comment by micahflee** [comment]
Sorry about never responding a year ago when you opened this! But right now it's entirely no longer relevant. :)
