### ISSUE TITLE
Use status-fd rather than GnuPG process exit codes

### ISSUE THREAD

**Issue by isislovecruft** [micahflee/torbrowser-launcher#147]
The exit codes from GnuPG are not a reliable, nor entirely stable, means of determining if the process did as it was intended to do. I also commented on #137 for the use of process exit codes to determine the result of an attempted key import.

torbrowser-laucher currently checks for `p.returncode == 0` in the `Laucher.verify()` method, and then proceeds to check the tarball's sha256sum and schedule installation if the process exited with `0`. This makes me a bit uneasy…

As I explained on #137, the "correct" way to check that GnuPG did as intended is to use the `--status-fd` flag to the binary, and then check for [the appropriate GnuPG status-fd output flag](http://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=doc/DETAILS;hb=HEAD#l323).

This would look something like:

```
valid_sig = False
p = subprocess.Popen(['/usr/bin/gpg', '--status-fd', '2',
                      '--homedir', self.common.paths['gnupg_homedir'],
                      '--verify', self.common.paths['sha256_sig_file']],
                     stderr=subprocess.PIPE)
self.pulse_until_process_exits(p)
output = p.stderr.read()
if ((output.find('GOODSIG') >= 0) and
    (output.find('VALIDSIG 8738A680B84B3031A630F2DB416F061063FEE659') >= 0)):
    valid_sig = True
```

**Comment by micahflee** [comment]
This is resolved thanks to #148.
