### ISSUE TITLE
AppArmor permission for browser homepage

### ISSUE THREAD

**Issue by adrelanos** [micahflee/torbrowser-launcher#152]
There is currently a patch in the works to [allow distributions set a Tor Browser homepage using an environment variable](https://trac.torproject.org/projects/tor/ticket/13835). We at @Whonix would like to use it and are not aware of a canonical way, where Linux distributions or derivatives could store their local homepages.

What do you think about adding a read-only AppArmor permission to the `/usr/share/homepage` folder?

(@Whonix is probably soon getting a [local homepage](https://www.whonix.org/forum/index.php/topic,365.msg5727.html#msg5727). And we would like to store our local homepage at `/usr/share/homepage/whonix-homepage`.)

The distribution agnostic path name `/usr/share/homepage` should allow any distribution or derivative allow dropping their homepage folder there.

Can you please check if this approach is sane, review and merge commit [12402ae7](https://github.com/troubadoour/torbrowser-launcher/commit/12402ae760e5b5ce4c11007115e10c2ee7a918cb)?

**Comment by micahflee** [comment]
Sorry about responding nearly a year later. Is this still relevant to you? If so, I'm happy to merge this patch.

**Comment by adrelanos** [comment]
Yes.

https://github.com/micahflee/torbrowser-launcher/pull/209
