### ISSUE TITLE
Can't pass URLs under Linux Mint 17 Cinnamon

### ISSUE THREAD

**Issue by starchy** [micahflee/torbrowser-launcher#153]
After the update post-#103, I updated TBB and I'm running torbrowser-launcher 0.1.7-ppa1-1. I can select Tor Browser as my default browser in the Preferred Applications preference applet, but when I click a link in another application nothing appears to happen.

**Comment by micahflee** [comment]
This is possibly related to #157.

**Comment by micahflee** [comment]
Passing URLs into Tor Browser Launcher no longer works, unfortunately.
