### ISSUE TITLE
add ability to configure StrictExitNodes in Tor Browser Settings

### ISSUE THREAD

**Issue by weisserose** [micahflee/torbrowser-launcher#154]
Since most ExitNodes cannot be trusted it would be handy to add them directly gui-wise in Tor Browser Settings. Or make torbrowser-launcher respect /etc/tor/torrc would be another possibility.

thanks for your work :-)

**Comment by micahflee** [comment]
I think this feature would be better directly in Tor Browser, rather than in Tor Browser Launcher.
