### ISSUE TITLE
Broken on Fedora 21

### ISSUE THREAD

**Issue by jawadcogilent** [micahflee/torbrowser-launcher#159]
Hi,

I am able to use it in Fedora 20 but I am unable to use it in Fedora 21. Following is the error I get:

==========================================================
/usr/lib64/python2.7/site-packages/twisted/internet/_sslverify.py:184: UserWarning: You do not have the service_identity module installed. Please install it from <https://pypi.python.org/pypi/service_identity>. Without the service_identity module and a recent enough pyOpenSSL tosupport it, Twisted can perform only rudimentary TLS client hostnameverification.  Many valid certificate/hostname mappings may be rejected.
  verifyHostname, VerificationError = _selectVerifyImplementation()
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.7
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Successfully loaded mirrors from /usr/share/torbrowser-launcher/mirrors.txt
Warning: can't load mirrors from /home/ahmad/.config/torbrowser/mirrors.txt
Importing keys
gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Starting launcher dialog
LATEST VERSION 4.0.2
Checking for update
Running task: download_update_check
Downloading https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions
Download error: [<twisted.python.failure.Failure <class 'twisted.internet._sslverify.SimpleVerificationError'>>] <class 'twisted.web._newclient.ResponseNeverReceived'>
Running task: attempt_update
Checking to see if update is needed
=================================================================

Secondly, I am unable to figure out why it is checking for updates. Is there a way to launch browser without checking for updates?

**Comment by micahflee** [comment]
Sorry about that! TBL automatically checks for updates every 24 hours, because it's important to always use the latest version of Tor Browser for security. If this is your first time running you need to check for updates because TBL doesn't actually come with Tor Browser, it needs to download it first. Otherwise there's no way to skip update checks (there's only a way to force them, from the settings window).

But sorry this is broken in FC21. I'm talking to some Fedora devs. It seems that FC21 will require the packages python-txsocksx and service-identity to be installed before this will work. Both are expected to land in FC21's stable repo in a couple days. So I think this should work again in FC21 very soon.

**Comment by jawadcogilent** [comment]
Hi,

I have upgraded from Fedora 20. TBL has already installed Tor Browser and functioning well. 

I can run the browser from ./.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser. When I launched the browser the tor icon is blinking saying it needs to upgrade from 4.0.2 to 4.0.3. I upgraded tor without any problem and now I am running 4.0.3.

I installed service_identity from pip. The torbrowser-launcher is still not functioning. It downloads the tarball now but fails to verify signature. Please see the output below:

<code>
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.7
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Successfully loaded mirrors from /usr/share/torbrowser-launcher/mirrors.txt
Warning: can't load mirrors from /home/ahmad/.config/torbrowser/mirrors.txt
Importing keys
gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Starting launcher dialog
LATEST VERSION 4.0.2
Checking for update
Running task: download_update_check
Downloading https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions
Finished receiving body: Response body fully received
Running task: attempt_update
Checking to see if update is needed
TBB is out of date, attempting to upgrade to 4.5a3
Running task: download_sha256
Downloading https://www.torproject.org/dist/torbrowser/4.5a3/sha256sums.txt
Finished receiving body: Response body fully received
Running task: download_sha256_sig
Downloading https://www.torproject.org/dist/torbrowser/4.5a3/sha256sums.txt.asc
Finished receiving body: Response body fully received
Running task: download_tarball
Downloading https://www.torproject.org/dist/torbrowser/4.5a3/tor-browser-linux64-4.5a3_en-US.tar.xz
Finished receiving body: Response body fully received
Running task: verify
Verifying signature
gpg: Signature made Fri 16 Jan 2015 01:37:06 PM PKT using RSA key ID D40814E0
gpg: Can't check signature: public key not found
</code>

**Comment by strasharo** [comment]
Same here on Fedora 20:

Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.7
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Successfully loaded mirrors from /usr/share/torbrowser-launcher/mirrors.txt
Warning: can't load mirrors from /home/strshr/.config/torbrowser/mirrors.txt
Importing keys
gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Starting launcher dialog
LATEST VERSION 4.5a3
Checked for update within 24 hours, skipping
TBB is not installed, attempting to install 4.5a3
Running task: download_sha256
Downloading https://www.torproject.org/dist/torbrowser/4.5a3/sha256sums.txt
Finished receiving body: Response body fully received
Running task: download_sha256_sig
Downloading https://www.torproject.org/dist/torbrowser/4.5a3/sha256sums.txt.asc
Finished receiving body: Response body fully received
Running task: download_tarball
Downloading https://www.torproject.org/dist/torbrowser/4.5a3/tor-browser-linux64-4.5a3_en-US.tar.xz
Finished receiving body: Response body fully received
Running task: verify
Verifying signature
gpg: Signature made Fri 16 Jan 2015 10:37:06 AM EET using RSA key ID D40814E0
gpg: Can't check signature: public key not found

**Comment by vlastikcz** [comment]
Same here on Jessie:

Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.7
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Successfully loaded mirrors from /usr/share/torbrowser-launcher/mirrors.txt
Warning: can't load mirrors from /home/vk/.config/torbrowser/mirrors.txt
Importing keys
gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Starting launcher dialog
LATEST VERSION 4.5a3
Checked for update within 24 hours, skipping
TBB is out of date, attempting to upgrade to 4.5a3
Running task: download_sha256
Downloading https://www.torproject.org/dist/torbrowser/4.5a3/sha256sums.txt
Updating over Tor
Finished receiving body: Response body fully received
Running task: download_sha256_sig
Downloading https://www.torproject.org/dist/torbrowser/4.5a3/sha256sums.txt.asc
Updating over Tor
Finished receiving body: Response body fully received
Running task: download_tarball
Downloading https://www.torproject.org/dist/torbrowser/4.5a3/tor-browser-linux64-4.5a3_en-US.tar.xz
Updating over Tor
Finished receiving body: Response body fully received
Running task: verify
Verifying signature
gpg: assuming signed data in `/home/vk/.cache/torbrowser/download/sha256sums.txt'
gpg: Signature made Fri 16 Jan 2015 09:37:06 AM CET using RSA key ID D40814E0
gpg: Can't check signature: public key not found

**Comment by heichblatt** [comment]
TBB (torbrowser-launcher-0.1.9-1.fc21) works on F21 if you also install [python-service-identity](http://koji.fedoraproject.org/koji/buildinfo?buildID=606773).
- [RedHat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1177388)
- [Koji build](http://koji.fedoraproject.org/koji/buildinfo?buildID=606773)

**Comment by echevemaster** [comment]
Unfortunately not. I just installed torbrowser-launcher in rawhide and throw the next message. 
```javascript
➜ ~ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.9
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Importing keys
gpg: clave 63FEE659: "Erinn Clark <erinn@torproject.org>" sin cambios
gpg: Cantidad total procesada: 1
gpg:              sin cambios: 1
gpg: clave 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" sin cambios
gpg: Cantidad total procesada: 1
gpg:              sin cambios: 1
Starting launcher dialog
LATEST VERSION 0
Checking for update
Running task: download_update_check
Downloading https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions
Updating over Tor
Download error: Connection was refused by other side: 111: Conexión rehusada. <class 'twisted.internet.error.ConnectionRefusedError'>```

**Comment by echevemaster** [comment]
I've installed through pip to twisted == 15.0.0 and the message has gone, but now I have this traceback.
```bash
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.9
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Importing keys
gpg: clave 63FEE659: "Erinn Clark <erinn@torproject.org>" sin cambios
gpg: Cantidad total procesada: 1
gpg:              sin cambios: 1
gpg: clave 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" sin cambios
gpg: Cantidad total procesada: 1
gpg:              sin cambios: 1
Starting launcher dialog
LATEST VERSION 0
Checking for update
Running task: download_update_check
Downloading https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions
Updating over Tor
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/__init__.py", line 69, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 131, in __init__
    self.build_ui()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 285, in build_ui
    self.start(None)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 294, in start
    self.run_task()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 312, in run_task
    self.download('update check', self.common.paths['update_check_url'], self.common.paths['update_check_file'])
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 473, in download
    None)
  File "/usr/lib64/python2.7/site-packages/twisted/web/client.py", line 1927, in request
    deferred = self._agent.request(method, uri, headers, bodyProducer)
  File "/usr/lib64/python2.7/site-packages/twisted/web/client.py", line 1560, in request
    endpoint = self._getEndpoint(parsedURI)
TypeError: _getEndpoint() takes exactly 4 arguments (2 given)
```

**Comment by robyduck** [comment]
Yes, same here. I've also built python-twisted-15.0.0-1 locally for F21 as rpm and get the same traceback. Anyway, I think at his point it is due to twisted, not torbrowser.

I'm going to revoke the last build of torbrowser-launcher-0.1.9-1 for F21. Will push a new release asap.

**Comment by askmatey** [comment]
Thank you @robyduck for the good work!

**Comment by robyduck** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1192707

**Comment by jawadcogilent** [comment]
I installed python-twisted-14.0.2 and torbrowser-launcher-0.1.9 from updates-testing repo couple of days ago. It worked like charm!

Today there is a strange problem. Look at the output below

<code>
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.9
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Importing keys
gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Starting launcher dialog
LATEST VERSION 4.0.4
Checked for update within 24 hours, skipping
TBB is out of date, attempting to upgrade to 4.0.4
Running task: download_sha256
Downloading https://dist.torproject.org/torbrowser/4.0.4/sha256sums.txt
Download error: Download Error: 404 Not Found <class 'torbrowser_launcher.launcher.DownloadErrorException'>
</code>

It is detecting from somewhere a new version. I am also unable to find this new version from torproject,org

Thanks @robyduck for wonderful work!

**Comment by robyduck** [comment]
I wonder why it works like a charm, but initially it worked also for me. The error you get is related and compatible with the issue on version 0.1.9.

I did some tests today and I'm going to revoke definitely 0.1.9-2 from updates-testing. I fixed some minor things and built 0.1.8-1 which seems at least to work as it should. In the meanwhile I have some time to find out the issue we have on 0.1.9...

Thanks for reporting this and helping me ;) much appreciated.

**Comment by robyduck** [comment]
Ok the new builds are submitted, version 0.1.8-1, for F21, F22 and F23.
Please help testing them and give karma to make them land in stable ASAP.
Thank you.

**Comment by Pincha** [comment]
Arch freshinstall, tor-browser too, through yaourt 
aur/torbrowser-launcher-git v0.1.8-1

<code>
user ~ $ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.9
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Importing keys
gpg: key 63FEE659: "Erinn Clark <erinn@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: key 93298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Starting launcher dialog
LATEST VERSION 0
Checking for update
Running task: download_update_check
Downloading https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions
Updating over Tor
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/__init__.py", line 69, in main
    app = Launcher(common, url_list)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 131, in __init__
    self.build_ui()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 285, in build_ui
    self.start(None)
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 294, in start
    self.run_task()
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 312, in run_task
    self.download('update check', self.common.paths['update_check_url'], self.common.paths['update_check_file'])
  File "/usr/lib/python2.7/site-packages/torbrowser_launcher/launcher.py", line 473, in download
    None)
  File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1927, in request
    deferred = self._agent.request(method, uri, headers, bodyProducer)
  File "/usr/lib/python2.7/site-packages/twisted/web/client.py", line 1560, in request
    endpoint = self._getEndpoint(parsedURI)
TypeError: _getEndpoint() takes exactly 4 arguments (2 given)
</code>

**Comment by robyduck** [comment]
This issue is about Fedora not other distributions, your output is not really useful here.
You're using 0.1.9 and not 0.1.8 as stated in your comment.

**Comment by jawadcogilent** [comment]
@robyduck I tested 0.18 version and it worked without any errors for me on Fedora 21 x86_64. Great work and many thanks. I add karma as well.

**Comment by robyduck** [comment]
Nice! Thank you for testing and confirming it works fine (also for karma) ;)

**Comment by jawadcogilent** [comment]
Just a quick note. This version has a bug as described in issue #157

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu: ( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder ) Başlatıcısı İnşa: 0 Seçili Pack: Yığın İzleme Yogbox: özel Durum: İndexOutOfBoundsException İletisi: Dizin: 0, Boyut: 0 İz: java.açıklama.ArrayList.(Bilinmeyen Kaynak) rangeCheck java.açıklama.ArrayList.(Bilinmeyen Kaynak) org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java) org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java) org.spoutcraft.başlatıcısı.Launcher 2 dolar.Çalıştır(Başlatıcısı.java:105) Sistem Bilgileri İşletim Sistemi: Windows 7 İşletim Sistemi Versiyon: 6.1 İşletim Sistemi Mimarisi: 86 Java sürümü: 1.8.0_31 32 bit Toplam Bellek: 47 MB Max Bellek: 247 MB boş Bellek: 20 MB CPU Çekirdek: 2

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu:
( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder )
Başlatıcı Oluştur: 0
 
Seçili Paketi: Yogbox
Yığın İzleme:
Özel Durum: İndexOutOfBoundsException
Mesaj: Dizin: 0, Size: 0
İzleme:
java.açıklama.ArrayList.rangeCheck(Bilinmeyen Kaynak)
java.açıklama.ArrayList.(Bilinmeyen Kaynak)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java)
org.spoutcraft.başlatıcısı.Launcher 2 dolar.Çalıştır(Başlatıcısı.:105 java)
 
Sistem Bilgisi:
İşletim Sistemi: Windows 7
İşletim Sistemi Versiyon: 6.1
İşletim Sistemi Mimarisi: 86
Java sürümü: 1.8.0_31 32 bit
Toplam Bellek: 47)
Max Bellek: 247 MB
Boş bellek: 20 MB

**Comment by robyduck** [comment]
@jawadcogilent
OK thank you, I might have found a patch to run also version 0.1.9. If it works I'directly update the last build.

**Comment by robyduck** [comment]
I've just released 0.1.9-2 which should fix this bug. Please test and leave karma, it's running fine here :)

https://admin.fedoraproject.org/updates/torbrowser-launcher-0.1.9-2.fc21
https://admin.fedoraproject.org/updates/torbrowser-launcher-0.1.9-2.fc22

**Comment by jawadcogilent** [comment]
@robyduck 
I've tested 0.1.9-2. Worked perfectly. Thanks.

**Comment by msx** [comment]
Hi all,
Can't make it work here on an F21 up-to-date.
When launching '$ torbrowser-launcher' I get a nice window telling me that it can't connect to the internet (or rather the Tor/Vidalia proxy, I presume).
Now, when launching the settings box, Tor Browser shows up as not installed.
I just installed torbrowser-launcher moments ago from repos:
Name        : torbrowser-launcher
Arch        : noarch
Version     : 0.1.9
Release     : 2.fc21
Size        : 355 k
Repo        : installed

Ideas?

**Comment by robyduck** [comment]
In your settings, could you try to check for updates over Tor, save and exit, and relaunch it?

**Comment by msx** [comment]
Hello Robert,
No matter I click 'Download updates over Tor (recommended)' then click 'Save & Exit', next time I launch 'torbrowser-launcher --settings' the option is still unticked... :p

**Comment by micahflee** [comment]
0.1.9-2 works great from the FC21 repos, so I'm gonna close this.
