### ISSUE TITLE
TBB signing key will change?

### ISSUE THREAD

**Issue by adrelanos** [micahflee/torbrowser-launcher#161]
Transition smoothly away from Erinn's signing key for the coming releases:
https://trac.torproject.org/projects/tor/ticket/13407

**Comment by micahflee** [comment]
Thanks for pointing this out.

**Comment by micahflee** [comment]
It looks like the new signing key will be this one: http://hkps.pool.sks-keyservers.net/pks/lookup?op=vindex&search=0x4E2C6E8793298290&fingerprint=on with fingerprint EF6E286DDA85EA2A4BA7DE684E2C6E8793298290

I think it makes sense for the next release to include both this key and Erinn's key and accept sigs from either, for the time being.
