### ISSUE TITLE
Build on linux mint 16 incomplete

### ISSUE THREAD

**Issue by DennisonWilliams** [micahflee/torbrowser-launcher#162]
The build completes no problem but then running gave some error about not being able to load txsocksx.http.  To resolve this I had to install the txsocksx module.

**Comment by micahflee** [comment]
Installing the python-txsocksx package is already part of the build instructions for "Debian, Ubuntu, Linux Mint, etc.": https://github.com/micahflee/torbrowser-launcher/blob/master/BUILD.md

Just confirmed in a fresh installation of Linux Mint that I can build it if I install all the deps listed in BUILD.md.
