### ISSUE TITLE
TBB fails to run on ubuntu 14.04 - signature verification failing

### ISSUE THREAD

**Issue by grrrrr** [micahflee/torbrowser-launcher#164]
As of today when you run `torbrowser-launcher` version `0.1.7-ppa1-1` on `Ubuntu 14.04.1` it tries to upgraded to Tor Browser Bundle 4.5a3  and fails to verify signature

    Updating over Tor
    Finished receiving body: Response body fully received
    Running task: verify
    Verifying signature 
    gpg: Signature made Fri 16 Jan 2015 08:37:06 GMT using RSA key ID D40814E0
    gpg: Can't check signature: public key not found

I suspect the verification issue may be due to #161 not making to to PPA but also there is issue of torbrowser-laucnher trying to update to alpha branch when it should not

**Comment by srguglielmo** [comment]
This happens in Debian Jessie as well. I installed version `0.1.7-1` from the `contrib` repo.

```
Running task: download_tarball
Downloading https://www.torproject.org/dist/torbrowser/4.5a3/tor-browser-linux64-4.5a3_en-US.tar.xz
Updating over Tor
Finished receiving body: Response body fully received
Running task: verify
Verifying signature
gpg: assuming signed data in `/home/srg/.cache/torbrowser/download/sha256sums.txt'
gpg: Signature made Fri 16 Jan 2015 03:37:06 AM EST using RSA key ID D40814E0
gpg: Can't check signature: public key not found
```

I tried manually adding Erinn's key to my keyring, but it had no affect.
```
$ gpg --list-keys
/home/srg/.gnupg/pubring.gpg
----------------------------
pub   2048R/63FEE659 2003-10-16
uid                  Erinn Clark <erinn@torproject.org>
uid                  Erinn Clark <erinn@debian.org>
uid                  Erinn Clark <erinn@double-helix.org>
sub   2048R/EB399FD7 2003-10-16
```

**Comment by micahflee** [comment]
Eek yes, this is indeed #161. I simply haven't made a release with that change in it yet. I'll do that today.

**Comment by grrrrr** [comment]
thanks @micahflee .   

Is there a way to ignore alpha releases, I don't see anything in `--configure` or to even launch the browser if upgrade fails in such instances?

**Comment by micahflee** [comment]
Yes it's supposed to already do that, but it look like Tor changed their formatting in RecommendedTBBVersions, and the code that specifically ignores alphas broke. Just fixed it here: https://github.com/micahflee/torbrowser-launcher/commit/143cbf4ee13fa4b227688b1e55f69fd65b2decfc so it'll be in today's release too

**Comment by grrrrr** [comment]
For anyone following along at home, you will need to modify `~/.config/torbrowser/settings` to put the `latest_version` back to 4.0.3 otherwise it will still try to download the alpha branch.

**Comment by bobblestiltskin** [comment]
D40814E0 is the key used to sign the alpha and we see ...

gpg --search-keys D40814E0
gpg: searching for "D40814E0" from hkp server keys.gnupg.net
(1)	Tor Browser Developers (signing key) <torbrowser@torproject.org>
	  4096 bit RSA key 93298290, created: 2014-12-15
Keys 1-1 of 1 for "D40814E0".  Enter number(s), N)ext, or Q)uit > n
Enter number(s), N)ext, or Q)uit > 1
gpg: requesting key 93298290 from hkp server keys.gnupg.net
gpg: key 93298290: public key "Tor Browser Developers (signing key) <torbrowser@torproject.org>" imported
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   2  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 2u
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

**Comment by cowlicks** [comment]
I tried importing the key like @bobblestiltskin but I got a "no ultimately trusted keys found" error. I tried setting my personal key to be trusted ultimately. But this didn't help.

**Comment by ninetyfivenorth** [comment]
`$ gpg --gen-key`
