### ISSUE TITLE
apt-get remove torbrowser-bundle also removes onionshare

### ISSUE THREAD

**Issue by grrrrr** [micahflee/torbrowser-launcher#165]
For some reason when you do an `apt-get remove torbrowser-bundle` the command will also remove `onionshare` from the Ubuntu 14.04.1 system

    $ sudo apt-get remove torbrowser-launcher
    ....
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libmikmod2 libportmidi0 libsdl-mixer1.2 libsmpeg0 python-blinker
      python-flask python-itsdangerous python-lzma python-parsley python-pygame
      python-pyinotify python-stem python-twisted python-twisted-conch
      python-twisted-lore python-twisted-mail python-twisted-names
      python-twisted-news python-twisted-runner python-twisted-words
      python-txsocksx python-werkzeug
    ....
    The following packages will be REMOVED
      onionshare torbrowser-launcher
    0 to upgrade, 0 to newly install, 2 to remove and 3 not to upgrade.
    After this operation, 605 kB disk space will be freed.

The expected results are that `onionshare` is not removed as it is a separate install.

**Comment by micahflee** [comment]
This is because `torbrowser-launcher` is a dependency of `onionshare` (since at the moment OnionShare requires Tor Browser to be running in the background, and doesn't work with a system Tor). So `onionshare` is also getting removed because you're uninstalling its dependency.

**Comment by grrrrr** [comment]
@micahflee makes sense, thanks for the clarification
