### ISSUE TITLE
debian wheezy backport 0.1.7-1~bpo70+1: cannot verify with gpg key imported

### ISSUE THREAD

**Issue by greymuse** [micahflee/torbrowser-launcher#167]
Hi,
Wen upgrading to Torbrowser 4.5a3 the verification always fails, both when Tor's key is in keyring and not.
And when the key is in the gpg-keyring the verification fails even though I am manually able to verify the sha256sums.txt.asc file and that the sha256sum in the file sha256sums.txt is the same as of 
tor-browser-linux64-4.5a3_en-US.tar.xz.

Below is a simple patch that enabled the upgrade to finish. I did not try to find a good solution, just to get something that worked.
The change in 'def start_launcher' was just to get the torbrowser to start when no Tor gpg key is in keyring so that one can go on the web and hunt down Tor's key; some further upgrading pop-up windows appear when launching the browser this way, but I did nothing to fix that.

The changes to 'def verify' made the upgrade complete, so this bug report is written in torbrowser 4.5a3.
'diff -u' patch for the file launcher.py:

    --- /usr/share/pyshared/torbrowser_launcher/launcher.py	2014-12-02 19:05:10.000000000 +0100
    +++ launcher.py	2015-01-26 02:19:19.421333792 +0100
    @@ -152,9 +152,15 @@
		     self.run(False)
		     self.launch_gui = False
		 elif installed_version < latest_version:
    -                print _('TBB is out of date, attempting to upgrade to {0}'.format(latest_version))
		     # there is a tbb upgrade available
    -                self.set_gui('task', _("Your Tor Browser is out of date. Upgrading from {0} to {1}.".format(installed_version, latest_version)),
    +                if subprocess.call(['/usr/bin/gpg', '--list-key', '0x2E1AC68ED40814E0']):
    +                    print _('Although old version of Tor browser is installed, no Tor project GPG key is installed; we launch old browser. Go to page https://xxxxx for information about how to get and import Tor gpg key.')
    +                    # current version of tbb is installed, launch it
    +                    self.run(False)
    +                    self.launch_gui = False
    +                else:
    +                    print _('TBB is out of date, attempting to upgrade to {0}'.format(latest_version))
    +                    self.set_gui('task', _("Your Tor Browser is out of date. Upgrading from {0} to {1}.".format(installed_version, latest_version)),
				  ['download_sha256',
				   'download_sha256_sig',
				   'download_tarball',
    @@ -545,27 +551,42 @@
	     self.build_ui()

	 def verify(self):
    +        gpg_verif = False
    +        has_gpg_key = False
	     # initialize the progress bar
    -        self.progressbar.set_fraction(0)
    -        self.progressbar.set_text(_('Verifying Signature'))
    -        self.progressbar.show()
    +        #self.progressbar.set_fraction(0)
    +        #self.progressbar.set_text(_('Verifying Signature'))
    +        #self.progressbar.show()

	     verified = False
	     # check the sha256 file's sig, and also take the sha256 of the tarball and compare
    -        p = subprocess.Popen(['/usr/bin/gpg', '--homedir', self.common.paths['gnupg_homedir'], '--verify', self.common.paths['sha256_sig_file']])
    -        self.pulse_until_process_exits(p)
    -        if p.returncode == 0:
    +        #p = subprocess.call(['/usr/bin/gpg', '--homedir', self.common.paths['gnupg_homedir'], '--verify', self.common.paths['sha256_sig_file']])
    +        p = subprocess.call(['/usr/bin/gpg', '--verify', self.common.paths['sha256_sig_file']])
    +        #self.pulse_until_process_exits(p)
    +        if p == 0:
    +            gpg_verif = True
		 # compare with sha256 of the tarball
		 tarball_sha256 = hashlib.sha256(open(self.common.paths['tarball_file'], 'r').read()).hexdigest()
		 for line in open(self.common.paths['sha256_file'], 'r').readlines():
		     if tarball_sha256.lower() in line.lower() and self.common.paths['tarball_filename'] in line:
			 verified = True
    +        else:
    +            #p = subprocess.call(['/usr/bin/gpg', '--homedir', self.common.paths['gnupg_homedir'], '--list-key', '0x2E1AC68ED40814E0'])
    +            p = subprocess.call(['/usr/bin/gpg', '--list-key', '0x2E1AC68ED40814E0'])
    +            if p == 0:
    +                has_gpg_key = True

	     if verified:
		 self.run_task()
	     else:
		 # TODO: add the ability to report attack by posting bug to trac.torproject.org
    -            self.set_gui('task', _("SIGNATURE VERIFICATION FAILED!\n\nYou might be under attack, or there might just be a networking problem. Click Start try the download again."), ['start_over'], False)
    +            if not has_gpg_key:
    +                error_msg = "GPG KEY IS MISSING!\n\nYou need to get hold of the Tor project's gpg key (id " + gpg_id + "). See web page: https://xxxxx. When you have imported the gpg key, try again"
    +            if gpg_verif:
    +                error_msg = "CHECKSUM FAILED!\n\nFile checksum failed. You might be under attack, or there might just be a networking problem. Click Start try the download again."
    +            else:
    +                error_msg = "SIGNATURE VERIFICATION FAILED!\n\nVerification of GPG signature of downloaded files failed. You might be under attack, or there might just be a networking problem. Click Start try the download again."]
    +            self.set_gui('task', _(error_msg), ['start_over'], False)
		 self.clear_ui()
		 self.build_ui()

    @@ -674,4 +695,3 @@
		 delattr(self, 'current_download_url')
	     if reactor.running:
		 reactor.stop()
    -

**Comment by greymuse** [comment]
Hi,
I should perhaps add that the final change that made it work was removing the arguments

   '--homedir', self.common.paths['gnupg_homedir'],

from the gpg commands. So maybe that was the only problem...

**Comment by micahflee** [comment]
Hey @greymuse actually the issue is that the Tor Project updated their signing key. Version 0.1.8 (which I guess hasn't made it to wheezy backports yet) includes the new signing key. (I've also released 0.1.9 since then too.)

A workaround is follow the instructions here https://github.com/micahflee/torbrowser-launcher/blob/master/BUILD.md and build from source.
