### ISSUE TITLE
Failed updates prevents working browser from launching

### ISSUE THREAD

**Issue by jklljklkjhlk1user** [micahflee/torbrowser-launcher#168]
torbrowser-launcher has had frequent and debilitating bugs with it's update functionality and these bugs have been made much worse by the fact that it will not launch an un-updated version of the browser (even if the update is not critical such that the previous version still works).

To work around this issue you should use the following command which automatically launches the last installed version of the tor browser bundle that was installed by torbrowser-launcher BEFORE initiating the usual update/launch procedure:

`$HOME/.local/share/torbrowser/tbb/*/tor-browser_en-US/start-tor-browser -allow-remote about:tor && /usr/bin/torbrowser-launcher about:tor `

**Comment by greymuse** [comment]
Here is a patch that fixes this for version 0.2.0 (or rather version 0.2.0-2 on debian stretch/jessie).

The idea is this: if download or SSL check fails, then you get the option to start the installed tor browser; and if the launcher is totally confused as to which version is the newest the installed browser is automatically launched.

If you download the debian source package with apt-get source torbrowser-launcher, you go into folder torbrowser-launcher-0.2.0/torbrowser_launcher and apply the patch there (and re-build and install the package), or you could apply it to the installed file at /usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py


Beware: I've just done some minor and incomplete testing. - Currently a hardened version of torbrowser cannot be installed and you can only exit, this patch solves that problem at least...


    --- launcher.py-old	2015-05-18 17:17:54.000000000 +0200
    +++ launcher.py	2015-11-07 19:34:20.322282221 +0100
    @@ -40,6 +40,9 @@
     pygtk.require('2.0')
     import gtk

    +class NonCriticalException(Exception):
    +    pass
    +
     class TryStableException(Exception):
	 pass

    @@ -162,7 +165,12 @@
				   'run'])
		 else:
		     # for some reason the installed tbb is newer than the current version?
    -                self.set_gui('error', _("Something is wrong. The version of Tor Browser Bundle you have installed is newer than the current version?"), [])
    +                #self.set_gui('error', _("Something is wrong. The version of Tor Browser Bundle you have installed is newer than the current version?"), [])
    +                print _('TBB version confusion (installed version: {0}, latest version: {1}).'.format(installed_version, latest_version))
    +                print _("SOMETHING IS WRONG. We launch installed Tor Browser anyway.")
    +                self.set_gui('task',
    +                             _("SOMETHING IS WRONG. We launch installed Tor Browser anyway."),
    +                             ['run'], True)

	     # not installed
	     else:
    @@ -227,6 +235,8 @@
			 self.yes_button.connect("clicked", self.try_default_mirror, None)
		     elif self.gui == 'error_try_tor':
			 self.yes_button.connect("clicked", self.try_tor, None)
    +                elif self.gui == 'error_with_option_to_launch_installed':
    +                    self.yes_button.connect("clicked", self.launch_installed_tor_version, None)
		     self.button_box.add(self.yes_button)
		     self.yes_button.show()

    @@ -354,7 +364,11 @@
			 if common.settings['mirror'] != common.default_mirror:
			     raise TryDefaultMirrorException(_("Download Error: {0} {1}\n\nYou are currently using a non-default mirror:\n{2}\n\nWould you like to switch back to the default?").format(response.code, response.phrase, common.settings['mirror']))
			 else:
    -                        raise DownloadErrorException(_("Download Error: {0} {1}").format(response.code, response.phrase))
    +                        start = common.paths['tbb']['start']
    +                        if os.path.isfile(start) and os.access(start, os.X_OK):
    +                            raise NonCriticalException(_("Download Error: {0} {1}\n\nCould not download file:\n{2}\n\nHence, cannot install newer version.\n\nClick 'Yes' if you would like to launch the already installed Torbrowser, which is old and might contain unfixed security issues.").format(response.code, response.phrase, url.format(common.settings['mirror'])))
    +                        else:
    +                            raise DownloadErrorException(_("Download Error: {0} {1}\n\nCould not download file:\n{2}").format(response.code, response.phrase, url.format(common.settings['mirror'])))

		 def dataReceived(self, bytes):
		     self.file.write(bytes)
    @@ -406,6 +420,10 @@
		 f.trap(TryDefaultMirrorException)
		 self.set_gui('error_try_default_mirror', str(f.value), [], False)

    +        elif isinstance(f.value, NonCriticalException):
    +            f.trap(NonCriticalException)
    +            self.set_gui('error_with_option_to_launch_installed', str(f.value), [], False)
    +
	     elif isinstance(f.value, DownloadErrorException):
		 f.trap(DownloadErrorException)
		 self.set_gui('error', str(f.value), [], False)
    @@ -424,7 +442,12 @@
			 if not self.common.settings['update_over_tor']:
			     self.set_gui('error_try_tor', _('The SSL certificate served by https://www.torproject.org is invalid! You may be under attack. Try the download again using Tor?'), [], False)
			 else:
    -                        self.set_gui('error', _('The SSL certificate served by https://www.torproject.org is invalid! You may be under attack.'), [], False)
    +                        #self.set_gui('error', _('The SSL certificate served by https://www.torproject.org is invalid! You may be under attack.'), [], False)
    +                        # This allows user to launch currently installed tor-browser rather than exit without any browser at all:
    +                        if os.path.isfile(start) and os.access(start, os.X_OK):
    +                            self.set_gui('error_with_option_to_launch_installed', _("The SSL certificate served by https://www.torproject.org is invalid! You may be under attack.\n\nWe therefore do not install the new tor browser version.\n\nClick 'Yes' if you want to launch the already installed Tor browser, which is old and might contain unfixed security issues. (And please report this by filing a bug at https://trac.torproject.org)"), [], False)
    +                        else:
    +                            self.set_gui('error', _('The SSL certificate served by https://www.torproject.org is invalid! You may be under attack.'), [], False)

	     else:
		 self.set_gui('error', _("Error starting download:\n\n{0}\n\nAre you connected to the internet?").format(f.value), [], False)
    @@ -488,6 +511,10 @@
	     subprocess.Popen([self.common.paths['tbl_bin']])
	     self.destroy(False)

    +    def launch_installed_tor_version(self, widget, data=None):
    +        print _('Running installed version'), self.common.paths['tbb']['start']
    +        self.run()
    +
	 def attempt_update(self):
	     # load the update check file
	     try:

**Comment by greymuse** [comment]
Well, to automatically start the browser when "confused", i.e. when installed version is newer, is perhaps not a very good idea since that enables blocking/downgrade attacks, so that should present user with a launch option instead, perhaps, so one has the option to launch after having checked things out first.

**Comment by micahflee** [comment]
This is no longer an issue because of #198. In the upcoming release, Tor Browser Launcher will no longer check for updates. Instead, Tor Browser itself will be in charge of updating.
