### ISSUE TITLE
4.5a5 will likely not be startable because location of start-tor-browser changed

### ISSUE THREAD

**Issue by adrelanos** [micahflee/torbrowser-launcher#176]
`./start-tor-browser` will be moved to `Browser/start-tor-browser`. I know this, because I looked into 4.5a5. Related changelog. Quote https://blog.torproject.org/blog/tor-browser-45a5-released:

> We're very excited about the usability and security improvements in this release. On the usability front, we've created a FreeDesktop-compatible launcher wrapper for Linux that can be invoked from either the GUI or the shell, and we also provide Windows users with the ability to add optional Start Menu and Desktop shortcuts.

Related IRC log:

```
<Patrick> is it considered sane to start TBB/Browser/start-tor-browser ? @ GeKo 
<Patrick> for start of TBB from terminal
<arma> patrick: that's how i do it. seems to work for me.
<Patrick> i see
<Patrick> i hope that script will stay in that place, because moving the file around breaks torbrowser-launcher and tb-updater
<arma> patrick: yeah, i have no idea why they moved it
<arma> i wonder if there's a ticket for moving it
<arma> or if they even know they did
<Patrick> will report a bug against torbrowser-launcher
<arma> patrick: https://trac.torproject.org/projects/tor/ticket/13375 looks related
-zwiebelbot/#tor- tor#13375: Tor Browser Script can't be launched from the Linux desktop - https://bugs.torproject.org/13375
```

**Comment by adrelanos** [comment]
```
<GeKo> Patrick: as long as you are not removing it it is staying but the new alpha does not have it anymore due to #13775
-zwiebelbot/#tor- tor#13775: Tor Browser won't open with OpenVPN - https://bugs.torproject.org/13775
<Patrick> GeKo:  So where will it be moved? Or how to start TBB from terminal by then?
<GeKo> ./start-tor-browser.desktop
```

**Comment by MarkCSmith** [comment]
I think it might be better for torbrowser-launcher to use ./Browser/start-tor-browser (that script has not moved, although the symlink with the same name that sat above it, i.e., next to the Browser directory, is gone).

**Comment by adrelanos** [comment]
Why is that?

Do you think ./start-tor-browser.desktop won't last for long either?

**Comment by MarkCSmith** [comment]
You might ask other developers for their opinion, but since Browser/start-tor-browser is the script that really starts the browser and because it is something that advanced users may modify, I think the Tor Browser team is less likely to move it in the future.  That is just a "gut feeling" on my part though. An argument can also be made that the .desktop file is at the top level and therefore more users may know about it, which means renaming or moving it would be more disruptive.

**Comment by adrelanos** [comment]
I see. I am in favor of ./start-tor-browser.desktop to prevent subtle browser fingerprint issues vs being a subset that just uses Browser/start-tor-browser. The "do as most others" credo. But that could just be FUD.

**Comment by micahflee** [comment]
Sorry about being flaky, I've been traveling and just realizing this is a serious issue!

I also prefer the idea of running ./start-tor-browser.desktop, except that if you choose to allow opening links from external programs with Tor Browser (basically if you want to set it as your default browser) TBL passes custom `-allow-remote` into Browser/start-tor-browser. So to keep this functionality, TBL must call the bash script. I'll go ahead and do that for now, but maybe change this in the future.

**Comment by micahflee** [comment]
Actually, it looks like the `-allow-remote` trick stopped working. After manually testing, it looks like opening URLs in Tor Browser doesn't work anymore with the new `Browser/start-tor-browser` script (which looks like it has changed a bunch). You can open Tor Browser with a URL the first time it's open, but if you have an already open window you can't open new tabs by calling it again.

That's a shame, but I'll go ahead and remove the default browser feature.

**Comment by micahflee** [comment]
Wow, executing .desktop files turns out to be nontrivial. https://askubuntu.com/questions/5172/running-a-desktop-file-in-the-terminal

**Comment by adrelanos** [comment]
./start-tor-browser.desktop
works for me.

**Comment by micahflee** [comment]
@adrelanos that's only if you're in the same directory. Try going to your home directory and running `~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop`. This is what happens for me, in a couple of different platforms:

```
micah@ubuntu-dev:~$ ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop 
/usr/bin/env: ./Browser/execdesktop: No such file or directory
```

**Comment by adrelanos** [comment]
Could be a bug in `start-tor-browser.desktop` or general issue with `.desktop` files.

Anyhow... What works...

Why not `cd` into that folder before running `./start-tor-browser.desktop`? This is what [tb-starter](https://github.com/Whonix/tb-starter) does. That works.

**Comment by micahflee** [comment]
Good idea, looks like you can pass cwd into subprocess.call: https://github.com/micahflee/torbrowser-launcher/commit/5f833d73290bd3623bf22caffaed599381d454d9

**Comment by MarkCSmith** [comment]
For what it's worth, these two commands worked for me with Tor Browser 4.5 on Ubuntu 14.04 (the second one opens a new tab in the already running first browser):

./Browser/start-tor-browser -allow-remote &
./Browser/start-tor-browser -allow-remote http://torproject.org/

If -allow-remote is not working for you, please open a Tor Browser trac ticket via https://trac.torproject.org/projects/tor/newticket
