### ISSUE TITLE
Stop using sha256sums.txt and sha256sums.txt.asc

### ISSUE THREAD

**Issue by micahflee** [micahflee/torbrowser-launcher#180]
Mike Perry has told me that Tor Browser is phasing out the use of sha256sums.txt in favor of signing individual binaries.

Right now torbrowser-launcher downloads sha256sums.txt and sha256sums.txt.asc and verifies it, and then calculates the sha256sum of the binary in order to verify that there wasn't an attack during the download.

We need to change it so that it just downloads the binary (e.g. `tor-browser-linux32-4.5_en-US.tar.xz`) and its signature (e.g. `tor-browser-linux32-4.5_en-US.tar.xz.asc`) and verifies that directly.

**Comment by adrelanos** [comment]
Is there any upstream ticket about this?

This is bad. Breaks Tor Browser downloaders and worsens security.

sha256sum helped to authenticate filenames... Because... 

GPG signatures do not authenticate filenames:
https://trac.torproject.org/projects/tor/ticket/2340

**Comment by micahflee** [comment]
Mike wrote:

> We recently started signing our windows exes using a digicert
> authenticode token in TBB since 4.5a4. When we released 4.5-stable, we
> noticed there was still some confusion in our Windows users who are
> still using sha256sums.txt to verify their packages. Because the
> sha256sums.txt file contains the build result exe sha256sums, and not
> the sha256sums of the exes after signing them with our token, users were
> confused by the resulting sha256sum mismatch. 
> 
> We had attempted to update our signature verification documentation to
> describe this
> (https://www.torproject.org/docs/verifying-signatures.html.en#BuildVerification)
> but it seems that people are just assuming that things still work the
> old way.
> 
> This has led us to decide to rename the sha256sums.txt file and
> associated detached signatures to something like
> 'sha256sums-presigned-build.txt' in the hopes that it will clue people
> in to the fact that the sha256sums in it may not match what they just
> downloaded. Here's our ticket where we brainstormed some ideas before
> arriving at that one:
> https://trac.torproject.org/projects/tor/ticket/15864

**Comment by adrelanos** [comment]
I don't think this was a necessary / good change. sha256sums.txt and
sha256sums.txt.asc were not actually deprecated. Now with direct
verification only, it got actually less secure. (See my "gpg does not
verify file names' argument above.)

**Comment by micahflee** [comment]
I know that the sha256sums.txt.asc isn't deprecated yet, but it seems wise to heed Mike's advice here so everyone doesn't get false positive MITM warnings one day.

Downgrade attackers are mitigated here because TBL detects the version that's installed before running it. If it detects an earlier version installed, it will just try to update again: https://github.com/micahflee/torbrowser-launcher/blob/master/torbrowser_launcher/launcher.py#L160

It's also somewhat mitigated by the fact that Tor Browser auto-updates itself. So I agree it's not ideal, but it seems better than risking everything breaking in the future.
