### ISSUE TITLE
building under jessie

### ISSUE THREAD

**Issue by 0xcaca0** [micahflee/torbrowser-launcher#183]
under Debian Jessie build_deb.sh currently fails after following BUILD.md instructions:

    dh_auto_clean: unable to load build system class 'pybuild': Can't locate Debian/Debhelper/Buildsystem/pybuild.pm in @INC (you may need to install the Debian::Debhelper::Buildsystem::pybuild module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at (eval 3) line 2.

You also require the 'dh-python' package.

**Comment by micahflee** [comment]
Good catch. `dh-python` is already listed as a build-dependency in `stdeb.cfg`, but I've added it to `BUILD.md` too.
