### ISSUE TITLE
TBB not an option when setting default browser

### ISSUE THREAD

**Issue by grrrrr** [micahflee/torbrowser-launcher#189]
Running  Ubuntu 14.04 and Torbrowser-launcher 0.2.0.1-1.

Has the option to set TBB as a default browser been removed?  When I go to `system settings` -> `details` -> `default applications`  in ubuntu, for browser I do not see TBB listed, just the other browsers installed on the system

**Comment by johndavidmartinez** [comment]
The following worked for me as a quick fix.
Open the following file in your text-editor of choice
```
~/.local/share/applications/torbrowser.desktop
```
Add the following text.
```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Icon[en_US]=browser
Name[en_US]=Tor Browser
Exec=/path/to/tor/browser
Name=Tor Browser
Icon=browser
```
Then run this command in the command-line.
```
xdg-settings set default-web-browser torbrowser.desktop
```

**Comment by adrelanos** [comment]
Changing the default browser on Linux isn't trivia. Therefore, setting up Tor Browser as default browser isn't trivial. To implement this... Perhaps...

The [tb-default-browser](https://github.com/Whonix/tb-default-browser) package configures `torbrowser` (ex: `/usr/bin/torbrowser`) as default browser. ([tb-default-browser](https://github.com/Whonix/tb-default-browser) is related to [tb-starter](https://github.com/Whonix/tb-starter) and [tb-updater](https://github.com/Whonix/tb-updater))

I could modify the [tb-default-browser](https://github.com/Whonix/tb-default-browser) package to start either `torbrowser` or `torbrowser-launcher`. Could you upload the package to Debian? Alternativly, you could re-implement its functionality into torbrowser-launcher.

**Comment by micahflee** [comment]
Yes, this feature has been reviewed. You can see #157 for more details. But basically, Tor Browser removed support for passing `-no-remote`, which means that you can't pass external URLs into it, which sort of defeats the purpose of using it as your default browser (e.g. you click a link and Tor Browser will open, but not load your link). Also, there was a bug that was never solved where if Firefox is open in the background, the link would open in that instead of Tor Browser.

**Comment by adrelanos** [comment]
Micah Lee:
> Yes, this feature has been reviewed. You can see #157 for more
> details. But basically, Tor Browser removed support for passing
> `-no-remote`, which means that you can't pass external URLs into it,
> which sort of defeats the purpose of using it as your default browser
> (e.g. you click a link and Tor Browser will open, but not load your
> link). Also, there was a bug that was never solved where if Firefox
> is open in the background, the link would open in that instead of Tor
> Browser.

I think there is no blocker here.

1) opening links in Tor Browser as default browser works [tested in Whonix]

2) you can pass arbitrary command line options including -no-remote from
start-tor-browser.desktop to Tor Browser / Firefox.
