### ISSUE TITLE
[Q] What is the canonical way to install this for Debian Jessie / stable?

### ISSUE THREAD

**Issue by vuarnet** [micahflee/torbrowser-launcher#195]
I use apt-listbugs to hopefully avoid buggy software, and several current bugs popped up when trying to install torbrowser-launcher from Debian stable repo. It looks like those issues are mostly fixed in backports, but I currently don't have backports enabled at all on my system... I certainly don't want to be susceptible to bugs, so if I'm on Debian stable / jessie, is the canonical method of installing tb-launcher to use jessie backports?

Thanks for the awesome work!

**Comment by micahflee** [comment]
It should be just running `apt-get install torbrowser-launcher`. Sorry about the buggyness, but I think after the release of 0.2.2 there should be way fewer problems.
