### ISSUE TITLE
start-tor-browser location has changed

### ISSUE THREAD

**Issue by meejah** [micahflee/torbrowser-launcher#199]
User "sine0" in #tor complained about torbrowser-launcher not working on Debian Jessie. I can confirm this is the case: ``start-tor-browser`` has moved down a sub-directory to ``Browser/start-tor-browser``. I am not sure what version this started happening.

**Comment by micahflee** [comment]
This was fixed awhile ago. TBL actually executes `start-tor-browser.desktop`, which in turn executes `Browser/start-tor-browser`. I think sine0 must be running an older version.
