### ISSUE TITLE
Implement a human-readable method for storing/changing settings

### ISSUE THREAD

**Issue by mckinney-subgraph** [micahflee/torbrowser-launcher#201]
Python pickling is not a very portable method of storing torbrowser-launcher settings. Having a more portable way of changing the settings may be useful to people who want to distribute operating system packages with different settings (without patching the code or having to pickle a new batch).

Some alternatives ideas spring to mind:
1. JSON or YAML 
2. Environment variables (similar to how the Tor browser supports skipping launch or changing port information)

**Comment by micahflee** [comment]
I agree, the pickle format is annoying. I vote for json.
