### ISSUE TITLE
Ubuntu 14.04: cannot import name IPolicyForHTTPS

### ISSUE THREAD

**Issue by janhh** [micahflee/torbrowser-launcher#206]
I receive missing IPolicyForHTTPS dependency message after upgrading to torbrowser-launcher 0.2.1-1 from ppa.

```
$ torbrowser-launcher
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 29, in <module>
    import torbrowser_launcher
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 33, in <module>
    from launcher import Launcher
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 33, in <module>
    from twisted.web.iweb import IPolicyForHTTPS
ImportError: cannot import name IPolicyForHTTPS
```
I found this commit: a0634fa8b3422ba6dc146af3a5ab2cc5cf1e2c10

The python-twisted packages are listed as version 13.2.0-1ubuntu1 in Ubuntu and python version is returned as 2.7.6.

**Comment by micahflee** [comment]
Confirmed. It looks like it's probably a missing dependency in Ubuntu, lemme figure out which one.

**Comment by micahflee** [comment]
Yup, it's because Ubuntu 14.04 has python-twisted-web 13.2.0, but IPolicyForHTTPS wasn't implemented until version 14.0: https://twistedmatrix.com/documents/15.2.1/api/twisted.web.iweb.IPolicyForHTTPS.html

**Comment by micahflee** [comment]
I'd love to make this working again on systems with older python-twisted-web right away, but I'm pushing it off to the next release. I'll need to detect if IPolicyForHTTPS is available, and if not fall back to some other method of certificate pinning (or just not certificate pin for older versions, and trust the CAs?)

**Comment by micah** [comment]
I'll note that this isn't just Ubuntu 14.04, its also happening in Debian (unstable), here is the bug report about it:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804270

**Comment by micah** [comment]
oops, clicked that button too soon... in debian I've got 15.2.1-1 of python-twisted installed (including python-twisted-web), so it seems like there is something else going on here?

**Comment by sedouard** [comment]
I'm getting the same issue here on 14.04. Is there another repository to get updated python-twisted from?

**Comment by jgreth** [comment]
Same here on Lubuntu 14.04 (Distributor ID:	Ubuntu,Description:	Ubuntu 14.04.2 LTS,Release:	14.04Codename: trusty)
Can you tell where (repo) to update python-twisted from?

**Comment by brbsix** [comment]
Instructions may vary, but here is what I did to solve this:

    sudo apt-get install python2.7-dev     # necessary to build twisted
    pip2 install --upgrade --user twisted  # install latest release of twisted to user installation directory
    pip2 install --user service_identity   # necessary for secure communications

**Comment by zmanian** [comment]
It might be nice to handle the import error with message suggesting the work around above.

**Comment by micahflee** [comment]
IPolicyForHTTPS is only needed for certificate pinning. Because #224 removes cert pinning, it also removes this problem. I've tested master branch in Ubuntu 14.04 and it works great.

**Comment by KreAch3R** [comment]
@micahflee and everyone else interested: I am using Linux Mint 17.3 (based on Ubuntu 14.04) and I still needed to follow @brbsix's instructions to get it to launch. I checked and I was using the master branch (and the #224 was in the commit history). 
Just a heads up.
