### ISSUE TITLE
Ubuntu 15.10 - Update fails with 404 download error or SIGNATURE VERIFICATION FAILED

### ISSUE THREAD

**Issue by ByteCommander** [micahflee/torbrowser-launcher#208]
Probably related to issue #206 

I've written a [question on AskUbuntu.com about this](http://askubuntu.com/q/695739/367990):

I use `torbrowser-launcher` (package version 0.2.0-2 from the Wily/universe amd64 repository on Ubuntu 15.10) which runs *Tor Browser 5.0.4*.

Since today, after the update to *5.5a4-hardened* became available, `torbrowser-launcher` does not start the browser any more but tries to update itself. This however fails due to a **Download error: 404 Not Found** as you can see in the two screenshots below. If I click <kbd>Yes</kbd> when it asks to switch to the default mirror, that doesn't change anything. Still the same error. And on the next try, it will still complain about a non-default mirror.

[![enter image description here][1]][1]  
[![enter image description here][2]][2]

When I run `torbrowser-launcher` in a terminal, I get this:

    Tor Browser Launcher
    By Micah Lee, licensed under MIT
    version 0.2.0
    https://github.com/micahflee/torbrowser-launcher
    Updating over Tor
    Checked for update within 24 hours, skipping
    TBB is out of date, attempting to upgrade to 5.5a4-hardened
    Downloading https://dist.torproject.org/torbrowser/5.5a4-hardened/sha256sums.txt
    Traceback (most recent call last):
      File "/usr/bin/torbrowser-launcher", line 30, in <module>
        torbrowser_launcher.main()
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 69, in main
        app = Launcher(common, url_list)
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 130, in __init__
        self.build_ui()
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 284, in build_ui
        self.start(None)
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 293, in start
        self.run_task()
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 318, in run_task
        self.download('signature', self.common.paths['sha256_url'], self.common.paths['sha256_file'])
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 454, in download
        agent = SOCKS5Agent(reactor, VerifyTorProjectCert(self.common.paths['torproject_pem']), proxyEndpoint=torEndpoint)
      File "/usr/lib/python2.7/dist-packages/txsocksx/http.py", line 58, in __init__
        super(_SOCKSAgent, self).__init__(*a, **kw)
      File "/usr/lib/python2.7/dist-packages/txsocksx/http.py", line 37, in __init__
        'contextFactory must implement IPolicyForHTTPS')
    NotImplementedError: contextFactory must implement IPolicyForHTTPS

If I open the Tor Browser Settings from terminal `torbrowser-launcher --settings`, select a different mirror and to "search for updates on next launch", then click on <kbd>Launch TorBrowser</kbd>, I get the following dialogue and terminal output (first answering <kbd>Start</kbd>, second time answering <kbd>Exit</kbd>):

[![enter image description here][3]][3]

    $ torbrowser-launcher --settings
    Tor Browser Launcher
    By Micah Lee, licensed under MIT
    version 0.2.0
    https://github.com/micahflee/torbrowser-launcher
    $ Tor Browser Launcher
    By Micah Lee, licensed under MIT
    version 0.2.0
    https://github.com/micahflee/torbrowser-launcher
    Updating over Tor
    Checking for update
    Downloading https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions
    Checking to see if update is needed
    TBB is out of date, attempting to upgrade to 5.5a4-hardened
    Downloading https://www.oignon.net/dist/torbrowser/5.5a4-hardened/sha256sums.txt
    Download error: [<twisted.python.failure.Failure <class 'service_identity.exceptions.VerificationError'>>] <class 'twisted.web._newclient.ResponseNeverReceived'>
    Downloading https://www.oignon.net/dist/torbrowser/5.5a4-hardened/sha256sums.txt.asc
    Download error: [<twisted.python.failure.Failure <class 'service_identity.exceptions.VerificationError'>>] <class 'twisted.web._newclient.ResponseNeverReceived'>
    Downloading https://www.oignon.net/dist/torbrowser/5.5a4-hardened/tor-browser-linux64-5.5a4-hardened_en-US.tar.xz
    Download error: [<twisted.python.failure.Failure <class 'service_identity.exceptions.VerificationError'>>] <class 'twisted.web._newclient.ResponseNeverReceived'>
    Verifying signature
    Starting download over again
    Downloading https://www.oignon.net/dist/torbrowser/5.5a4-hardened/tor-browser-linux64-5.5a4-hardened_en-US.tar.xz
    Download error: [<twisted.python.failure.Failure <class 'service_identity.exceptions.VerificationError'>>] <class 'twisted.web._newclient.ResponseNeverReceived'>

What is wrong here and how can it be fixed?

  [1]: http://i.stack.imgur.com/KWujm.png
  [2]: http://i.stack.imgur.com/U26ff.png
  [3]: http://i.stack.imgur.com/FBjcT.png

**Comment by ByteCommander** [comment]
As a workaround, I'm now (temporarily?) using the package `tor-browser` from the [WebUpd8Team PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/tor-browser) and purged `torbrowser-launcher`.

**Comment by micahflee** [comment]
Tor recently released a hardened version of Tor Browser:
https://blog.torproject.org/blog/tor-browser-55a4-hardened-released

And they changed their RecommendedTBBVersions file to include it:
https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions

So Tor Browser Launcher gets confused with the new format and thinks that 5.5a4-hardened-Linux is the latest stable version, rather than 5.0.4-Linux.

This is all fixed though in the latest version of Tor Browser Launcher, which hasn't yet made it to the Ubuntu repositories. You can make sure you have the latest version by installing it from my PPA:

```sh
sudo add-apt-repository ppa:micahflee/ppa
sudo apt-get update
sudo apt-get install torbrowser-launcher
```

If your files are still in a broken state for whatever reason, you can open `Tor Browser Launcher Settings` and click `Reinstall Tor Browser`, or you can delete all of the local files to start over:

```sh
rm -rf ~/.cache/torbrowser ~/.local/share/torbrowser ~/.config/torbrowser
```

**Comment by ldmpub** [comment]
Hi,

Many thanks for these clear explainations and for the fix because Tor Browser Launcher is still not updated in Ubuntu repositories for Ubuntu 15.10 Wily.

**Comment by james-nesbitt** [comment]
Just got the same error on Fedora (25).  Solved it by installing tor as a service, starting it, and then telling the browser installer to install over the system tor.
