### ISSUE TITLE
Implement a network transport that is not Twisted

### ISSUE THREAD

**Issue by mckinney-subgraph** [micahflee/torbrowser-launcher#213]
Hello,

Twisted seems to be causing a lot of problems on Debian Stretch (and possibly other distros?). It is probably also overkill/bloat for simply downloading TBB. How about using something like Python stdlib + a Socks library such as PySocks as an alternative? Even just having the option of selecting this as a backup transport would be nice for times when Twisted is broken.

**Comment by micahflee** [comment]
I agree. The main reason I've been keeping it was because the certificate pinning implementation required it, but that's been removed (#224).
