### ISSUE TITLE
AppArmor denial on start using jessie-backports

### ISSUE THREAD

**Issue by henry-bennett** [micahflee/torbrowser-launcher#216]
Before installation, `apparmor` and `apparmor-profiles` installed.

Installed from `jessie-backports`.  Used "Tor Browser" menu icon, and download of Tor Browser went fine.  However, at the end, when it should have launched, it just disappeared.

`/var/log/kern.log` reveals:

```
12 10:58:24 debian kernel: [338208.915831] audit: type=1400
audit(1449939504.305:72): apparmor="DENIED" operation="exec"
profile="/home/*/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/{Browser/,}start-tor-browser"
name="/bin/bash" pid=23850 comm="start-tor-brows" requested_mask="x"
denied_mask="x" fsuid=1000 ouid=0
```

**Comment by h01ger** [comment]
Sadly you didnt say which version from jessie-backports you've tried, as far as I know this is fixed in 0.2.2-2~bpo8+1 from jessie-backports, can you confirm?

**Comment by u451f** [comment]
This will be fixed as soon as we release 0.2.5 jessie-backports. It's on its way Please try the new version and report back. And then this bug can be closed IMO.

**Comment by intrigeri** [comment]
jessie-backports now has 0.2.6-2~bpo8+1, so according to u451f's previous comment, this bug can be closed. Untested though.

**Comment by intrigeri** [comment]
The problem this bug was out was fixed 1+ year ago, please close.

**Comment by ageis** [comment]
Closing per previous comment.
