### ISSUE TITLE
wrongly detects language

### ISSUE THREAD

**Issue by h01ger** [micahflee/torbrowser-launcher#220]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753173 was has lots of more background about this issue. Basically, if you've set any LC_ variable to an existing locale, torbrowser will start in this languge, which is wrong, as many LC_ variables have nothing to do with UI language.

The fix is rather simple (and confirmed by me):

http://sources.debian.net/src/torbrowser-launcher/0.2.2-3/torbrowser_launcher/common.py/#L74

which currently reads:

  default_locale = locale.getdefaultlocale()[0]

should instead be:

  default_locale = locale.getlocale(locale.LC_MESSAGES)[0]

**Comment by rogers0** [comment]
https://github.com/micahflee/torbrowser-launcher/commit/b828bdfafe60bb9bcf93ec660ad5c07ff7fdbdf5
reverted previous fix, so it's broken again.
Could you kindly consider to revert? Thanks!
