### ISSUE TITLE
twisted-error on Fedora23

### ISSUE THREAD

**Issue by nielsk** [micahflee/torbrowser-launcher#222]
When I try to install the tor-browser via the tor-launcher I get the following error on Fedora 23:

`Download error: Connection was refused by other side: 111: Connection refused. <class 'twisted.internet.error.ConnectionRefusedError'>`
python-txsocksx is at version 1.15.0.2-1 apparently (package name is python-txsocksx-1.15.0.2-1.fc23.noarch)

Any ideas what I can do to fix this on my side?

**Comment by nielsk** [comment]
torbrowser-launcher is at version 0.2.2

**Comment by nielsk** [comment]
Tried it now with installing txsocksx via pip and cloned this repo and still get the same error.

**Comment by h01ger** [comment]
This looks like you are missing certificates. On Debian I could solve a similar situation by installing the ca-certificates packages.

Also you might want to try 0.2.3 which was released yesterday :)

**Comment by nielsk** [comment]
@h01ger thanks. 0.2.3 works :)
