### ISSUE TITLE
Include png icon

### ISSUE THREAD

**Issue by xSmurf** [micahflee/torbrowser-launcher#226]
Hello, TBBL currently only includes an `xpm` icon. While that works in most cases, this currently causes problems in some edge cases, for example the icon is not retrievable by name using GIO/Gtk libraries, and also with some remote X solutions.

Would it be possible include standard icons in png with the package?

A main blocker for this is finding the original vector art for the icon.

Gracias

**Comment by micahflee** [comment]
Certainly!

**Comment by xSmurf** [comment]
Thanks a bunch Micah! Beer's on me :D
