### ISSUE TITLE
Torbrowser won't launch without serious apparmor compromises...

### ISSUE THREAD

**Issue by benbailess** [micahflee/torbrowser-launcher#230]
I've been trying to debug the root issue for about an hour or so now, and I've determined that it's somehow related to the apparmor policies... 

here's the behavior, denials and errors:

behavior: 
If I reinstall Tor browser using torbrowser-launcher, it launches fine. If I close it and re-launch from the .desktop icon in Gnome (just executes ./start-tor-browser --detach), then I get a failure of tor to start with the following error: 

Window title: Tor Launcher

Tor unexpectedly exited. This might be due to a bug in Tor itself, another program on your system, or faulty hardware. Until you restart Tor, the Tor Browser will not able to reach any websites. If the problem persists, please send a copy of your Tor Log to the support team.

Restarting Tor will not close your browser tabs.
Options: OK | Restart Tor

... Neither option does anything to get past this issue. If I go back to torbrowser-launcher and redownload TBB, it launches again just fine, but not if I try to launch directly from the .desktop icon. 

With the tbb and Tor apparmor profiles enforced, I get the following denial from audit.log:

```
type=AVC msg=audit(1459960578.870:113591): apparmor="DENIED" operation="open" profile="/home/*/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/firefox" name="/run/NetworkManager/resolv.conf" pid=2740 comm="firefox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

type=AVC msg=audit(1459960578.874:113592): apparmor="DENIED" operation="open" profile="/home/*/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/firefox" name="/run/NetworkManager/resolv.conf" pid=2740 comm="firefox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

type=AVC msg=audit(1459960579.286:113593): apparmor="DENIED" operation="open" profile="/home/*/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/firefox" name="/etc/pulse/client.conf" pid=2740 comm="firefox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

type=AVC msg=audit(1459960579.286:113595): apparmor="DENIED" operation="mknod" profile="/home/*/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/firefox" name="/dev/shm/pulse-shm-1614250275" pid=2740 comm="firefox" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000

type=AVC msg=audit(1459960579.286:113596): apparmor="DENIED" operation="open" profile="/home/*/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/firefox" name="/dev/shm/" pid=2740 comm="firefox" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

I understand not all of those denials are problematic and are indeed intended...

I also get the following error in the terminal when I run ./start-tor-browser --debug manually:

```
/home/{my_user_is_here}/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Tor/tor: symbol lookup error: /home/{my_user_is_here}/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Tor/tor: undefined symbol: evutil_secure_rng_set_urandom_device_file
shm_open() failed: Permission denied
```

When I set both profiles to complain, I still get the following error in terminal with --debug:

```
/home/{my_user_is_here}/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Tor/tor: symbol lookup error: /home/{my_user_is_here}/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Tor/tor: undefined symbol: evutil_secure_rng_set_urandom_device_file
```

When I *disable* the torbrowser.Browser.firefox profile (using aa-disable), and leave the torbrowser.Tor.tor profile set to complain, everything works as intended. If I then set the torbrowser.Tor.tor profile to enforce again and leave the "firefox" profile disabled, I get the following error in terminal with --debug (same as before):

```
/home/{my_user_is_here}/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Tor/tor: symbol lookup error: /home/{my_user_is_here}/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Tor/tor: undefined symbol: evutil_secure_rng_set_urandom_device_file
```

Any guidance on how to resolve would be very much appreciated... and hopefully this information is helpful to others and to troubleshoot the root cause.

Thanks,

Ben

**Comment by h01ger** [comment]
hi Ben, how did you install torbrowser-launcher? which distro are you using?

**Comment by benbailess** [comment]
Hey @h01ger, thanks for the reply. I installed via apt and debian sid. I purged for the time being and managed manually, and I just installed again via apt on debian sid, and am still running into issues. I'll take some time today to see if the error messages are the same or different and run a aa-logprof to see if the denials can be sensibly resolved.

Let me know if you'd like me to test anything else in the meantime. I'll try to post an update either today or tomorrow.

Thanks

Ben

**Comment by ajhaydock** [comment]
I am getting this issue also on AppArmor-enabled Debian, and it happens on both Debian Stable and Testing/Sid (though manifests differently).

On stable, I am unable to disable the AA rule, with both `aa-disable` and `aa-complain` complaining that it doesn't exist.

On testing/sid I am able to use `aa-disable` as follows to get the browser to launch:
```bash
sudo aa-disable "/home/*/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/{Browser/TorBrowser/,}Tor/tor"
sudo aa-disable "/home/*/.local/share/torbrowser/tbb/{i686,x86_64}/tor-browser_*/Browser/firefox"
```

In both cases though the browser can be launched (seemingly with the AA rule working) if it is launched from the "Tor Browser Launcher Settings" app and not the "Tor Browser" desktop shortcut.

This workaround is much more convenient on stable though, as the packaged version of `torbrowser-launcher` has a "Launch Tor Browser" button inside the Settings app.

This button seems to have been removed in the newer version of `torbrowser-launcher` that gets packaged for testing/sid, meaning that (as @benbailess noted) a user who wants to launch TBB on testing/sid without disabling the AA rule needs to use the "Reinstall Tor Browser" button to launch every time, which isn't ideal.

Any ideas? I'm pretty new to debugging AppArmor so I can't see what might be wrong here.
