### ISSUE TITLE
Unable to launch when update is available

### ISSUE THREAD

**Issue by lucianposton** [micahflee/torbrowser-launcher#232]
https://github.com/micahflee/torbrowser-launcher/commit/a8d1e803798251e051dcf41d9c8a1b2e00710a0c added a version check to prevent torbrowser from launching if its version is too low. However, the mechanism to update the torbrowser (afaik) is to launch the old browser and via the GUI initiate the update. See image below.

With the version check introduced by https://github.com/micahflee/torbrowser-launcher/commit/a8d1e803798251e051dcf41d9c8a1b2e00710a0c, the user is not able to update the browser via normal means.

![beforer](https://cloud.githubusercontent.com/assets/646121/14684786/750bd4a8-06e6-11e6-92db-562fda0ad8b9.png)

**Comment by micahflee** [comment]
Eek, that's not good.
