### ISSUE TITLE
Apparmor profiles from torbrowser-launcher 0.2.6-2 on debian jessie is broken.

### ISSUE THREAD

**Issue by protoman1** [micahflee/torbrowser-launcher#246]
Hello.

I use Debian Jessie 8.6 with installed torbrowser-launcher 0.2.6-2 from jessie-backports repository. Rules from apparmor files **torbrowser.Browser.firefox** and **torbrowser.Tor.tor** break Tor Browser 6.0.5 start.

**Comment by u451f** [comment]
Hi, we are aware of this. There is a pull request which fixes this issue: https://github.com/micahflee/torbrowser-launcher/pull/243 You might also edit the apparmor profiles yourself in the meantime,
