### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by u451f** [micahflee/torbrowser-launcher#248]
Hi Micah,

when I try to download a fresh torbrowser using torbrowser-launcher, I get an signature verification error. 

When verifying manually, gpg reports a correct signature though:

```
gpg --verify tor-browser-linux64-6.0.5_de.tar.xz.asc tor-browser-linux64-6.0.5_de.tar.xz
gpg: Unterschrift vom Fr 16 Sep 2016 13:51:55 CEST
gpg:                mittels RSA-Schlüssel 0x2E1AC68ED40814E0
gpg: Korrekte Unterschrift von "Tor Browser Developers (signing key) <torbrowser@torproject.org>" [unbestimmt]
gpg: WARNUNG: Dieser Schlüssel trägt keine vertrauenswürdige Signatur!
gpg:          Es gibt keinen Hinweis, daß die Signatur wirklich dem vorgeblichen Besitzer gehört.
Haupt-Fingerabdruck  = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
Unter-Fingerabdruck  = BA1E E421 BBB4 5263 180E  1FC7 2E1A C68E D408 14E0
```

**Comment by u451f** [comment]
Wow, it looks like this might have been due to a faulty exit node. Scary. I don't know which one it was though.

**Comment by micahflee** [comment]
Wow! That's crazy. Hmm I wonder if there's any way to find out. I don't think and tor logs would say which exit you were using, but have you checked?

If it was a faulty exit node and not a TBL bug, how come your manual signature verification succeeded?

**Comment by u451f** [comment]
I actually did not verify the files downloaded over Tor with TBL but those downloaded over clearnet manually..  So that worked and thus I suppose it was only those which I downloaded over Tor which were faulty. I retried it several times and they were always faulty. 

Didn't check the logs yet, no.
