### ISSUE TITLE
Tor unexpectedly exited

### ISSUE THREAD

**Issue by MatthieuStigler** [micahflee/torbrowser-launcher#252]
Hi

I just installed torbrowser-launcher on Ubuntu 16.04 through standard repository, and when running  
torbrowser-launcher got error message: 

> Tor unexpectedly exited. This might be due to a bug in Tor itself, another program on your system, or faulty hardware. Until you restart Tor, the Tor Browser will not able to reach any websites. If the problem persists, please send a copy of your Tor Log to the support team.

 This problem was also reported on Tor Beta: http://tor.stackexchange.com/questions/4857/errors-when-starting-tor-browser-on-linux 
but is only self-answered, although the answer seems to have worked in my case. Is there any more official answer on that case? Is that the right solution? Thanks!

**Comment by KMax** [comment]
I faced the same problem. Here is the output of `start-tor-browser --verbose`:

```
Unable to update the static FcBlanks: 0x0600
Unable to update the static FcBlanks: 0x0601
Unable to update the static FcBlanks: 0x0602
Unable to update the static FcBlanks: 0x0603
Unable to update the static FcBlanks: 0x06dd
Unable to update the static FcBlanks: 0x070f
Unable to update the static FcBlanks: 0x2028
Unable to update the static FcBlanks: 0x2029
Unable to update the static FcBlanks: 0xfff9
Unable to update the static FcBlanks: 0xfffa
Unable to update the static FcBlanks: 0xfffb
Feb 05 20:15:06.870 [notice] Tor 0.2.9.9 (git-56788a2489127072) running on Linux with Libevent 2.0.22-stable, OpenSSL 1.0.2j and Zlib 1.2.8.
Feb 05 20:15:06.870 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 05 20:15:06.870 [notice] Read configuration file "/home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Tor/torrc-defaults".
Feb 05 20:15:06.870 [notice] Read configuration file "/home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Tor/torrc".
Feb 05 20:15:06.874 [notice] Opening Control listener on 127.0.0.1:9151
Feb 05 20:15:06.874 [warn] Could not bind to 127.0.0.1:9151: Address already in use. Is Tor already running?
Feb 05 20:15:06.874 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
Feb 05 20:15:06.874 [err] Reading config failed--see warnings above.
```

**Comment by micahflee** [comment]
I think this is an issue with Tor Browser itself, not Tor Browser Launcher. In the end, Tor Browser Launcher just run `~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop`.
