### ISSUE TITLE
./build_rpm.sh outputs a .tar.gz instead of .rpm

### ISSUE THREAD

**Issue by patrickod** [micahflee/torbrowser-launcher#257]
Discovered this while reading through [this article](https://micahflee.com/2014/05/using-tor-browser-launcher-in-qubes/) on using the torbrowser-launcher in qubes. The `./build_rpm.sh` file references an `.rpm` file in its console output, but the extension for the build output is a `.tar.gz` Minor issue as you can still install it, but copy / pasting the script output will not work.

**Comment by davidbaumann** [comment]
Actually the current version I tested on Fedora 37 did create the file.
Also I could copy paste the supplied command.
