### ISSUE TITLE
Add option to download experimental version, hardened version or sandboxed version 

### ISSUE THREAD

**Issue by GitHubPleaseDontBlockTor** [micahflee/torbrowser-launcher#258]

**Comment by ge-fa** [comment]
See #207 as well.

**Comment by jyn514** [comment]
@GitHubPleaseDontBlockTor Is there a binary available for sandboxed-tor-browser? I looked at the [docs page](https://trac.torproject.org/projects/tor/wiki/doc/TorBrowser/Sandbox/Linux) and there's only a link to source, no executables. I doubt anyone wants the launcher to compile executables from source.

**Comment by davidbaumann** [comment]
Duplicate of #207
