### ISSUE TITLE
New Tor Browser signing subkey 

### ISSUE THREAD

**Issue by epidemics-scepticism** [micahflee/torbrowser-launcher#260]
D1483FA6C3C07136 is the new signing subkey for the 6.5 Tor Browser release, this subkey isn't in the hardcoded keys distributed with `torbrowser-launcher`.

**Comment by zkutch** [comment]
I posted this question to #tor and https://tor.stackexchange.com/questions/13814/upgrading-to-6-5 against not upgrading on debian wheezy.
Is there some way other to waiting debian maintaineer , for example suspend/not upgrade to 6.5? Such problems will be in future also.

**Comment by zkutch** [comment]
Solution for debian wheezy found following:
update/refresh keys from mit using command
gpg --keyserver pgp.mit.edu --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys
after this torbrowser-launcher upgrades itself successfully

**Comment by epidemics-scepticism** [comment]
Temporary workaround: `gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu`

**Comment by micahflee** [comment]
Awesome, thanks @epidemics-scepticism @zkutch for troubleshooting

**Comment by ge-fa** [comment]
See #263 as well.
