### ISSUE TITLE
Add package to deb.torproject.org

### ISSUE THREAD

**Issue by lofidevops** [micahflee/torbrowser-launcher#269]
I ran into #260 after setting up deb.torproject.org, and discovered my version of torbrowser-launcher was out-of-date (0.2.6-1 on Ubuntu 16.10). Would it be possible to add torbrowser-launcher to the `deb.torproject.org` so that there is a single, trusted source for everything TBB related?

(This was mentioned in #29 and #31 , so was this previously planned and cancelled?)

**Workaround for Ubuntu:** (thanks @theel0ja) use the micahflee PPA - see [instructions in README](https://github.com/micahflee/torbrowser-launcher#installing-in-ubuntu)

**Related Tor ticket:** https://trac.torproject.org/projects/tor/ticket/22965

**Comment by theel0ja** [comment]
Same on Ubuntu 16.04, outdated version that didn't work.

**Comment by ajhaydock** [comment]
@theel0ja In case you missed it, the fix in #263 works for the package in Ubuntu 16.04, though I find that `keyserver.ubuntu.com` is usually a bit more reliable than `pgp.mit.edu` if you're still having problems.

I'd definitely support the idea of integrating into the TorProject deb repo though. Especially since `torbrowser-launcher` is the only reason I need to keep `contrib` enabled on my Debian systems, and this would let me avoid that.

**Comment by theel0ja** [comment]
Just updated to latest version from PPA, works properly.

**Comment by u451f** [comment]
FWIW: There is no build of TorBrowser made by the TorProject, hence it is not available as a package on deb.torproject.org.
torbrowser-launcher is an independent wrapper for downloading the TorBrowser sources.
The package available in Debian and Ubuntu is made by Debian people, not Tor people.
Complicated entanglements! :)

**Comment by kwill** [comment]
I assumed that torbrowser-launcher downloaded the build available at https://www.torproject.org/download/download-easy.html.en -- i.e. bypassing reliance on any distro's (potentially out-of-date) build?

So currently I need to:
1. Add deb.torproject.org as a source to get the latest Tor router
2. Add ppa:micahflee/ppa as a source to get the latest torbrowser-launcher
3. Use torbrowser-launcher to get the latest TBB
4. Rely on sources and torbrowser-launcher for further updates

My suggestion (if feasible) is to include torbrowser-launcher in deb.torproject.org and thereby skip step 2. (Step 2 is also tricky on non-Ubuntu Debian-based distros.)

**Comment by jyn514** [comment]
@kwill As far as I know, micah isn't a direct contributor to torproject, so he has no control over what's hosted on their site.

**Comment by kwill** [comment]
Created https://trac.torproject.org/projects/tor/ticket/22965 and cross-linked the tickets.
