### ISSUE TITLE
It is not possible to launch 2 torbrowsers on the same host from 2 different users

### ISSUE THREAD

**Issue by u451f** [micahflee/torbrowser-launcher#273]
Dear Micah,

we've received a  bug report on the Debian bugtracker containing a patch (which you might want to review, adapt or comment on) here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860297

Direct link to the patch: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=860297;filename=torbrowser.start-tor-browser.patch;msg=20

I think it would indeed be nice to be able to launch a second TorBrowser under a different user - this could be a way to isolate it a bit more. The user who reported the bug seems to refer to a normal usage though, really to launch two instances from two user accounts.

Cheers!

**Comment by rogers0** [comment]
I think the patch cannot be merged in this project, but the upstream tor project.
So I created the ticket: https://trac.torproject.org/projects/tor/ticket/33882

I guess this ticket on github can be closed.
