### ISSUE TITLE
SIGNATURE VERIFICATION ERROR

### ISSUE THREAD

**Issue by COLABORATI** [micahflee/torbrowser-launcher#275]
Installed from Ubuntu 16.04 repo and using it for the first time gives me a VERY BIG WARNING:

SIGNATURE VERIFICATION ERROR

From my understanding this is the worst error that could happen, I see no fix to that.

**Comment by dephekt** [comment]
This is related to #260. Here is a fix for you:

`gpg --keyserver pgp.mit.edu --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys`

This will refresh your torbrowser-launcher GPG keyring and download the missing signing subkey(s).
