### ISSUE TITLE
AppArmor: sandbox the content rendering processes (e10s) more strictly

### ISSUE THREAD

**Issue by intrigeri** [micahflee/torbrowser-launcher#278]
Once we have https://github.com/micahflee/torbrowser-launcher/pull/277, we confine these processes in exactly the same way as the parent Firefox process. They can be confined much more strictly, without impacting UX whatsoever. And while we're at it, maybe some permissions we currently grant to the parent Firefox process are not needed anymore, as it does less work.

Preliminary work lives in https://github.com/intrigeri/torbrowser-launcher/tree/apparmor-e10s. I'm using on my own system, I'll run it through the Tails automated test suite, and once I'm happy I'll submit a merge request. Testing & all kinds of help are welcome :)

**Comment by micahflee** [comment]
Thank you! This is great. I'll review and merge #277 now.

**Comment by intrigeri** [comment]
https://github.com/micahflee/torbrowser-launcher/pull/280

**Comment by ageis** [comment]
The associated PRs are both merged. Closing.
