### ISSUE TITLE
Don't install stop in verify...

### ISSUE THREAD

**Issue by lucascouts** [micahflee/torbrowser-launcher#281]
hi, I use Funtoo and and the torbrowser overlay, few months ago the launcher work, but stop start, I install the package version 2.8, when I start, download the bundle, but frozen in Verifying signature and don't intall. 

I already change the python default synlink to 2.7 and nothing yet. 

someone can help me.

**Comment by miragu** [comment]
Same for me in stable Gentoo, with only a few required packages from testing. To bypass the verification I commented it in /usr/lib64/python2.7/site-packages/torbrowser_launcher/launcher.py line 119. This is obviously NOT a solution! Just a workaround FOR ME, since I'm not in any danger.
