### ISSUE TITLE
The Signature verification fails every time

### ISSUE THREAD

**Issue by elypter** [micahflee/torbrowser-launcher#282]
no matter what mirror or over tor or not i cant download a new tbb. linux mint mate 18.1 32bit 4.8 kernel

**Comment by dephekt** [comment]
If you're seeing signature verification failures, it's likely related to #260 and can be resolved by running the following command to refresh the GPG keyring the launcher uses:

    gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu

You should see a message indicating new subkeys were added. Then you should be able to run the installation again from the Launcher Settings dialog.

Alternatively, you can clone v0.2.8 from this repository, which has fixes built-in:

1. `git clone https://github.com/micahflee/torbrowser-launcher` 
2. `cd torbrowser-launcher`
3. `git checkout v0.2.8`
4. `./torbrowser-launcher`

Running the 0.2.8 client should automatically update your Tor Browser GPG keyring.

**Comment by elypter** [comment]
thanks, i got it working by using apt purge

**Comment by baimafeima** [comment]
@micahflee This is also an issue for me. Installing Tor Browser Bundle via torbrowser-launcher is currently broken.

**Comment by dephekt** [comment]
@baimafeima can you tell me what version of the launcher you're using? I can walk you through dealing with this if you can give me some details. I made the fixes in newer versions that solve this issue before you see it. Let me know what version you're using and what Linux distribution and release you're using and I'll give you more details.

**Comment by freezed** [comment]
Here my log, on LMDE2:
`Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.1.9+deb8u3
https://github.com/micahflee/torbrowser-launcher
Initializing Tor Browser Launcher
Importing keys
gpg: clef 63FEE659 : « Erinn Clark <erinn@torproject.org> » n'est pas modifiée
gpg:       Quantité totale traitée : 1
gpg:                 non modifiées : 1
gpg: clef 93298290 : « Tor Browser Developers (signing key) <torbrowser@torproject.org> » n'est pas modifiée
gpg:       Quantité totale traitée : 1
gpg:                 non modifiées : 1
Starting launcher dialog
LATEST VERSION 7.0.4
Checking for update
Running task: download_update_check
Downloading https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US
Download error: Download Error: 404 Not Found <class 'torbrowser_launcher.launcher.DownloadErrorException'>
`

**Comment by dephekt** [comment]
@freezed Your issue is unrelated to this issue. The download URL your client is using `https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US` is returning a 404 error and doesn't appear to be a valid URL.

**Comment by freezed** [comment]
Thanks its rocks!

For the first log, that's a Debian issue? It's quite recent, I don't find the same error somewhere else.

**Comment by dephekt** [comment]
I'm not sure without looking and testing. I would just randomly assume that the 0.1.9 version in Debian Jessie is using (or generating) outdated URLs for its downloads and that it would need to be resolved through their bug tracker in their branch for Jessie. Having said that, I don't actually know, and I could be entirely wrong but I'll try to look into it with a Jessie virtual machine when I have a chance and see if I can reproduce the issue.

**Comment by davidhedlund** [comment]
Your [instructions](https://github.com/micahflee/torbrowser-launcher/issues/282#issuecomment-315555536) doesn't work (can you make update them?):

> $ git clone https://github.com/micahflee/torbrowser-launcher
> Cloning into 'torbrowser-launcher'...
> remote: Counting objects: 2920, done.
> remote: Total 2920 (delta 0), reused 0 (delta 0), pack-reused 2920
> Receiving objects: 100% (2920/2920), 1.51 MiB | 1.47 MiB/s, done.
> Resolving deltas: 100% (1758/1758), done.
> Checking connectivity... done.
> $ cd torbrowser-launcher
> $ git checkout v0.2.8
> Note: checking out 'v0.2.8'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at a20103c... Version bump to 0.2.8, and updated changelog
> $ ./torbrowser-launcher
> Traceback (most recent call last):
>   File "./torbrowser-launcher", line 30, in <module>
>     torbrowser_launcher.main()
>   File "/home/foo/torbrowser-launcher/torbrowser_launcher/__init__.py", line 46, in main
>     with open(os.path.join(SHARE, 'version')) as buf:
> IOError: [Errno 2] No such file or directory: '/usr/share/torbrowser-launcher/version'
>

**Comment by davidhedlund** [comment]
@dephekt Your [instructions](https://github.com/micahflee/torbrowser-launcher/issues/282#issuecomment-315555536) doesn't work (can you make update them?):

> $ git clone https://github.com/micahflee/torbrowser-launcher
> Cloning into 'torbrowser-launcher'...
> remote: Counting objects: 2920, done.
> remote: Total 2920 (delta 0), reused 0 (delta 0), pack-reused 2920
> Receiving objects: 100% (2920/2920), 1.51 MiB | 1.47 MiB/s, done.
> Resolving deltas: 100% (1758/1758), done.
> Checking connectivity... done.
> $ cd torbrowser-launcher
> $ git checkout v0.2.8
> Note: checking out 'v0.2.8'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> HEAD is now at a20103c... Version bump to 0.2.8, and updated changelog
> $ ./torbrowser-launcher
> Traceback (most recent call last):
>   File "./torbrowser-launcher", line 30, in <module>
>     torbrowser_launcher.main()
>   File "/home/foo/torbrowser-launcher/torbrowser_launcher/__init__.py", line 46, in main
>     with open(os.path.join(SHARE, 'version')) as buf:
> IOError: [Errno 2] No such file or directory: '/usr/share/torbrowser-launcher/version'

**Comment by micahflee** [comment]
This issue has been resolved in the latest version of torbrowser-launcher, 0.2.9. Make sure you're running the latest version. You can build from source by following these directions of your distro doesn't include it in its repositories: https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md
