### ISSUE TITLE
fedora 26 + xguest

### ISSUE THREAD

**Issue by unclesam87** [micahflee/torbrowser-launcher#283]
Hello,

i am using Fedora 26 cinnamon spin -
on new Accounts torbrowser-launcher works fine, it downloads the brand new version and starts.

But when i try to use it on xguest, it download it and crashes at startup. I would like to post an log, but when i click copy tor protocol, it is empty. 
it also says tor was crashed unexpectedly. 

Any ideas how i can fix that? xguest is the account most people use around here for saftey reason (dont save anything, just writing in ram)

**Comment by dephekt** [comment]
xguest works with SELinux rules to prevent things like executing things in a users home directory or within a /tmp directory. Tor Browser reads and writes from several different areas and this is probably where things go bad.

Red Hat documentation says "by default, Linux users in the guest_t and xguest_t domains cannot execute applications in their home directories or /tmp/; however, by default, Linux users in the user_t and staff_t domains can."

To allow Linux users in the guest_t & xguest_t domains to execute applications in their home directories and /tmp/: 
```
~]# setsebool -P allow_xguest_exec_content on
~]# setsebool -P allow_guest_exec_content on
```

Then try running torbrowser-launcher just to see what happens. If you get crashes, check for SELinux failures with setroubleshoot. I have a feeling this will come down to having the right SELinux contexts on various things to make it work.

There may need to be under-the-hood changes that need made to support running in Kiosk mode or as other xguest users. I don't have a lot of experience with xguest so feel free to correct me anywhere here if I've gotten something wrong.
