### ISSUE TITLE
torbrowser-launcher going to wrong directory to launch torbrowser when "Force downloading English version of Tor Browser" is checked

### ISSUE THREAD

**Issue by juadde** [micahflee/torbrowser-launcher#284]
Hello,

I have a problem with the 0.2.7-3 version under debian.
The screen "Installing" can't get passed because the script is looking into tor-browser_LANG (for me fr) instead of tor-browser_en-US.

If I uncheck "Force downloading English version of Tor Browser" torbrowser launches as expected (in fr).

Hoping you will be able to make the "Force downloading English version of Tor Browser" working again for foreigners...

**Comment by dephekt** [comment]
This should be pretty straight-forward to fix. I'll try to get a PR ready and test against a non-en-US locale in Debian.
