### ISSUE TITLE
Latest version in PPA is outdated on every Ubuntu version except trusty

### ISSUE THREAD

**Issue by pizzadude** [micahflee/torbrowser-launcher#285]
Hi,

The latest version (2.8) of torbrowser-launcher in the ppa:micahflee/ppa is only updated on trusty.

All the other releases, xenial, zesty, etc are still on 2.7.

Any plans to update it?

Thanks!

**Comment by micahflee** [comment]
Sorry about that! I'll fix it now

**Comment by micahflee** [comment]
Should be fixed
