### ISSUE TITLE
doesn't work in http proxy environment

### ISSUE THREAD

**Issue by rogers0** [micahflee/torbrowser-launcher#288]
If the PC can only access internet via http proxy, the tb launcher cannot get the proxy from environment variables such as "http_proxy" and "https_proxy".
I confirm wget can work well in such case.

**Comment by davidbaumann** [comment]
Checked on 0.3.6:
- Install torbrowser-launcher from flatpak
- put behind other device with tinyproxy
- export http_proxy and https_proxy
- flatpak run com.github.micahflee.torbrowser-launcher

Actually it did download and start tbb.
