### ISSUE TITLE
AttributeError: 'module' object has no attribute 'events_pending'

### ISSUE THREAD

**Issue by shekfeh** [micahflee/torbrowser-launcher#296]
Hello everyone,

Since few weeks I am experiencing problem in launching torbrowser, in spite that it was working fine before few weeks. I am on Debian 9 stretch:

#torbrowser-launcher 

Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 29, in <module>
    import torbrowser_launcher
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 31, in <module>
    from common import Common, SHARE
  File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 54, in <module>
    gtk2reactor.install()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/gtk2reactor.py", line 99, in install
    reactor = Gtk2Reactor(useGtk)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/gtk2reactor.py", line 73, in __init__
    _glibbase.GlibReactorBase.__init__(self, gobject, _gtk, useGtk=useGtk)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_glibbase.py", line 119, in __init__
    self._pending = self._gtk.events_pending
AttributeError: 'module' object has no attribute 'events_pending'

Any idea .. I don't remember I changed any python package that could affect tor
thanks in advance

**Comment by dephekt** [comment]
Can you tell us what versions you are running for the following python modules?
- twisted
- pygtk

The traceback indicates you get as far as gtk2reactor.install() in common.py at which point there is a hand-off from torbrowser-launcher to the Python twisted.internet module and its Gtk2Reactor. So, my first guess is twisted.internet or pygtk updated at some point which triggered this problem, so I want to narrow down the versions before and after to find out what changed and how it's affecting things here.

I'm most familiar with Fedora and Red Hat but I'm happy to throw up a Debian 9 vm and try to isolate the issue.

**Comment by shekfeh** [comment]
I checked if I have updated any of these packages, but it seems not.
So pyGTK is installed by debian (2.24), actually pip refuse to install or update pygtk.
Twisted is 16.6.0, exactly as in stretch repositories.

**Comment by dephekt** [comment]
Thanks. I'll try to replicate the issue tonight on a Debian Stretch vm and get back to you when I can.

**Comment by dephekt** [comment]
Oh yeah, what version of torbrowser-launcher do you have installed? Same as Debian Stretch or are you cloning from git?

**Comment by shekfeh** [comment]
I am very very sorry. It appeared it is my mistake!! totally user problem.
Few weeks ago I installed vtk on python3 only, and I had to pass the location to pythonpath:

export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.5/dist-packages/vtk

apparently vtk conflicted with pygtk in python2 !! and caused the problem !
I am very sorry if I have wasted your time yesterday. Many thanks for the help.
