### ISSUE TITLE
Native Messaging Hosts

### ISSUE THREAD

**Issue by hThoreau** [micahflee/torbrowser-launcher#301]
Hello there. I'm interested on installing the following Web Extensions on my Tor Browser: [Browserpass](https://github.com/dannyvankooten/browserpass) and [Bukubrow](https://github.com/SamHH/bukubrow).
Both of these applications instruct that, for a firefox installation, it is necessary to create a `$HOME/.mozilla/native-messaging-hosts` folder to place their respective .json files inside describing the path to their applications in order for the browser to communicate with them. I don't know what is the equivalent folder to ${HOME}.mozilla for torbrowser-launcher, or if I should create a .mozilla folder somewhere under the torbrowser file structure. Or even, if the app-armor profile might block such a communication. Anyhow, I already tried placing the native-messaging-hosts folder in these locations without results:
```
~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/browser
~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser
~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser/profiles.default
~/.config/torbrowser
~/.mozilla/
```

**Comment by marsu08** [comment]
Hello,
for me, this location has worked :
~/.local/share/torbrowser/tbb/x86_64/tor-browser_fr/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts

**Comment by hThoreau** [comment]
Thanks for the tip Marsu, I'll try this as soon as I can get the Tor Browser reinstalled.
