### ISSUE TITLE
torbrowser-launcher fails to launch torbrowser after update to 7.5

### ISSUE THREAD

**Issue by ContactLeft** [micahflee/torbrowser-launcher#313]
Distro is Parrot 3.11 (Debian) amd64 

[torbrowser-error.txt](https://github.com/micahflee/torbrowser-launcher/files/1679193/torbrowser-error.txt)

quick workaround / quick fix is to:

launch start-tor-browser in the /.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser directory.
or
start-tor-browser.desktop in ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/

**Comment by duritong** [comment]
Same thing happens on Fedora 27, though the above work around do not seem to work.

**Comment by charlydelta** [comment]
Can confirm this on Debian stretch - The suggested workaround does **not** work for me

@duritong Did you do anything specific to make it work?

**Comment by charlydelta** [comment]
Doesn't work in Ubuntu 16.04 LTS either (tested in a VM)

**Comment by rickhg12hs** [comment]
Same problem on Fedora 26.

Workaround is:

```bash
$ cd ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser
$ ./start-tor-browser

```

**Comment by sogalboogalsky** [comment]
Same problem on openSUSE Leap 42.3.
Workaround does work.

**Comment by pkreuzt** [comment]
Same problem here, fix does work. In my case I think it's related to https://github.com/micahflee/torbrowser-launcher/issues/284

The launcher looks for localized version of the path, even when I forced en_US version installation.

**Comment by israelfaria** [comment]
Hit this issue. If you'r running on ubuntu derivatives you may update to 0.2.9 trough this repo author ppa. After upgrade everything works fine.

**Comment by micahflee** [comment]
This was fixed in #307

**Comment by Tyrben** [comment]
By me, this directory is empty after fresh installation of tor browser. The workaround cant work
`~/.local/share/torbrowser/tbb/x86_64/`

**Comment by ContactLeft** [comment]
> Same problem on Fedora 26.
> 
> Workaround is:
> 
> ```shell
> $ cd ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser
> $ ./start-tor-browser
> ```

isnt that what i put down?

**Comment by rickhg12hs** [comment]
@ContactLeft  Yep, just wanted to show it affected Fedora too and give clear commands to run.
