### ISSUE TITLE
Launcher expects Tor Browser installation to create .../Docs/sources/versions

### ISSUE THREAD

**Issue by pmocek** [micahflee/torbrowser-launcher#318]
After verifying that old torbrowser-launcher configuration cruft did not exist:

    $ find $HOME/.local/share/torbrowser
    /home/pmocek/.local/share/torbrowser
    /home/pmocek/.local/share/torbrowser/gnupg_homedir
    /home/pmocek/.local/share/torbrowser/gnupg_homedir/trustdb.gpg
    /home/pmocek/.local/share/torbrowser/gnupg_homedir/pubring.gpg
    /home/pmocek/.local/share/torbrowser/gnupg_homedir/pubring.gpg~
    /home/pmocek/.local/share/torbrowser/gnupg_homedir/secring.gpg

And refreshing package management cache:

    $ sudo aptitude update
    Hit http://prerelease.keybase.io/deb stable InRelease
    Hit http://mirrors.cat.pdx.edu/ubuntu xenial InRelease
    Hit http://mirrors.cat.pdx.edu/ubuntu xenial-updates InRelease
    Hit http://APT.spideroak.com/ubuntu-spideroak-hardy release InRelease
    Hit http://mirrors.cat.pdx.edu/ubuntu xenial-backports InRelease
    Hit http://mirrors.cat.pdx.edu/ubuntu xenial-security InRelease
    Hit https://updates.signal.org/desktop/apt xenial InRelease
    Hit http://screenshots.getdeb.net xenial-getdeb InRelease

I installed pacakge torbrowser-launcher, accepting depsolver recommendations:

    $ sudo aptitude install torbrowser-launcher
    The following NEW packages will be installed:

      python-attr{a} python-lzma{a} python-pam{a} python-parsley{a}
      python-psutil{a} python-pyasn1-modules{a} python-serial{a}
      python-service-identity{a} python-twisted{a} python-twisted-bin{a}
      python-twisted-core{a} python-txsocksx{a} python-zope.interface{a} tor{a}
      tor-geoipdb{a} torbrowser-launcher torsocks{a} wmctrl{a}

    0 packages upgraded, 18 newly installed, 0 to remove and 49 not upgraded.
    Need to get 0 B/4,466 kB of archives. After unpacking 25.4 MB will be used.
    Do you want to continue? [Y/n/?] Y
    Selecting previously unselected package python-attr.
    (Reading database ... 513908 files and directories currently installed.)
    Preparing to unpack .../python-attr_15.2.0-1_all.deb ...
    Unpacking python-attr (15.2.0-1) ...
    Selecting previously unselected package python-lzma.
    Preparing to unpack .../python-lzma_0.5.3-3_amd64.deb ...
    Unpacking python-lzma (0.5.3-3) ...
    Selecting previously unselected package python-pam.
    Preparing to unpack .../python-pam_0.4.2-13.2ubuntu2_amd64.deb ...
    Unpacking python-pam (0.4.2-13.2ubuntu2) ...
    Selecting previously unselected package python-psutil.
    Preparing to unpack .../python-psutil_3.4.2-1_amd64.deb ...
    Unpacking python-psutil (3.4.2-1) ...
    Selecting previously unselected package python-pyasn1-modules.
    Preparing to unpack .../python-pyasn1-modules_0.0.7-0.1_all.deb ...
    Unpacking python-pyasn1-modules (0.0.7-0.1) ...
    Selecting previously unselected package python-serial.
    Preparing to unpack .../python-serial_3.0.1-1_all.deb ...
    Unpacking python-serial (3.0.1-1) ...
    Selecting previously unselected package python-service-identity.
    Preparing to unpack .../python-service-identity_16.0.0-2_all.deb ...
    Unpacking python-service-identity (16.0.0-2) ...
    Selecting previously unselected package python-twisted-bin.
    Preparing to unpack .../python-twisted-bin_16.0.0-1_amd64.deb ...
    Unpacking python-twisted-bin (16.0.0-1) ...
    Selecting previously unselected package python-zope.interface.
    Preparing to unpack .../python-zope.interface_4.1.3-1build1_amd64.deb ...
    Unpacking python-zope.interface (4.1.3-1build1) ...
    Preparing to unpack .../python-twisted-core_16.0.0-1_all.deb ...
    Unpacking python-twisted-core (16.0.0-1) ...
    Preparing to unpack .../tor_0.2.9.11-1ubuntu1~16.04.1_amd64.deb ...
    Unpacking tor (0.2.9.11-1ubuntu1~16.04.1) ...
    Preparing to unpack .../python-twisted_16.0.0-1_all.deb ...
    Unpacking python-twisted (16.0.0-1) ...
    Selecting previously unselected package wmctrl.
    Preparing to unpack .../wmctrl_1.07-7_amd64.deb ...
    Unpacking wmctrl (1.07-7) ...
    Selecting previously unselected package python-parsley.
    Preparing to unpack .../python-parsley_1.2-1_all.deb ...
    Unpacking python-parsley (1.2-1) ...
    Selecting previously unselected package python-txsocksx.
    Preparing to unpack .../python-txsocksx_1.15.0.2-1_all.deb ...
    Unpacking python-txsocksx (1.15.0.2-1) ...
    Selecting previously unselected package torbrowser-launcher.
    Preparing to unpack .../torbrowser-launcher_0.2.4-1_amd64.deb ...
    Unpacking torbrowser-launcher (0.2.4-1) ...
    Preparing to unpack .../torsocks_2.1.0-2_amd64.deb ...
    Unpacking torsocks (2.1.0-2) ...
    Selecting previously unselected package tor-geoipdb.
    Preparing to unpack .../tor-geoipdb_0.2.9.11-1ubuntu1~16.04.1_all.deb ...
    Unpacking tor-geoipdb (0.2.9.11-1ubuntu1~16.04.1) ...
    Processing triggers for man-db (2.7.5-1) ...
    Processing triggers for systemd (229-4ubuntu21.1) ...
    Processing triggers for ureadahead (0.100.0-19) ...
    Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
    Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
    Processing triggers for mime-support (3.59ubuntu1) ...
    Setting up python-attr (15.2.0-1) ...
    Setting up python-lzma (0.5.3-3) ...
    Setting up python-pam (0.4.2-13.2ubuntu2) ...
    Setting up python-psutil (3.4.2-1) ...
    Setting up python-pyasn1-modules (0.0.7-0.1) ...
    Setting up python-serial (3.0.1-1) ...
    Setting up python-service-identity (16.0.0-2) ...
    Setting up python-twisted-bin (16.0.0-1) ...
    Setting up python-zope.interface (4.1.3-1build1) ...
    Setting up python-twisted-core (16.0.0-1) ...
    Setting up tor (0.2.9.11-1ubuntu1~16.04.1) ...
    Setting up python-twisted (16.0.0-1) ...
    Setting up wmctrl (1.07-7) ...
    Setting up python-parsley (1.2-1) ...
    Setting up python-txsocksx (1.15.0.2-1) ...
    Setting up torbrowser-launcher (0.2.4-1) ...
    Setting up torsocks (2.1.0-2) ...
    Setting up tor-geoipdb (0.2.9.11-1ubuntu1~16.04.1) ...
    [master 20b0132] committing changes in /etc after apt run
     1 file changed, 1 deletion(-)
     delete mode 120000 systemd/system/tor.service

TBB fails upon first startup, after downloading and installing Tor Browser:

    $ torbrowser-launcher
    Tor Browser Launcher
    By Micah Lee, licensed under MIT
    version 0.2.4
    https://github.com/micahflee/torbrowser-launcher
    Downloading and installing Tor Browser for the first time.
    Downloading https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US
    Latest version: 7.5
    Downloading https://www.torproject.org/dist/torbrowser/7.5/tor-browser-linux64-7.5_en-US.tar.xz.asc
    Downloading https://www.torproject.org/dist/torbrowser/7.5/tor-browser-linux64-7.5_en-US.tar.xz
    Verifying signature
    Extracting tor-browser-linux64-7.5_en-US.tar.xz
    Running /home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
    Unhandled Error
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 916, in dispatcher
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1472, in _finishResponse_WAITING
        self._giveUp(Failure(reason))
      File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1525, in _giveUp
        self._disconnectParser(reason)
      File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1513, in _disconnectParser
        parser.connectionLost(reason)
    --- <exception caught here> ---
      File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 537, in connectionLost
        self.response._bodyDataFinished()
      File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 916, in dispatcher
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/twisted/web/_newclient.py", line 1161, in _bodyDataFinished_CONNECTED
        self._bodyProtocol.connectionLost(reason)
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 312, in connectionLost
        self.all_done(reason)
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 329, in response_finished
        self.run_task()
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 267, in run_task
        self.verify()
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 463, in verify
        self.run_task()
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 271, in run_task
        self.extract()
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 503, in extract
        self.run_task()
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 275, in run_task
        self.run()
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 519, in run
        if not self.check_min_version():
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 507, in check_min_version
        for line in open(self.common.paths['tbb']['versions']).readlines():
    exceptions.IOError: [Errno 2] No such file or directory: '/home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions'

Reattempting run with already-installed-browser fails:

    $ torbrowser-launcher
    Tor Browser Launcher
    By Micah Lee, licensed under MIT
    version 0.2.4
    https://github.com/micahflee/torbrowser-launcher
    Traceback (most recent call last):
      File "/usr/bin/torbrowser-launcher", line 30, in <module>
        torbrowser_launcher.main()
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 62, in main
        app = Launcher(common, url_list)
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 94, in __init__
        self.run(False)
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 519, in run
        if not self.check_min_version():
      File "/usr/lib/python2.7/dist-packages/torbrowser_launcher/launcher.py", line 507, in check_min_version
        for line in open(self.common.paths['tbb']['versions']).readlines():
    IOError: [Errno 2] No such file or directory: '/home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions'

That directory does not exist, nor does parent, but grandparent does:

    $ ls /home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions
    ls: cannot access '/home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources/versions': No such file or directory
    $ ls /home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources
    ls: cannot access '/home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs/sources': No such file or directory
    $ ls /home/pmocek/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Docs
    ChangeLog.txt  fteproxy  libfte  Licenses  meek  Obfsproxy

**Comment by alassek** [comment]
This is already fixed in 0.2.9

**Comment by pmocek** [comment]
duplicate of #306
