### ISSUE TITLE
Dependency pygtk is unmantained

### ISSUE THREAD

**Issue by ge-fa** [micahflee/torbrowser-launcher#319]
Hi,

Forwarding a [Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885489):

> pygtk is unmaintained upstream. It has not had a release since GNOME 3
was released in 2011.
>
> The way forward is to port your app to use GObject Introspection
bindings (and gtk3).
>
>For more information on GObject Introspection see [1] and [2].
>
>Please try to do this before the Buster release as we're going to
try to remove pygtk this cycle.
>
>If you have any question don't hesitate to ask.
>
>[1] https://wiki.gnome.org/Projects/GObjectIntrospection
>[2] https://wiki.gnome.org/Projects/PyGObject
>
>On behalf of the Debian GNOME team,
>Jeremy Bicha

Thanks for your work,
cheers,
Georg

**Comment by micahflee** [comment]
Good to know. I'm planning on switching from pygtk to PyQt5 (#321).
