### ISSUE TITLE
Major refactor

### ISSUE THREAD

**Issue by micahflee** [micahflee/torbrowser-launcher#321]
I'd like to change much of the underlying dependencies of torbrowser-launcher:

* Switch from python2 to python3 (will resolve #214)
* Switch from gtk2 to Qt5 (will resolve #319)
* Switch from twisted to using Qt threads for asynchronous
* Switch from txsocksx to requests/PySocks (will resolve #213)
* ~Switch from pygame (for playing optional .ogg) to pyaudio~ Alas, I think I'm actually just going to remove the modem sound. It was fun, but pygame for python3 isn't packaged, pyaudio doesn't support ogg files, and it's really not necessary anyway

This will make it much easier for me to maintain since I'm more familiar with this stack, and it's always good to switch to newer, actively maintained software.

**Comment by intrigeri** [comment]
> I'd like to change much of the underlying dependencies of torbrowser-launcher:

Sounds good! I don't expect the AppArmor profiles will need to be updated (they only confine Tor Browser currently) but still, it would be nice if you could tag an alpha/beta once the refactoring is done and poke me so I can make sure we're good on the AppArmor side before the official release :)

**Comment by micahflee** [comment]
Sounds good! I'll do that.

**Comment by elliott-sh** [comment]
I want modem back
