### ISSUE TITLE
Always downloads the en_US Tor Browser

### ISSUE THREAD

**Issue by intrigeri** [micahflee/torbrowser-launcher#323]
In a Debian sid VM with torbrowser-launcher 0.3.0~dev-1~exp2 installed (i.e. from the develop branch with the major refactoring merged) and `fr_FR.UTF-8` locales, the en_US Tor Browser is downloaded. Is that on purpose?

**Comment by intrigeri** [comment]
Note that the torbrowser-launcher UI is correctly displayed in French.

**Comment by micahflee** [comment]
That is not on purpose, it looks like it's a regression bug.
