### ISSUE TITLE
Slow desktop app when installed through launcher

### ISSUE THREAD

**Issue by binary132** [micahflee/torbrowser-launcher#326]
Ubuntu 18.04 x64 Gnome3 w/ native Nvidia drivers

I installed Tor browser 7.5.3 through `torbrowser-launcher`'s "reinstall" option and ran it.  The app's performance, even to open a new tab or move the window, is absolutely horrendously slow, and the window decorations are messed up.  Unmodified Firefox / FF nightly work just fine.

**Comment by micahflee** [comment]
That's odd. It shouldn't make a difference how you install it. Tor Browser Launcher just downloads and installs Tor Browser for you, and it doesn't modify it in any way. When you already have Tor Browser installed and launch it, TBL just opens it in the background, and then closes itself.

Try running this:

```sh
cd ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
./start-tor-browser.desktop
```

Is it still slow? If it is, it probably isn't a TBL problem, but rather some problem with Tor Browser itself on your computer.

**Comment by micahflee** [comment]
If that doesn't fix it, feel free to re-open this issue.

**Comment by binary132** [comment]
I'm pretty sure it's a pathological interaction in Firefox with the Gnome 3 API, because I've seen a similar performance regression in Firefox, which causes system-wide UI lag, and in a few other things outside of Firefox as well, such as Nautilus.  I'll link here if I discover what's going on.
