### ISSUE TITLE
Debian 9 x64 ./build_deb.sh

### ISSUE THREAD

**Issue by corsairetc** [micahflee/torbrowser-launcher#327]
Hello,
When I was start ./build_deb.sh I get this errors:
`sudo ./build_deb.sh 
rm: can't delete 'build': Folder or file doesn't exist
rm: can't delete 'deb_dist': Folder or file doesn't exist
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_deb'

To install, run:
sudo dpkg -i deb_dist/torbrowser-launcher_0.3.0.dev-1_all.deb`

What could be wrong ?

**Comment by ninetyfivenorth** [comment]
Re-run the dependency command:
`sudo apt install build-essential dh-python python3-all python3-stdeb python3-pyqt5 python3-gpg python3-requests python3-socks gnupg2 tor`

Make sure you acquire all the necessary depends then run:
`./build_deb.sh`

IF you have installed all the required prerequisites then run:
`sudo dpkg -i deb_dist/torbrowser-launcher_*.deb`

**Comment by micahflee** [comment]
Thanks @ninetyfivenorth, I think that should fix it
