### ISSUE TITLE
./torbrowser-launcher broken in git clone

### ISSUE THREAD

**Issue by davidhedlund** [micahflee/torbrowser-launcher#332]
> $ git clone https://github.com/micahflee/torbrowser-launcher
> Cloning into 'torbrowser-launcher'...
> remote: Counting objects: 2920, done.
> remote: Total 2920 (delta 0), reused 0 (delta 0), pack-reused 2920
> Receiving objects: 100% (2920/2920), 1.51 MiB | 1.32 MiB/s, done.
> Resolving deltas: 100% (1758/1758), done.
> Checking connectivity... done.
> $ cd torbrowser-launcher
> $ ./torbrowser-launcher
> Traceback (most recent call last):
>   File "./torbrowser-launcher", line 29, in <module>
>     import torbrowser_launcher
>   File "/home/foo/torbrowser-launcher/torbrowser_launcher/__init__.py", line 34, in <module>
>     from PyQt5 import QtCore, QtWidgets
> ImportError: No module named 'PyQt5

**Comment by micahflee** [comment]
You need to follow the instructions in [BUILD.md](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md). You haven't installed the dependencies that torbrowser-launcher relies on.

The build instructions also explain how to run it. You either need to build a package and install it and run it globally, or set the `TBL_SHARE` environment variable if you're running it from within the git repo dir.

**Comment by davidhedlund** [comment]
Thank you. You could implement detection of missing programs and print a message if they are missing. What do you think about it?

**Comment by micahflee** [comment]
I don't think it's necessary because `ImportError: No module named 'PyQt5` already does that, and really users should install the package. Running torbrowser-launcher from the source repository is intended for development.

**Comment by davidhedlund** [comment]
Ok, yes that make sense.
