### ISSUE TITLE
Running TorBrowser inside of Docker

### ISSUE THREAD

**Issue by MeFisto94** [micahflee/torbrowser-launcher#334]
Hey Guys,
based on https://github.com/jlesage/docker-firefox/ I am working on a TBB Docker Image.
I can get it working to the point where the launcher installs tbb sucessfully, however after the output of `Running /config/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop`, nothing happens.

Unfortunately I have come to a point where I don't know how to debug further, is there a way of forcing logs from tor browser? And should this rather be an issue for the tor browser team itself?

Here's the full log so far:
```
Launching './Browser/start-tor-browser --detach'...
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.8
https://github.com/micahflee/torbrowser-launcher
Creating GnuPG homedir /config/.local/share/torbrowser/gnupg_homedir
Refreshing local keyring...
Keyring refreshed successfully...
Downloading and installing Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Latest version: 7.5.4
Downloading https://www.torproject.org/dist/torbrowser/7.5.4/tor-browser-linux64-7.5.4_en-US.tar.xz.asc
Downloading https://www.torproject.org/dist/torbrowser/7.5.4/tor-browser-linux64-7.5.4_en-US.tar.xz
Verifying Signature
Extracting tor-browser-linux64-7.5.4_en-US.tar.xz
Running /config/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
```

Thanks in Advance for any help :)

Edit: Worth noting that the whole X-Server Stuff works, as I can see the progress bar during the download and after the "installing" step, I get a blackscreen.

**Comment by eyedeekay** [comment]
It may not be the best way to achieve what you're trying to do. Check out this URL: https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions - that should be enough to get the Tor Browser Version to keep your container up-to-date automatically by downloading it from the TBB download page. With that, you could just have your Dockerfile download the TBB and check it's signature in the container by passing build-args and environment variables. You can also configure how the TBB connects to Tor using environment variables. This would allow you to use different containers(one for Tor, one for the TBB) and keep your tbb container off of --net host. When I saw your question, I went ahead and made this: https://github.com/eyedeekay/tbb-docker which checks the RecommendedTBBVersions and builds both images configured to work with eachother just to see if I could. Unfortunately, there are a semi-confusing number of ways to run the TBB inside of Docker, and I don't know if mine is the best, but it might be a decent example of how.

**Comment by MeFisto94** [comment]
Hey :)
I wonder if one could not bypass the complex network setup by simply using a docker-compose file and make use of the `service` network mode. However one might still have to configure some iptables in the containers to block any other traffic.

Something like this:
```
version: '3'
services:
  tor:
    image: mefisto94/tor-socks-proxy
    ports:
      - "9150:9150" # Might not be needed
  containername:
    image: image....
    depends_on:
      - "tor"
    network_mode: "service:tor"
```

I think the exposal of the port is just a fault of me, because for tbb the tor ip might not be localhost but rather some internal ip.

In general I just used the launcher as it was recommended by debian, but you may be right that for a container, a manual setup might be more appropriate

**Comment by eyedeekay** [comment]
I am fairly certain you could do exactly that with docker-compose. My trouble is that I started using Docker before I became aware of docker-compose, and haven't had time to learn it to rid myself of the "scripting docker setups" anti-pattern. You could also express the network setup from my Makefiles in the docker-compose file if you wanted. As far as iptables, the way I did it was to assume that TBB would be the only application using Tor in this circumstance, and that it only needed to do normal TBB things(Connect to the SocksPort and the ControlPort) so the only settings I altered were the host that the Tor service ran on(from localhost to 172.70.70.2, so I could affix the IP address with Docker). I did this with the environment variables used to configure TBB for system-tor/Whonix-like setups. As long as it's used as a TBB-launcher, it should be safe in that way(AFAICT). It should also be possible to make the Socks Socket in the Tor Service docker container and mount it in the Tor Browser docker container and use TOR_SOCKS_IPC_FILE like in the hardened TBB but I didn't do that yet. Using the Socks Socket may be an alternative to iptables to prevent leaks.

Anyway, I doubt Micah's big on us using his project as a discussion point. Feel free to open an issue on my repo if you'd like to continue.

**Comment by micahflee** [comment]
It's possible that you need to set your working directory to `~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US`. It seems that you can't run `start-tor-browser.desktop` from any other folder.

```sh
user@dev ~ $ ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop 
/usr/bin/env: './Browser/execdesktop': No such file or directory
user@dev ~ $ cd ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/
user@dev ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US $ ./start-tor-browser.desktop 
Launching './Browser/start-tor-browser --detach'...
user@dev ~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US $ 
```
