### ISSUE TITLE
debian repo cannot start, update is needed from a site which is blocked

### ISSUE THREAD

**Issue by Ismoez** [micahflee/torbrowser-launcher#341]
packet: 0.2.9-3~bpo8+1 amd64  
In Turkey the domain torproject.org is blocked.
when trying to start torbrowser-launcher it freezes in downloading.
so the download doesnt start from url:
https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
![test](https://user-images.githubusercontent.com/18556841/44885910-17030f00-acb3-11e8-9302-d29af84c24af.png)

**Comment by micahflee** [comment]
Yup, you should be able to download from a mirror. You can also possible install `tor` on your system first, and then in the settings you can choose to download Tor Browser anonymously over tor.
