### ISSUE TITLE
apparmor problem for TB 8.0 on Debian 9.5

### ISSUE THREAD

**Issue by greymuse** [micahflee/torbrowser-launcher#348]
Hello,

I have package torbrowser-launcher 0.2.9-3~bpo9+1 installed.
After TB updated itself to the new 8.0, it no longer started.
After adding these 3 lines to /etc/apparmor.d/local/usr.bin.torbrowser-launcher TB starts again:

  /usr/bin/dirname ix,
  owner @{torbrowser_home_dir}/abicheck ix,
  owner @{torbrowser_home_dir}/firefox.real ix,

I do not know if this is the proper apparmor config file to put them in or if this is a secure/an optimal configuration change, but it works.
The lines are needed for calls in the sh script @{torbrowser_home_dir}/firefox (the same folder where start-tor-browser is located):
Otherwise the call to dirname is denied and the variable basedir becomes empthy; the commands abicheck and firefox.real are also denied.

**Comment by greymuse** [comment]
Addendum:

There is some problem with using /usr/bin/lsb_release and reading /etc/ld.so.conf.d/ as well. Typical complaint in /var/log/syslog is:

```
audit: type=1400 audit(1536672858.855:175): apparmor="DENIED" operation="open" profile="torbrowser_firefox" name="/etc/ld.so.conf" pid=17372 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=xxxx ouid=0
audit: type=1400 audit(1536672858.867:176): apparmor="DENIED" operation="exec" profile="torbrowser_firefox" name="/usr/bin/lsb_release" pid=17392 comm="firefox.real" requested_mask="x" denied_mask="x" fsuid=xxxx ouid=0
audit: type=1400 audit(1536672858.955:177): apparmor="DENIED" operation="open" profile="torbrowser_firefox" name="/etc/ld.so.conf" pid=17372 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=xxxx ouid=0
```

Symptom: when you download a file and when you in the save-to-file dialog click OK button TB crashes.
In syslog you then see:

```
audit: type=1400 audit(1536673154.475:181): apparmor="DENIED" operation="open" profile="torbrowser_firefox" name="/usr/share/glib-2.0/schemas/gschemas.compiled" pid=17372 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=xxxx ouid=0
traps: firefox.real[17372] trap int3 ip:7fe54c5ca261 sp:7fff46978c80 error:0 in libglib-2.0.so.0.5000.3[7fe54c57a000+112000]
Chrome_~dThread[17487]: segfault at 0 ip 00007f58a16493b6 sp 00007f589febcb10 error 6 in libxul.so[7f58a11cd000+56bc000]
Chrome_~dThread[17443]: segfault at 0 ip 00007fc6d0cfc3b6 sp 00007fc6cf56fb10 error 6 in libxul.so[7fc6d0880000+56bc000]

```

I've read somewhere that TB should use libgtk 3, maybe that is the problem...

Adding things like:

 ```
/etc/ld.so.conf r,
/usr/bin/lsb_release rix,
```

or:

```
/etc/ld.so.conf r,
/usr/bin/lsb_release rux,
```

does not help.

**Comment by rogers0** [comment]
@greymuse I think you're using stretch, so just try to apt update and upgrade.
I uploaded 0.2.9-5~bpo9+1 three days ago.

Or you may try the latest 0.3.0-1~exp1 in experimental repo [1].

[1] https://wiki.debian.org/TorBrowser#Debian_.22experimental.22

**Comment by greymuse** [comment]
Hi,

Yes, I run stretch. But I use a bpo kernel, package linux-image-4.14.0-0.bpo.3-amd64.
That is the only bpo package that is relevant, otherwise my stretch is pretty "clean" (I have 4 bpo packages in total).

With torbrowser-launcher 0.2.9-5~bpo9+1 TB still crashes. The program firefox.real is denied, and the kernel reports a trap error for libglib-2.0.so.0.5000.3 and segfaults for libxul.so.

I'll investigate some more (boot into kernel 4.9) and test your experimental package. I'll be back.

**Comment by rogers0** [comment]
@greymuse please try to install:
```
apt install -t stretch-backports linux-image-amd64 gnupg
```
reboot to latest kernel and then try TBB again.

**Comment by greymuse** [comment]
Hello,

Thank you for the reply.
I removed my additions under /etc/apparmor.d/local.
Yes, with your "implied" upgrade to kernel package linux-image-4.18.0-0.bpo.1-amd64 (version 4.18.6-1~bpo9+1) together with package torbrowser-launcher 0.2.9-6~bpo9+1 TBB 8.0.1 and 8.0,2 now start OK and I can save downloaded files. (The old bpo linux-image package still doesn't work.)

TBB also works with kernel linux-image-4.9.0-8-amd64 (version 4.9.110-3+deb9u5).

So problem is fixed. Thank you very much!
