### ISSUE TITLE
SIGNATURE VERIFICATION FAILED!

### ISSUE THREAD

**Issue by ghostoffreedom** [micahflee/torbrowser-launcher#349]
Unable to install tor-browser on **linux Fedora 28**  and this error message appear

**Error Code: EB774491D9FF06E2: No public key**

**Comment by micahflee** [comment]
I've confirmed this one, I'm getting it too

**Comment by micahflee** [comment]
This is fixed in the new version 0.3.0 that I just released. You can get it by either [installing from source](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md) or installing from the Ubuntu PPA, described [here](https://github.com/micahflee/torbrowser-launcher/blob/develop/README.md#installing-in-ubuntu).

**Comment by hThoreau** [comment]
Hi @micahflee. I've installed torbrowser-launcher from source, as I was having this issue using the version available through the Debian experimental repository, `0.3.0~dev-1~exp3`. But as of now, I'm experiencing this same error described above. :/

**Comment by rogers0** [comment]
@hThoreau 0.3.0~dev-1~exp3 is 3-month ago version, so it's not latest.
Please try debian sid version (0.2.9-4) or build from latest source.

**Comment by micahflee** [comment]
@hThoreau you're having this issue now, when you installed from source from the 0.3.0 tag? What version of Debian are you using?

@DJKuhpisse (who commented on #354), have you tried installing the latest torbrowser-launcher from the PPA in ubuntu? Does that fix it?

**Comment by hThoreau** [comment]
@micahflee 0.3.0 tag? I haven't seen that being pointed out. I followed the instructions you've [linked](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md) for building from source using Debian. `apt` points out the package version is `0.3.0-1`. I'm using a Subgraph Aaron, which is based on Debian Stretch. I'm getting the same screen that @DJKuhpisse has just pasted.

**Comment by ghostoffreedom** [comment]
I think the problem is in **Tor Browser Launcher** not in the browser, because I reinstalled **Fedora** and that everything works fine

**Comment by Mikaela** [comment]
I think it works on Debian Testing as the download seems successfull and the output ends to `Launching './Browser/start-tor-browser --detach'...`, but apparmor blocks it from starting.

```
type=AVC msg=audit(1538158891.742:191): apparmor="DENIED" operation="exec" profile="torbrowser_firefox" name="/usr/bin/lsb_release" pid=5296 comm="firefox.real" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0                          
type=AVC msg=audit(1538158892.278:192): apparmor="DENIED" operation="open" profile="torbrowser_firefox" name="/usr/share/fontconfig/conf.avail/" pid=5276 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0             
type=AVC msg=audit(1538158892.334:193): apparmor="DENIED" operation="open" profile="torbrowser_firefox" name="/usr/share/uim/lib/sigscheme-init.scm" pid=5276 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0         
type=AVC msg=audit(1538158933.966:194): apparmor="DENIED" operation="capable" profile="torbrowser_firefox" pid=5401 comm="firefox.real" capability=21  capname="sys_admin"
type=AVC msg=audit(1538158934.070:195): apparmor="DENIED" operation="exec" profile="torbrowser_firefox" name="/usr/bin/lsb_release" pid=5421 comm="firefox.real" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0                          
type=AVC msg=audit(1538158934.566:196): apparmor="DENIED" operation="open" profile="torbrowser_firefox" name="/usr/share/fontconfig/conf.avail/" pid=5401 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0             
type=AVC msg=audit(1538158934.618:197): apparmor="DENIED" operation="open" profile="torbrowser_firefox" name="/usr/share/uim/lib/sigscheme-init.scm" pid=5401 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0   
```

Is the command to remove all Tor Browser launcher files documented anywhere? I recently distro-hopped from Ubuntu to Debian with the same /home, so I thought that my issues with Tor Browser Launcher might come from it and cause these problems. In the end I just ended up downloading it by hand.

**Comment by AqwelF** [comment]
Hi,
Same problem here.

I installed torbrowser on debian stretch using :
`apt install torbrowser-launcher -t stretch-backports`

**Comment by rogers0** [comment]
@AqwelF please try to apt update & upgrade.
I just uploaded a new version to stretch-backports.
