### ISSUE TITLE
SINGNATURE VERIFICATION FAILED! TOR BROWSER

### ISSUE THREAD

**Issue by solrac865** [micahflee/torbrowser-launcher#353]
I get this everytime i try to install tor browser 

SIGNATURE VERIFICATION FAILED!

Error Code: GENERIC_VERIFY-FAIL

You might be under attack, there might be a network 
problem, or you may be missing a recently added 
Tor Browser verification key.
click Start to refresh the keyring and try again. if the 
message persists report the above error code here:
Https://github.com/micahflee/torbrowser-launcher/issues

i clicked start 2 times and this always comes up? 
can anyone help?

**Comment by micahflee** [comment]
Sorry about that! This has been fixed in the latest version of torbrowser-launcher. You can get it by either [building from source](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md) or using the Ubuntu PPA that's described in the readme.
