### ISSUE TITLE
Cannot update to 0.3.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by wviechtb** [micahflee/torbrowser-launcher#355]
I am on Ubuntu 16.04, with `torbrowser-launcher` version `0.2.9-1` installed. The update to `0.3.0` fails because it depends on `python3-gpg`, which is not available for Xenial (there is `python3-gpgme`). Not a big deal for me, since the Tor Browser is already installed and updates itself just fine, but this could be an issue for somebody trying to install `torbrowser-launcher` fresh right now on 16.04 (upgrading to 18.04 of course is a solution).

**Comment by qazip** [comment]
@micahflee, is there something you can do about this? It's a deal-breaker to me.

**Comment by davidbaumann** [comment]
Closed this issue as it is outdated.
