### ISSUE TITLE
Can't install due to un-installable package: python3-gpg

### ISSUE THREAD

**Issue by GNUbahn** [micahflee/torbrowser-launcher#357]
When installing via Micah's PPA I got this message:

```
~$ sudo apt-get install torbrowser-launcher
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 torbrowser-launcher : Depends: python3-gpg but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I have done it a number of times before without any issues at all. According to synaptic I have no broken packages. I have tried to update and (full and dist) upgrade, and reboot reboot in any possible combination of ways

**Comment by GNUbahn** [comment]
This problem was reproduced on a fresh Linux Mint 19.3 installation

**Comment by qazip** [comment]
Same problem on Ubuntu 16.04

**Comment by GNUbahn** [comment]
I did not experience this issue on my latest attempt (Trisquel 8.0)

However, I did experience this issue: https://github.com/micahflee/torbrowser-launcher/issues/382

**Comment by davidbaumann** [comment]
Closed as the ppa is EOL.
