### ISSUE TITLE
Language should be selected from LC_MESSAGES, not LC_CTYPE

### ISSUE THREAD

**Issue by creideiki** [micahflee/torbrowser-launcher#361]
Since upgrading torbrowser-launcher to 0.3.0, I suddenly get a Tor Browser in Swedish, even though my system and my existing Tor Browser installation is in English.

I want programs to accept Swedish strings and give me understandable and searchable English messages instead of poor translations, so I have the following locale settings:
```sh
LC_ADDRESS=sv_SE.utf8
LC_COLLATE=POSIX
LC_CTYPE=sv_SE.utf8
LC_IDENTIFICATION=sv_SE.utf8
LC_MEASUREMENT=sv_SE.utf8
LC_MESSAGES=POSIX
LC_MONETARY=sv_SE.utf8
LC_NAME=sv_SE.utf8
LC_NUMERIC=sv_SE.utf8
LC_PAPER=sv_SE.utf8
LC_TELEPHONE=sv_SE.utf8
LC_TIME=sv_SE.utf8
```

The current code (at https://github.com/micahflee/torbrowser-launcher/blob/develop/torbrowser_launcher/common.py#L76) selects language based on `locale.getlocale()`, which checks `LC_CTYPE`. According to `setlocale(3)`, `LC_CTYPE` controls "Character classification", while `LC_MESSAGES` controls "Localizable natural-language messages". Thus, `LC_MESSAGES` should be used instead.

Also, since the code never calls `locale.setlocale()`, it relies on [Python bug 6203](https://bugs.python.org/issue6203) to set `LC_CTYPE` (but no other locale categories). To import the correct value from the environment, something like this should be used instead:
```python
locale.setlocale(locale.LC_MESSAGES, '')
locale.getlocale(locale.LC_MESSAGES)
```
since `locale.getlocale()` is `None` for all categories except `LC_CTYPE` until `locale.setlocale()` is called explicitly:
```python
~ $ env LC_MESSAGES="ja_JP.utf8" python3
Python 3.6.6 (default, Jul  7 2018, 10:31:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale(locale.LC_MESSAGES)
(None, None)
>>> locale.setlocale(locale.LC_MESSAGES, '')
'ja_JP.utf8'
>>> locale.getlocale(locale.LC_MESSAGES)
('ja_JP', 'UTF-8')
>>> 
```
with the already existing fallback to `en-US` retained, since `locale.getlocale()` returns `None` when it means `POSIX` or `C`:
```python
Python 3.6.6 (default, Jul  7 2018, 10:31:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_MESSAGES, '')
'C'
>>> locale.getlocale(locale.LC_MESSAGES)
(None, None)
>>> import os
>>> os.environ['LC_MESSAGES']
'POSIX'
>>> 
```

This also means that language selection as currently implemented does not work on Python 2, since it does not suffer from bug 6203 and lets `LC_CTYPE` stay at the POSIX default of `C` (and `locale.getlocale()` return `None`) until explicitly told otherwise by a call to `locale.setlocale()`.

**Comment by sHAsHiLx** [comment]
so how to fix it excepting editing /usr/lib/python2.7/site-packages/torbrowser_launcher/common.py and changing self.language='ru'?

**Comment by creideiki** [comment]
I have ben running with the change I wrote about above for a couple of months, without problems. I have not sent a pull request because I have not tested it on any configuration but mine.

The exact patch is:
```patch
diff --git a/torbrowser_launcher/common.py b/torbrowser_launcher/common.py
index 4e3a30a..cdd912a 100644
--- a/torbrowser_launcher/common.py
+++ b/torbrowser_launcher/common.py
@@ -73,7 +73,8 @@ class Common(object):
 
         # figure out the language
         available_languages = ['ar', 'ca', 'da', 'de', 'en-US', 'es-ES', 'fa', 'fr', 'ga-IE', 'he', 'id', 'is', 'it', 'ja', 'ko', 'nb-NO', 'nl', 'pl', 'pt-BR', 'ru', 'sv-SE', 'tr', 'vi', 'zh-CN', 'zh-TW']
-        default_locale = locale.getlocale()[0]
+        locale.setlocale(locale.LC_MESSAGES, '')
+        default_locale = locale.getlocale(locale.LC_MESSAGES)[0]
         if default_locale is None:
             self.language = 'en-US'
         else:
```

**Comment by rogers0** [comment]
@sHAsHiLx @creideiki 

I uploaded 0.3.2-10 to debian, and included this patch.
- https://tracker.debian.org/news/1122382/accepted-torbrowser-launcher-032-10-source-into-unstable/

If you use debian, you can install it from backports.
- https://wiki.debian.org/TorBrowser#Debian_10_.22Buster.22
