### ISSUE TITLE
torbowser-launcher-0.3.0 creates an empty window on tiling window managers.

### ISSUE THREAD

**Issue by crocket** [micahflee/torbrowser-launcher#365]
I'm on i3 window manager. This issue is annoying. I have to close an empty window whenever I launch torbrowser-launcher.

![2018-09-30_sun_23 53 02](https://user-images.githubusercontent.com/748856/46264418-8d678b00-c557-11e8-9d0b-57c185e77dc6.png)

![2018-09-30_sun_23 53 17](https://user-images.githubusercontent.com/748856/46264417-8d678b00-c557-11e8-820d-7263fa1dcf10.png)

**Comment by blackPantherOS** [comment]
Here available my hotfix for empty window problem: https://github.com/blackPantherOS/torbrowser-launcher/commit/8bd90bebf074ee3030a11e6c4e8ed0342c7cb24b

**Comment by crocket** [comment]
0.3.1 somehow fixed this issue. Confirm that it is fixed by closing this issue.
