### ISSUE TITLE
Signature Verification Failed

### ISSUE THREAD

**Issue by c3lsi0r** [micahflee/torbrowser-launcher#366]
Error Code: Generic_Verify_Fail

You might be under attack, there might ba a network problem, or you be missing a recently added Tor Browser verification key.
Click start to refresh the keyring and try again. if the message persists report the above code here:
https://github.com/micahflee/torbrowser-launcher/issues

**Comment by FredrikLindseth** [comment]
This happens to me on Ubuntu 18.10 with the Tor Browser Launcher via apt.

**Comment by micahflee** [comment]
See https://github.com/micahflee/torbrowser-launcher/issues/382#issuecomment-451603188

**Comment by noloader** [comment]
Add a "mee too" for Ubuntu 18.04.03 x86_64 (fully patched).

I can't seem to get beyond this failure. It has been going on 6 months to a year:

![Screenshot from 2019-12-18 15-27-08](https://user-images.githubusercontent.com/3538226/73025802-3fd2f980-3dfe-11ea-950e-5550e82d34db.png)

Why can't Tor and Ubuntu get this to work?
