### ISSUE TITLE
Signature  verification failed !

### ISSUE THREAD

**Issue by navneetmuffin** [micahflee/torbrowser-launcher#368]
Error Code: Generic_Verify_Fail

You might be under attack, there might ba a network problem, or you be missing a recently added Tor Browser verification key.
Click start to refresh the keyring and try again. if the message persists report the above code here:
https://github.com/micahflee/torbrowser-launcher/issues

**Comment by micahflee** [comment]
https://github.com/micahflee/torbrowser-launcher/issues/382#issuecomment-451603188
