### ISSUE TITLE
signature verification failed

### ISSUE THREAD

**Issue by Hacker3541** [micahflee/torbrowser-launcher#369]
![screenshot at 2018-10-06 06-02-07](https://user-images.githubusercontent.com/39010717/46567990-9a231f00-c95b-11e8-814a-b6238dc18153.png)
hey tor team, i experienced with signature verification problem.Can you please give me solution for this.
This is my email id "kushagrasrivastav728@gmail.com"
Why you are closed the tor messager

**Comment by micahflee** [comment]
See https://github.com/micahflee/torbrowser-launcher/issues/382#issuecomment-451603188
