### ISSUE TITLE
GENERIC_VERIFY_FAIL

### ISSUE THREAD

**Issue by Andrewluck248** [micahflee/torbrowser-launcher#371]
########
I Get this when trying to run 
sudo apt service Tor start [in the terminal ] 
##########
Oct 06 09:27:52.255 [notice] Tor 0.3.4.8 (git-5da0e95e4871a0a1) running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.0h, Zlib 1.2.11, Liblzma 5.2.2, and Libzstd 1.3.5.
Oct 06 09:27:52.255 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Oct 06 09:27:52.255 [notice] Read configuration file "/etc/tor/torrc".
Oct 06 09:27:52.257 [notice] Scheduler type KIST has been enabled.
Oct 06 09:27:52.257 [notice] Opening Socks listener on 127.0.0.1:9050
Oct 06 09:27:52.257 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
Oct 06 09:27:52.258 [notice] Opening DNS listener on 127.0.0.1:53
Oct 06 09:27:52.258 [warn] Could not bind to 127.0.0.1:53: Permission denied
Oct 06 09:27:52.258 [notice] Opening Transparent pf/netfilter listener on 127.0.0.1:9040
Oct 06 09:27:52.258 [warn] Could not bind to 127.0.0.1:9040: Address already in use. Is Tor already running?
Oct 06 09:27:52.258 [notice] Opening Control listener on 127.0.0.1:9051
Oct 06 09:27:52.258 [warn] Could not bind to 127.0.0.1:9051: Address already in use. Is Tor already running?
Oct 06 09:27:52.258 [warn] Failed to parse/validate config: Failed to bind one of the listener ports.
Oct 06 09:27:52.258 [err] Reading config failed--see warnings above.
##########

then when i try and when i try and open the browser i get this 

SIGNATURE VERIFICATION FAILED!
Error Code: GENERIC_VERIFIY_FAIL 

You might be under attack .......
#######

i have tried re-installing the browser and still doesn't seem to work on mirror on list. and i seem to be unable to connect at all with tor unless i run the apt service tor start command

**Comment by micahflee** [comment]
See https://github.com/micahflee/torbrowser-launcher/issues/382#issuecomment-451603188
