### ISSUE TITLE
Signature Verification takes an eternality

### ISSUE THREAD

**Issue by colourful-land** [micahflee/torbrowser-launcher#379]
What I got is this:

"Downloading and installing Tor Browser..."
"Verifying signature"

and the progress is at 0% for 8 hours.

I request to add a timeout function so the user gets an error in 10 minutes, instead of having the app hanging there for 8 hours.

**Comment by RoboRocky** [comment]
SIGNATURE VERIFICATION FAILED

32BIT LINUX MINT

**Comment by RoboRocky** [comment]
Error Code:  GENREIC_VERIFY_FAIL

**Comment by RoboRocky** [comment]
WRONG KEY ?
