### ISSUE TITLE
url argument in torbrowser-launcher is ignored

### ISSUE THREAD

**Issue by pwnage101** [micahflee/torbrowser-launcher#380]
The ability to specify a URL argument on the `torbrowser-launcher` command was added in 028bc225ace555adc3314fa95751d29659a14778 in 2014.  The following year, 3d9f4edc206ade74ff1b4194297e20025e51b793 broke it.  I'm guessing this was an accident because much of the URL passing code-scaffolding was left untouched, including the man page which states that there is a url argument.

Testing:

I ran this on Ubuntu 18.04:
```
$ torbrowser-launcher "https://www.debian.org/"
```
And tor browser launched successfully, but only the default "About Tor" page opened.

Versions:

Ubuntu 18.04
torbrowser-launcher 0.2.9-2
Tor Browser 8.0.4

**Comment by pmaziere** [comment]
as a temporary solution, tested on Debian Linux testing,  here is what I did:
in launcher.py, after the "Run Tor Browser" comment, replace:
```
subprocess.call([self.common.paths['tbb']['start']], cwd=self.common.paths['tbb']['dir_tbb'])
```
by:
 ```
subprocess.call([self.common.paths['tbb']['start']] + self.url_list, cwd=self.common.paths['tbb']['dir_tbb'])
```

but it won't like it if you already have a Tor Browser instance running.

**Comment by beroal** [comment]
Is there any progress on this? I often used this option with Tor Browser (without Launcher), but was forced to move to Tor Browser Launcher recently.
