### ISSUE TITLE
Re-opening: Initial use: SIGNATURE VERIFICATION FAILED (no error code) 

### ISSUE THREAD

**Issue by GNUbahn** [micahflee/torbrowser-launcher#384]
This is a re-opening, i.e. a copy of a 'closed' issue (https://github.com/micahflee/torbrowser-launcher/issues/382)

The exact same thing happened on a new fresh install of Trisquel 8.0 (Flidas) on a librebooted device:

On a fresh install of Trisquel 8.0, Tor Browser Launcher downloads Tor Browser without problems but signature verification gives me: SIGNATURE VERIFICATION FAILED

I was presented with no error code. See the attached pic.

signature verification failed
![torbrowser_fail](https://user-images.githubusercontent.com/22903560/51071074-40f61600-1643-11e9-8876-b888a0c25a12.png)

(I an uncertain if this is the right way to re-open a closed issue that wasn't solved)

**Comment by traumschule** [comment]
Hey, see [#382](/micahflee/torbrowser-launcher/issues/382#issuecomment-451603188). I suggest you poke your distro maintainers a bit.

> The problem is that occasionally an update on Tor Browser's side breaks Tor Browser Launcher, and then once it's fixed, the fix takes a very long time to make it into package repositories. For example, Trisquel 8.0 includes torbrowser-launcher 0.2.4, from March 2016. But if you install torbrowser-launcher in Debian Buster (which includes version 0.3.1) it works fine without a verification error.

**Comment by GNUbahn** [comment]
I did install from Micah's PPA

Although, I realised that running:

```
~$ apt search torbrowser-launcher
Sorting... Done
Full Text Search... Done
torbrowser-launcher/flidas,now 0.2.4-1 amd64 [installed]
  helps download and run the Tor Browser Bundle
```

I suppose this means that the newer version from Micah's PPA is not installed?
![ppa](https://user-images.githubusercontent.com/22903560/51072958-e6b87d80-1661-11e9-9ee7-f88992adfb8d.png)

**Comment by traumschule** [comment]
Can you paste the output of `apt policy torbrowser-launcher`, this is what i see:
```
# apt search torbrowser-launcher
Sorting... Done
Full Text Search... Done
torbrowser-launcher/stretch-backports 0.3.1-2~bpo9+1 i386
  helps download and run the Tor Browser Bundle
# apt policy torbrowser-launcher
torbrowser-launcher:
  Installed: (none)
  Candidate: 0.3.1-2~bpo9+1
  Version table:
     0.3.1-2~bpo9+1 100
        100 tor://vwakviie2ienjx6t.onion/debian stretch-backports/contrib i386 Packages
```

**Comment by traumschule** [comment]
This confirms that trisquel should update, not much the maintainer of this repository can do about.

**Comment by GNUbahn** [comment]
What indicates that?

Should it not be possible to install from Micah's PPA?

**Comment by GNUbahn** [comment]
This drives me crazy. As you can see from the screenshot attached above, Micah's PPA is added, registered and recognised by trisquel. It is also shown by
```
~$ ls /etc/apt/sources.list.d
micahflee-ubuntu-ppa-xenial.list
```
But tha PPA seems to be not recognised when I try to install from it:
```
~$ sudo apt install torbrowser-launcher
Reading package lists... Done
Building dependency tree
Reading state information... Done
torbrowser-launcher is already the newest version (0.2.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
This is consistent with a search command output:```

~$ apt search torbrowser-launcher
Sorting... Done
Full Text Search... Done
torbrowser-launcher/flidas,now 0.2.4-1 amd64 [installed]
  helps download and run the Tor Browser Bundle
```
And with a policy command output:
```
~$ apt policy torbrowser-launcher
torbrowser-launcher:
  Installed: 0.2.4-1
  Candidate: 0.2.4-1
  Version table:
 *** 0.2.4-1 500
        500 http://es.archive.trisquel.info/trisquel flidas/main amd64 Packages
        100 /var/lib/dpkg/status
```
According to the Github page, the latest version, which I expected to have installed, is v0.3.1: https://github.com/micahflee/torbrowser-launcher/releases

How come Trisquel does not recognise the version from Michah's PPA?

**Comment by traumschule** [comment]
Do you see any errors for `apt update`?

**Comment by GNUbahn** [comment]
No. Except I just realised, that it doesn't update from Micah's PPA!

```
~$ sudo apt update
[sudo] password for jcb: 
Hit:1 http://es.archive.trisquel.info/trisquel flidas InRelease
Get:2 http://es.archive.trisquel.info/trisquel flidas-security InRelease [4,898 B]
Get:3 http://es.archive.trisquel.info/trisquel flidas-updates InRelease [6,124 B]
Hit:4 http://es.archive.trisquel.info/trisquel flidas-backports InRelease
Get:5 http://es.archive.trisquel.info/trisquel flidas-security/main Sources [218 kB]
Get:6 http://es.archive.trisquel.info/trisquel flidas-security/main amd64 Packages [771 kB]
Get:7 http://es.archive.trisquel.info/trisquel flidas-security/main i386 Packages [769 kB]
Get:8 http://es.archive.trisquel.info/trisquel flidas-updates/main Sources [594 kB]
Get:9 http://es.archive.trisquel.info/trisquel flidas-updates/main amd64 Packages [1,637 kB]
Get:10 http://es.archive.trisquel.info/trisquel flidas-updates/main i386 Packages [1,626 kB]
Fetched 5,627 kB in 3s (1,737 kB/s)                           
Reading package lists... Done
Building dependency tree       
Reading state information... Done
22 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

**Comment by GNUbahn** [comment]
@traumschule, maybe this is what you were trying to make me understand:

> I've found the problem. See here:
> 
> https://launchpad.net/~micahflee/+archive/ubuntu/ppa/+packages
> 
> The PPA does not have torbrowser-launcher packaged for Xenial, only
> Bionic and Cosmic. Since Trisquel 8 is based on Xenial, there's no
> package available.

https://trisquel.info/en/forum/install-ppa-rather-repo#comment-138454
