### ISSUE TITLE
initial use error

### ISSUE THREAD

**Issue by djh42** [micahflee/torbrowser-launcher#386]
I just tried to install on openSUSE Leap 15.0 and got an error. The dialog box is one of the annoying type that won't let me copy the text! The console log is below. I don't know much about what I'm looking at, so I suppose it's something simple :)

```
$ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.9
https://github.com/micahflee/torbrowser-launcher
Refreshing local keyring...
Downloading and installing Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Latest version: 8.0.4
Downloading https://www.torproject.org/dist/torbrowser/8.0.4/tor-browser-linux64-8.0.4_en-US.tar.xz.asc
Downloading https://www.torproject.org/dist/torbrowser/8.0.4/tor-browser-linux64-8.0.4_en-US.tar.xz
Verifying Signature
Refreshing local keyring... Missing key: EB774491D9FF06E2
Starting download over again
Downloading https://www.torproject.org/dist/torbrowser/8.0.4/tor-browser-linux64-8.0.4_en-US.tar.xz
Verifying Signature
Refreshing local keyring... Missing key: EB774491D9FF06E2
```

**Comment by Dumbledorf** [comment]
I'm having the exact same issue in Ubuntu 18.04. It fails to verify the signature every time. Error code isn't all that helpful either.

![GENERIC_VERIFY_FAIL](https://i.imgur.com/cKfek21.png)

**Comment by djh42** [comment]
FWIW, afterwards I downloaded the version from https://www.torproject.org/dist/torbrowser/8.0.4/tor-browser-linux64-8.0.4_en-US.tar.xz and that installed fine.

**Comment by Dumbledorf** [comment]
Well that's odd. Works for me as well!

Thanks for the solution.

**Comment by brunces** [comment]
Guys, I was having the same issue, then I decided to turn off my firewall (GUFW) and try to launch Tor Browser again. It worked! Then, I turned on the firewall again and now everything's working normally. I really don't know if the issue was really caused by the firewall, but that was the one and only thing I did and it worked. I hope this is useful somehow.

**Comment by noloader** [comment]
Add a "mee too" for Ubuntu 18.04.03 x86_64 (fully patched).

I can't seem to get beyond this failure. It has been going on 6 months to a year:

![Screenshot from 2019-12-18 15-27-08](https://user-images.githubusercontent.com/3538226/73025802-3fd2f980-3dfe-11ea-950e-5550e82d34db.png)

Why can't Tor and Ubuntu get this to work?
