### ISSUE TITLE
GENERIC_VERIFY_FAIL in Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by tops91** [micahflee/torbrowser-launcher#388]
Trying to install Tor browser through the Ubuntu software installer, but getting the above error every time. Please help. Thanks in advance.

**Comment by cryptohasher76** [comment]
having the same issue they tried installed directly from ppa -- new error 

Extracting tor-browser-linux64-8.0.8_en-US.tar.xz
TypeError: error() missing 1 required positional argument: 'message'

**Comment by brunces** [comment]
Guys, I was having the same issue, then I decided to turn off my firewall (GUFW) and try to launch Tor Browser again. It worked! Then, I turned on the firewall again and now everything's working normally. I really don't know if the issue was really caused by the firewall, but that was the one and only thing I did and it worked. I hope this is useful somehow.

**Comment by rowland007** [comment]
> Guys, I was having the same issue, then I decided to turn off my firewall (GUFW) and try to launch Tor Browser again. It worked! Then, I turned on the firewall again and now everything's working normally. I really don't know if the issue was really caused by the firewall, but that was the one and only thing I did and it worked. I hope this is useful somehow.

Didn't work for me. I disabled my firewall by running `sudo ufw disable` then executed the launcher again. The download went much quicker but it still valid the signature verification.  Signature verification still took a few mins too.

**Comment by noloader** [comment]
Add a "mee too" for Ubuntu 18.04.03 x86_64 (fully patched).

I can't seem to get beyond this failure. It has been going on 6 months to a year:

![Screenshot from 2019-12-18 15-27-08](https://user-images.githubusercontent.com/3538226/73025802-3fd2f980-3dfe-11ea-950e-5550e82d34db.png)

Why can't Tor and Ubuntu get this to work?
