### ISSUE TITLE
help

### ISSUE THREAD

**Issue by r3x07** [micahflee/torbrowser-launcher#390]
adham@fbi:~$ torbrowser-launcher
Traceback (most recent call last):
  File "/usr/local/bin/torbrowser-launcher", line 29, in <module>
    import torbrowser_launcher
  File "/usr/local/lib/python2.7/dist-packages/torbrowser_launcher/__init__.py", line 36, in <module>
    from .common import Common, SHARE
  File "/usr/local/lib/python2.7/dist-packages/torbrowser_launcher/common.py", line 38, in <module>
    import gpg
ImportError: No module named gpg

**Even tho i have it installed**

root@fbi:/adham# apt-get install gpg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gpg is already the newest version (2.2.12-1).
The following packages were automatically installed and are no longer required:
  android-framework-res android-libaapt android-libandroidfw
  android-libbacktrace android-libbase android-libcutils android-liblog
  android-libunwind android-libutils android-libziparchive couchdb
  erlang17-asn1 erlang17-base erlang17-crypto erlang17-eunit erlang17-inets
  erlang17-mnesia erlang17-os-mon erlang17-public-key erlang17-runtime-tools
  erlang17-snmp erlang17-ssl erlang17-syntax-tools erlang17-tools
  erlang17-webtool erlang17-xmerl famfamfam-flag-png gir1.2-mutter-1
  gir1.2-networkmanager-1.0 gir1.2-nmgtk-1.0 glusterfs-common
  gnome-themes-standard guile-2.0-libs gvfs-bin i2p i2p-router junit
  libacl1-dev libantlr-java libantlr3-runtime-java libapache-pom-java
  libarmadillo8 libatinject-jsr330-api-java libattr1-dev libavahi-gobject0
  libavfilter6 libavformat57 libavresample3 libbabeltrace-ctf1 libbind9-160
  libboost-date-time1.62.0 libboost-filesystem1.62.0 libbz2-1.0:i386
  libcamel-1.2-60 libcdio17 libcgal13 libchamplain-0.12-0 libcommons-cli-java
  libcommons-io-java libcommons-lang3-java libcommons-parent-java libcue1
  libcurl4:i386 libdee-1.0-4 libdigest-md5-file-perl libdns169
  libeclipse-jdt-core-java libedata-cal-1.2-28 libedataserver-1.2-22
  libedataserverui-1.2-1 libel-api-java libenca0 libexempi3 libfcgi-bin
  libfcgi0ldbl libfile-copy-recursive-perl libfolks-telepathy25
  libfreerdp-cache1.1 libfreerdp-client1.1 libfreerdp-codec1.1
  libfreerdp-common1.1.0 libfreerdp-core1.1 libfreerdp-crypto1.1
  libfreerdp-gdi1.1 libfreerdp-locale1.1 libfreerdp-primitives1.1
  libfreerdp-utils1.1 libgail-3-0 libgcab-1.0-0 libgcr-3-common
  libgdbm-compat4:i386 libgdbm6:i386 libgetopt-java libgfchangelog0 libgfdb0
  libgfortran4 libglusterfs-dev libgnome-desktop-3-12 libgtk2-perl
  libguava-java libgweather-3-6 libhttp-parser2.7.1 libhunspell-1.6-0
  libicu-le-hb0 libicu60 libieee1284-3:i386 libisc166 libisccc160 libisccfg160
  libisl15 libjaxp1.3-java libjbigi-jni libjemalloc1 libjetty9-java
  libjs-excanvas libjs-jquery-form libjs-openlayers libjson-simple-java
  libjsp-api-java libjsr305-java liblouis14 liblvm2app2.2 liblvm2cmd2.02
  liblwgeom-2.4-0 liblwgeom-2.5-0 liblwgeom-dev liblwres160
  libmagickcore-6.q16-3 libmagickcore-6.q16-3-extra libmagickwand-6.q16-3
  libmariadb3:i386
  libmono-system-runtime-interopservices-runtimeinformation4.0-cil
  libmozjs185-1.0 libmpfr4 libmutter-1-0 libnfs8 libnghttp2-14:i386
  libnm-glib4 libnm-gtk0 libnm-util2 libntfs-3g88 libopenexr22 libpango-perl
  libpci3:i386 libperl5.26 libperl5.28:i386 libpoppler68 libpoppler72
  libpostproc54 libproj12 libprotobuf-lite10 libprotobuf10 libpsl5:i386
  libpyside-py3-1.2 libpython3.6 libpython3.6-dev libpython3.6-minimal
  libpython3.6-stdlib libqca2 libqca2-plugins libqgis-analysis2.18.28
  libqgis-core2.14.21 libqgis-core2.18.28 libqgis-customwidgets
  libqgis-gui2.14.21 libqgis-gui2.18.28 libqgis-networkanalysis2.14.21
  libqgis-networkanalysis2.18.28 libqgis-server2.18.28 libqgispython2.14.21
  libqgispython2.18.28 libqwt5-qt4 libqwt6abi1 libradare2-2.1 librtmp1:i386
  libruby2.3 libsane:i386 libsctp1 libservice-wrapper-java
  libservice-wrapper-jni libservlet-api-java libservlet3.1-java libsfcgal1
  libshiboken-py3-1.2v5 libsmali-java libsmbios-c2 libsnmp30:i386
  libspatialindex4v5 libssh2-1:i386 libstringtemplate-java libswscale4
  libsynctex1 libtaglibs-standard-impl-java libtaglibs-standard-jstlel-java
  libtaglibs-standard-spec-java libtcl8.5 libtelepathy-glib0 libtk8.5
  libtomcat9-java libwayland-egl1-mesa libwebsocket-api-java libwinpr-crt0.1
  libwinpr-crypto0.1 libwinpr-dsparse0.1 libwinpr-environment0.1
  libwinpr-file0.1 libwinpr-handle0.1 libwinpr-heap0.1 libwinpr-input0.1
  libwinpr-interlocked0.1 libwinpr-library0.1 libwinpr-path0.1
  libwinpr-pool0.1 libwinpr-registry0.1 libwinpr-rpc0.1 libwinpr-sspi0.1
  libwinpr-synch0.1 libwinpr-sysinfo0.1 libwinpr-thread0.1 libwinpr-utils0.1
  libwireshark10 libwiretap7 libwscodecs1 libwsutil8 libxfont1 libxmlunit-java
  libxpp3-java libyaml-snake-java libzeitgeist-2.0-0 openjdk-8-jdk
  openjdk-8-jdk-headless php7.0-mysql python-anyjson
  python-backports.ssl-match-hostname python-capstone python-couchdbkit
  python-functools32 python-http-parser python-httpretty python-imaging
  python-pam python-ply python-pycryptodome python-pysmi python-pysnmp4
  python-pysnmp4-apps python-pysnmp4-mibs python-pyspatialite python-qgis
  python-qgis-common python-qt4-sql python-restkit python-shapely
  python-socketpool python3-argcomplete python3-argh python3-construct
  python3-cssutils python3-editorconfig python3-feedparser python3-flask
  python3-html2text python3-itsdangerous python3-jsbeautifier python3-jwt
  python3-pathtools python3-prettytable python3-pyinotify python3-simplejson
  python3-watchdog python3-werkzeug python3.6 python3.6-dev python3.6-minimal
  qt4-designer ruby-faraday ruby-terminal-table ruby-unicode-display-width
  ruby2.3 secure-delete service-wrapper smitools tk8.5 vino zeitgeist-core
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 317 not upgraded.

**Comment by podkilla** [comment]
you are missing the python module.

install via pip:
sudo pip install gpg
