### ISSUE TITLE
Updating the Tor project key

### ISSUE THREAD

**Issue by sm0rux** [micahflee/torbrowser-launcher#400]
Hi,

As the Tor project key has been infect by approx. 100000 signatures it now takes about 6 minutes to start Tor Browser when installed using torbrowser-launcher.

BR,

Pontus

**Comment by oskarddfa** [comment]
Here is a comment about the whole infection problem. 
https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f

An option would be to use the keyserver hkps://keys.openpgp.org instead of the old sks server?

**Comment by arvidjaar** [comment]
> it now takes about 6 minutes to start Tor Browser

Well, my `gpg --refresh-keys` is still grinding for over 28 minutes ...

**Comment by l0b0** [comment]
Shouldn't this be ultra-high priority? People are unable to use the official key using the recommended method.

**Comment by micahflee** [comment]
Fixed in #401
