### ISSUE TITLE
Unable to start tor browser - gpg hangs refreshing keys (possible key servers DoS)

### ISSUE THREAD

**Issue by arvidjaar** [micahflee/torbrowser-launcher#401]
See https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f

What I have now looks very much like it:

```
UID        PID  PPID  C STIME TTY          TIME CMD
bor      31474 31391 97 06:30 ?        00:13:46 /usr/bin/gpg --status-fd 2 --homedir /home/bor/.local/share/torbrowser/gnupg_homedir --keyserver hkps://hkps.pool.sks-keyservers.net --keyserver-options ca-cert-file /usr/share/torbrowser-launcher/sks-keyservers.netCA.pem include-revoked no-honor-keyserver-url no-honor-pka-record --refresh-keys
```

Yes, 13 **minutes** processing time!!!

Please make key server configurable to allow mitigation.

**Comment by momo42** [comment]
I have the exact same problem. At first I thought that Tor browser is not starting at all but ~15 minutes later it finally popped up. Then I realized that the launcher triggers the problem. On my machine gpg runs with 100% load on one core before launcher window appears. OS is Linux Mint 19.1 and Tor Browser has been installed via `sudo apt install torbrowser-launcher`.
Please fix that. :-)

**Comment by maieul** [comment]
same problem

**Comment by baptx** [comment]
The workaround I used is to kill all GPG processes with the command `killall gpg`, then Tor Browser started and I could use it.
But isn't this workaround removing the following security feature?
`Verifies Tor Browser's signature for you, to ensure the version you downloaded was cryptographically signed by Tor developers and was not tampered with`
Then it would be considered a security vulnerability that we can start Tor Browser just by killing GPG, users should not be able to disable a security feature without giving an explicit permission (e.g. through a command parameter --disable-gpg) and a warning should be displayed when the browser starts.

This issue looks similar to a previous one: https://github.com/micahflee/torbrowser-launcher/issues/305
Here is a cleaner workaround: `~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/start-tor-browser`.

**Comment by Argentino84** [comment]
Same problem and the suggested workaround doesn't work for me. After killing gpg I only can choose to download everything again or close.

**Comment by P9at4Kic** [comment]
this may not be an issue with tor but an attack on OpenPGP 

https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f

**Comment by Wikinaut** [comment]
@micahflee thanks for swift reaction and fix (confirmed: works).

**Comment by dephekt** [comment]
People using the Ubuntu 18.04 LTS release version of this can do a oneliner to delete the bad key and a small hack to make torbrowser-launcher not hang on the key refresh.

This will delete the offending key you received from hkps.pool.sks-keyservers.net:
`gpg --homedir ~/.local/share/torbrowser/gnupg_homedir --delete-keys torbrowser@torproject.org`

Then you can manually edit your locally installed torbrowser-launcher to use keys.openpgp.org as seen in #402 by editing `/usr/lib/python2.7/dist-packages/torbrowser_launcher/common.py` line 220 and change `hkps://hkps.pool.sks-keyservers.net` to `hkps://keys.openpgp.org`.

Then start torbrowser-launcher like usual and it will get an uncorrupted key and things will keep working. It's just a way to workaround the issue until Ubuntu releases a fixed version downstream.

**Comment by matt3o** [comment]
> gpg --homedir ~/.local/share/torbrowser/gnupg_homedir --delete-keys torbrowser@torproject.org

This stalls forever on my machine on 100% cpu usage. 

For me a different quote in another bug report (#356) helped: 

> Running rm -r ~/.config/torbrowser ~/.cache/torbrowser ~/.local/share/torbrowser before trying to reinstall has solved my problem.

Fixed it for me.

**Comment by MaxXor** [comment]
Can you release an update of torbrowser-launcher which includes the fix with the new key server? It's too inconvenient having to edit this line by hand to make it work on any fresh install for new users.

**Comment by wizball1087** [comment]
Thanks dephekt:

The workaround worked great for me also, the problem has been bugging me for days.

**Comment by magusvox** [comment]
im new on linux, but this has some hacker attack or i misundestood something?

**Comment by mark-orion** [comment]
I have the same problem (Ubuntu 18.04 LTS). Personally I don't mind editing things but please provide a fix for this ASAP - just for the sake of ease of use and to make TOR user friendly.

**Comment by SantiAcevedo** [comment]
I'm running the Ubuntu 18.04 version and after changing the keyserver I'm getting a GENERIC_VERIFY_FAIL error.

**Comment by dafeder** [comment]
Same - had this problem on 18.04, @dephekt fix worked

**Comment by dafeder** [comment]
I tried this fix and get farther now, in startup, but get a dialog with `GENERIC_VERIFY_FAIL` error.

**Comment by noloader** [comment]
Add a "mee too" for Ubuntu 18.04.03 x86_64 (fully patched).

I can't seem to get beyond this failure. It has been going on 6 months to a year:

![Screenshot from 2019-12-18 15-27-08](https://user-images.githubusercontent.com/3538226/73025802-3fd2f980-3dfe-11ea-950e-5550e82d34db.png)

Why can't Tor and Ubuntu get this to work?

**Comment by hvek** [comment]
I also have the same issue with 18.04.03

**Comment by lucidyan** [comment]
For those who will experience this behavior on Ubuntu 18.04 - you should install newer version by adding ppa:
```
sudo add-apt-repository ppa:micahflee/ppa
sudo apt install torbrowser-launcher
```

Source:
https://github.com/micahflee/torbrowser-launcher/issues/410#issuecomment-520294348

**Comment by maksliman** [comment]
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
4.15.0-74-generic GNU/Linux

https://github.com/micahflee/torbrowser-launcher
Refreshing local keyring...

and still not working

**Comment by bansheetk23** [comment]
Adding ppa worked for me. Thanx

**Comment by baptx** [comment]
This problem is still present in Ubuntu 19.10. Adding PPA and reinstalling Tor browser did not fix the issue for me.

**Comment by guglielmogcg** [comment]
```
sudo apt-get purge tor torbrowser-launcher
rm -r ~/.config/torbrowser ~/.cache/torbrowser ~/.local/share/torbrowser
```
then add the ppa and sudo apt ```install torbrowser-launcher```

Worked for me, ubuntu 18.04

**Comment by serolrom** [comment]
> ```
> sudo apt-get purge tor torbrowser-launcher
> rm -r ~/.config/torbrowser ~/.cache/torbrowser ~/.local/share/torbrowser
> ```
> 
> then add the ppa and sudo apt `install torbrowser-launcher`
> 
> Worked for me, ubuntu 18.04

Confirming this works for me.
From a newbie at Linux, let me give you guys a big Thank you!

**Comment by syfran66** [comment]
I'm on Linux Mint 19.3 Tricia and it still doesn't work.
Need help please.
Thanks

**Comment by alexalex1024** [comment]
> ```
> sudo apt-get purge tor torbrowser-launcher
> rm -r ~/.config/torbrowser ~/.cache/torbrowser ~/.local/share/torbrowser
> ```
> 
> then add the ppa and sudo apt `install torbrowser-launcher`
> 
> Worked for me, ubuntu 18.04

It work very well for me with Ubuntu 18.04. Before, all other online workarounds have failed! You save me!

**Comment by comradekingu** [comment]
> ```
> sudo add-apt-repository ppa:micahflee/ppa
> sudo apt install torbrowser-launcher
> ```
run a "sudo apt update" between those to find the new package.

**Comment by ktuulos** [comment]
Hmm, the above mentioned ppa does not work in my Ubuntu 18.04.04 computer. When I enabled the ppa and tried to install onionshare, I got following error message:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 onionshare : Depends: python3-flask-httpauth but it is not installable
E: Unable to correct problems, you have held broken packages.
```

True, there is no python3-flask-httpauth in Bionic. What now?

**Comment by avimanyu786** [comment]
> Hmm, the above mentioned ppa does not work in my Ubuntu 18.04.04 computer. When I enabled the ppa and tried to install onionshare, I got following error message:
> 
> ```
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  onionshare : Depends: python3-flask-httpauth but it is not installable
> E: Unable to correct problems, you have held broken packages.
> ```
> 
> True, there is no python3-flask-httpauth in Bionic. What now?

I manually installed the [Focal package](https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/python3-flask-httpauth_3.2.4-3.1_all.deb.html) on Bionic and then was able to install `onionshare` successfully.

**Comment by dhanesh-vishwakarma-a6** [comment]
I'm a 20.04 user. 
Didn't worked for me...
