### ISSUE TITLE
SIGNATURE VERIFICATION FAILED! 

### ISSUE THREAD

**Issue by matswes** [micahflee/torbrowser-launcher#410]
When I run torbrowser-launcher I get a warning:
** (torbrowser-launcher:2799): WARNING **: 09:51:20.429: AT-SPI: Could not obtain desktop path or name
and finally error message: 
SIGNATURE VERIFIKATION FAILED
Error Code: GENERIC_VERIFY_FAILED

I have run:

gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu

and get 

gpg: refreshing 1 key from hkp://pgp.mit.edu
gpg: keyserver refresh failed: Server indicated a failure

I also tried the same with servers pool.sks-keyservers.net and keyserver.ubuntu.com with the same result.

**Comment by Riezebos** [comment]
Which version are you using? I had the same error on Ubuntu but was apparently using an old version (0.2.9), installing the newest version solved it for me!

**Comment by matswes** [comment]
Thankyou! That helped. I thought I had the latest version.

This lines fixed it:

sudo add-apt-repository ppa:micahflee/ppa
sudo apt install torbrowser-launcher

**Comment by NewIncome** [comment]
Awesome @matswes !! Thanks man!!

**Comment by baaridunnasr** [comment]
Thanks @Riezebos! That cleared up everything!!

**Comment by BlackCatte** [comment]
I'm still getting this, despite doing everything mentioned in this thread :/

**Comment by baaridunnasr** [comment]
> 
> 
> I'm still getting this, despite doing everything mentioned in this thread :/

Make sure you purge while removing the older version of Tor. And remove any offending keys. Refer #401 for procedures.

**Comment by DMrFrost** [comment]
The ppa:micahflee/ppa repository solved my problem.

**Comment by booxdk** [comment]
sudo add-apt-repository ppa:micahflee/ppa
sudo apt install torbrowser-launcher

Worked for me, remember to apt update after adding the ppa 👍
