### ISSUE TITLE
First run on Mint 19.2: SIGNATURE VERIFICATION FAILED

### ISSUE THREAD

**Issue by st1944hu** [micahflee/torbrowser-launcher#430]
Tried twice with same result.
![torerr](https://user-images.githubusercontent.com/12700677/65554231-ca056280-dedd-11e9-8efc-8e6d7326a076.png)

**Comment by twjang** [comment]
Following command will fix your problem. 
```
gpg --auto-key-locate nodefault,wkd --homedir ~/.local/share/torbrowser/gnupg_homedir --locate-keys torbrowser@torproject.org
```

**Comment by st1944hu** [comment]
Many thanks. That worked perfectly.

**Comment by dpalmajr** [comment]
How would i resolve this same issue for Ubuntu 18?
