### ISSUE TITLE
GENERIC_VERIFY_FAIL on first use (Acer Aspire, Ubuntu 18.04.3)

### ISSUE THREAD

**Issue by Exsul1** [micahflee/torbrowser-launcher#431]
I keep getting this error when I try to launch the Tor Browser for the first time on my Acer Aspire, Ubuntu 18.04.3.  Clicking Start doesn't help.

```
SIGNATURE VERIFICATION FAILED! 

Error Code: GENERIC_VERIFY_FAIL 

You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key. Click Start to refresh the keyring and try again. If the message persists report he above error code here: github.com/micahflee/torbrowser-launcher/issues
```

**Comment by Dave3991** [comment]
same here - thinkpad t480

**Comment by Matv1989** [comment]
same lenovo ideapad 360s

**Comment by ilyesAj** [comment]
same as here "Ubuntu 18.04.3 LTS"

**Comment by Dave3991** [comment]
this helped me guys :) 
https://askubuntu.com/a/1050404

**Comment by noloader** [comment]
Add a "mee too" for Ubuntu 18.04.03 x86_64 (fully patched).

I can't seem to get beyond this failure. It has been going on 6 months to a year:

![Screenshot from 2019-12-18 15-27-08](https://user-images.githubusercontent.com/3538226/73025802-3fd2f980-3dfe-11ea-950e-5550e82d34db.png)

Why can't Tor and Ubuntu get this to work?

**Comment by vianin** [comment]
I am facing the same issue.

Ubuntu 18.04 / Lenovo

**Comment by vianin** [comment]
> this helped me guys :)
> https://askubuntu.com/a/1050404

Thanks, this helped.
