### ISSUE TITLE
Error Code: GENERIC_VERIFY_FAIL

### ISSUE THREAD

**Issue by ssem1aB** [micahflee/torbrowser-launcher#437]
In Ubuntu-18.04.3 Tor Browser will install.  However, the verification key will not download.  So, Tor can not run...or browse.  Any method of acquiring the key will be an asset.  Please give generously.

**Comment by cransono** [comment]
Confirmed. Fixed my problem as well

**Comment by noloader** [comment]
Add a "mee too" for Ubuntu 18.04.03 x86_64 (fully patched).

I can't seem to get beyond this failure. It has been going on 6 months to a year:

![Screenshot from 2019-12-18 15-27-08](https://user-images.githubusercontent.com/3538226/73025802-3fd2f980-3dfe-11ea-950e-5550e82d34db.png)

Why can't Tor and Ubuntu get this to work?
