### ISSUE TITLE
V9.x on Debian Sid results in black screen

### ISSUE THREAD

**Issue by vsatmydynipnet** [micahflee/torbrowser-launcher#443]
Since V9 .x update on Sid i get a black screen after starting Tor Browser. Very annoying, not Tor browser on all boxes meanwhile. Thank you for your help

**Comment by shirishag75** [comment]
happened on my end too, I was able to see #942901 on the Debian bts and I followed the workaround and it worked. It has been integrated by upstream, we are probably going to have to either use the workaround provided or wait for a new release of torbrowser-launcher. 

Either way it works. 

https://github.com/micahflee/torbrowser-launcher/commits/develop

**Comment by freezed** [comment]
This issue is on Debian Stable/Buster too.

[Bug link](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942901) on Debian BTS

**Comment by shirishag75** [comment]
The workaround given by Paul Wise works, I tried and used it perfectly :)
