### ISSUE TITLE
Signature Verification Failed

### ISSUE THREAD

**Issue by tienhing** [micahflee/torbrowser-launcher#447]
Error code: EB774491D9FF06E2

**Comment by hapibeli** [comment]
apt install tor
[sudo] password for dirk:         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tor is already the newest version (0.4.2.5-1~bionic+1).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.

But on trying to start Tor, I have the same error.
