### ISSUE TITLE
SIGNATURE VERIFICATION FAILED!

### ISSUE THREAD

**Issue by apollosnyder** [micahflee/torbrowser-launcher#448]
Error code: GENERIC_VERIFY_FAIL

**Comment by Extarys** [comment]
Same error here. Linux Mint using repo `deb https://deb.torproject.org/torproject.org bionic main`

**Comment by saeed-basterd** [comment]
same error here. Linux mint

**Comment by OVNI67** [comment]
Same error here. Linux ubuntu 18.04

**Comment by OVNI67** [comment]
Over and over again trying to run torbrowser launcher, i get this error

**Comment by TheDealerMan** [comment]
Same.  System is up-to-date with 19.1 XFCE 64

**Comment by steve165** [comment]
Ditto - same failure and error code
tried multiple times over the last twelve hours

**Comment by arkadiyjs** [comment]
Same on Trisquel 8.0

**Comment by missfelicitas** [comment]
Same on Xubuntu 18.04

**Comment by Extarys** [comment]
I think the issue is now confirmed. We just need to wait for someone with time to investigate. :+1:

**Comment by jorgegx92** [comment]
Same on KDE neon

**Comment by werfive** [comment]
I have the same issue on Linux Mint:   GENERIC_VERIFY_FAIL     during signature verification.

**Comment by JGDev3** [comment]
SOLVED for me adding repositorie of Tor project, update and install deb.torproject.org-keyring package, then run Tor browser. Tested in KDE neon, It should work on ubuntu bionic and others OS

**Comment by VikOlliver** [comment]
It fails for me on a clean, upgraded install of 64-bit xubuntu-18.04-3 every time. So I ran "ps ax|grep pgp" at a strategic moment and found that torbrowser_launcher is using the following gpg command:

gpg --status-fd 2 --homedir /home/xubuntu/.local/share/torbrowser/gnupg_homedir --keyserver hkps://hkps.pool.sks-keyservers.net --keyserver-options ca-cert-file /usr/share/torbrowser-launcher/sks-keyservers.netCA.pem include-revoked no-honor-keyserver-url no-honor-pka-record --refresh-keys

If you run this from the command line, you get:

gpg: keyserver option 'ca-cert-file' is obsolete; please use 'hkp-cacert' in dirmngr.conf
gpg: Note: '--refresh-keys' is not considered an option
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
usage: gpg [options] [filename]

so it appears it's using an obsolete GnuPG option. My guess is that it'll spn for a while waiting for verification that never happens, and then time out. If you have a machine running (for whatever reason) GnuPG V1.x torbrowser_launcher will probably work, but I suspect not with updated distributions using GnuPG V2.x like mine :(

If yours works, please test with:
gpg --version

**Comment by noloader** [comment]
Add a "mee too" for Ubuntu 18.04.03 x86_64 (fully patched).

Why can't Tor and Ubuntu get this to work?

**Comment by JGDev3** [comment]
> It fails for me on a clean, upgraded install of 64-bit xubuntu-18.04-3 every time. So I ran "ps ax|grep pgp" at a strategic moment and found that torbrowser_launcher is using the following gpg command:
> 
> gpg --status-fd 2 --homedir /home/xubuntu/.local/share/torbrowser/gnupg_homedir --keyserver hkps://hkps.pool.sks-keyservers.net --keyserver-options ca-cert-file /usr/share/torbrowser-launcher/sks-keyservers.netCA.pem include-revoked no-honor-keyserver-url no-honor-pka-record --refresh-keys
> 
> If you run this from the command line, you get:
> 
> gpg: keyserver option 'ca-cert-file' is obsolete; please use 'hkp-cacert' in dirmngr.conf
> gpg: Note: '--refresh-keys' is not considered an option
> gpg: WARNING: no command supplied. Trying to guess what you mean ...
> usage: gpg [options] [filename]
> 
> so it appears it's using an obsolete GnuPG option. My guess is that it'll spn for a while waiting for verification that never happens, and then time out. If you have a machine running (for whatever reason) GnuPG V1.x torbrowser_launcher will probably work, but I suspect not with updated distributions using GnuPG V2.x like mine :(
> 
> If yours works, please test with:
> gpg --version

I think you just have to change something in the order like this:
gpg --status-fd 2 --homedir /home/xubuntu/.local/share/torbrowser/gnupg_homedir --keyserver hkps://hkps.pool.sks-keyservers.net --keyserver-options hkap-cert-file /usr/share/torbrowser-launcher/sks-keyservers.netCA.pem include-revoked no-honor-keyserver-url no-honor-pka-record --refresh-keys

And take a look at the order '--refresh-keys'

My problem seems to be due to a dirname, but yours i think it is something wrong with the arguments, but --refresh-keys seems to be a valid argument, so maybe try to download manually the key of the repo or the manual instructions instead of downloading it from repos, and delete before the previous installation. 
It solved the problem for me, and changing some dirnames, just download the default version en_EN, to avoid the dirname change.
It worked for me without downloading a new package (I use the repo's one)
https://2019.www.torproject.org/docs/tor-doc-unix.html.en
https://2019.www.torproject.org/docs/debian.html.en

**Comment by mabuimo** [comment]
Same problem in Linux Mint 19.3 Tricia

**Comment by Federkun** [comment]
Are you guys installing from the PPA?
https://github.com/micahflee/torbrowser-launcher#installing-from-the-ppa

**Comment by Extarys** [comment]
@Federkun I took another look at it. I removed the PPA, cleared cache, removed the older package I had. Re added the package and installed it using Flatpak. IT WORKS!

**Comment by VikOlliver** [comment]
So the PPA is broken? Is there someone who should be told?

**Comment by Extarys** [comment]
We should test in a VM with the PPA I think before trying to report anything. Maybe it's just some OSes/etc that makes it broken? I don't really know. If there is an issue, the PPA belongs to @micahflee so... their the one we should notify.

**Comment by TimesEnemy** [comment]
Ubuntu 18.04, this is what I get.  I can click the Start button over and over, for days, and I end up at the same error:

`SIGNATURE VERIFICATION FAILED!

Error Code: GENERIC_VERIFY_FAIL

You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key.
Click Start to refresh the keyring and try again.  If the message persists report the above error code here:
https://github.com/micahflee/torbrowser-launcher/issues`

BTW, when I click the Cancel button, the terminal outputs the following, which is a bit confusing:

`Keyring refreshed successfully...`

So, let's see, am I under attack?  Possible, but unlikely, let's check other systems.  No, I do not appear to be under attack.

Is there a network problem?  Well, this is more difficult to answer, as I am unaware, or ignorant of the actual network devices TorBrowser would consider it's network.  But, I am able to reach all other systems that I should be able to reach via the internet tubes.  So, let's check this off as most likely not the issue, for now.  Maybe toss this into memory.

Am i missing a recently added TorBrowser verification key?  Well, I saw a few different instances of when to do this, which vary slightly as to their purpose.  So, I am going to go with updating my existing install, and/or prepping to uninstall reinstall.

Tried various steps, to no avail.  Ditching the Ubuntu repository version ... which worked like a charm.

**Comment by DougInAMug** [comment]
I had the same issue. I checked my torbrowser-launcher version which was v0.2.9 (i.e. 2 year old.) I checked to see what tor related packages I had installed...

`$ apt search '\<tor\>' | grep 'installed'`

... and purged them. In my case:

`$ sudo apt-get purge tor tor-geoipdb torsocks`

... after which I re-followed the [Installing from the PPA](https://github.com/micahflee/torbrowser-launcher#installing-from-the-ppa) and now everything is working fine.

**Comment by aitaix** [comment]
same

**Comment by OtterGauze** [comment]
I'm getting this issue on Manjaro 20.1, installing Tor directly from the official repositories.

**Comment by myxit** [comment]
Same here, guys. 
it is wired, why it does not work?
solution kindly suggested by @DougInAMug did not work.

Appreciate if someone can share a  workaround..
(Linux Mint 19.3 ubuntu based)

**Comment by AwakeningProgrammer** [comment]
Problem solved!

$sudo apt install torbrowser-launcher

Thank me later :)
