### ISSUE TITLE
signature verification failed: generic_verify_fail

### ISSUE THREAD

**Issue by dingerjunkie** [micahflee/torbrowser-launcher#455]
OS: Ubuntu 18.04.4 LTS
GNOME: 3.28.2
likely repeat of other reported issues.

**Comment by hasenbalg** [comment]
have a look here: [#454](https://github.com/micahflee/torbrowser-launcher/issues/454). this worked for me

**Comment by nathanfranke** [comment]
Fixed, please see https://github.com/micahflee/torbrowser-launcher/pull/526
