### ISSUE TITLE
Tor Browser: SIGNATURE VERIFICATION FAILED!

### ISSUE THREAD

**Issue by bladewheels** [micahflee/torbrowser-launcher#458]
![Screenshot from 2020-04-05 13-16-54](https://user-images.githubusercontent.com/913762/78507872-20324880-7740-11ea-9a25-90ad71227579.png)

Tried clicking 'Start' but ended up with the same notification when all was said & done.

**Comment by Najoj** [comment]
I just got this message too. Tried multiple times.

**Comment by teknowiztx** [comment]
Getting the same exact thing.  Have restarted machine as well as process multiple times, same result.

**Comment by Kukuster** [comment]
Same story
Tried:
`gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu`
`gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir" --refresh-keys --keyserver keyserver.ubuntu.com`
`gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290`

with no success (in terms of solving the issue)

**Comment by seniorxy** [comment]
Having the same error on Ubuntu on two machines

**Comment by schildbach** [comment]
I've got the same issue.

**Comment by gndl00p** [comment]
Same issue Ubuntu 18.04.4 LTS

**Comment by SCBuergel** [comment]
Also on Ubuntu 18.04.4, reboot did NOT resolve the issue.

**Comment by hewonen** [comment]
Here's the command it runs to refresh the keyring:

`/usr/bin/gpg --status-fd 2 --homedir /home/user/.local/share/torbrowser/gnupg_homedir --refresh-keys --keyserver hkps://hkps.pool.sks-keyservers.net --keyserver-options ca-cert-file /usr/share/torbrowser-launcher/sks-keyservers.netCA.pem include-revoked no-honor-keyserver-url no-honor-pka-record`

Here is the response it gives when run manually:

`gpg: keyserver option 'ca-cert-file' is obsolete; please use 'hkp-cacert' in dirmngr.conf
gpg: Note: '--refresh-keys' is not considered an option
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
usage: gpg [options] [filename]`

Move the `--refresh-keys` to an earlier position in the command and you only get:

`gpg: keyserver option 'ca-cert-file' is obsolete; please use 'hkp-cacert' in dirmngr.conf`

From running the actual launcher I just get a repeated `GENERIC_VERIFY_FAIL`. This is an up to date Ubuntu 18.04.

I fixed it by adding the PPA (and then removing and installing):

`sudo add-apt-repository ppa:micahflee/ppa`

**Comment by SCBuergel** [comment]
Thank you @hewonen - that worked for me!

In summary I did the following

```
sudo add-apt-repository ppa:micahflee/ppa
sudo apt install torbrowser-launcher
torbrowser-launcher
```
This would install the Tor Browser and this time signature verification worked.

**Comment by seniorxy** [comment]
cheers guys

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by padraig-jm** [comment]
I had a similar problem using Peppermint 10.
![Screenshot_2020-04-23_21-21-56](https://user-images.githubusercontent.com/64037582/80291632-4898db80-871d-11ea-9a63-9371f859a7ff.png)

**Comment by alexnemesis** [comment]
> I had a similar problem using Peppermint 10.
> ![Screenshot_2020-04-23_21-21-56](https://user-images.githubusercontent.com/64037582/80291632-4898db80-871d-11ea-9a63-9371f859a7ff.png)

First remove your torbrowser-launcher, why from ppa repository is discontinued.

sudo apt remove torbrowser-launcher


install torbrowser-launcher in the following link
https://gist.github.com/alexnemesis/c4a5db10e62e6c4746eeeabd008998b7
