### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by AsciiWolf** [micahflee/torbrowser-launcher#459]
Please, consider making a new release (tag) of torbrowser-launcher. The latest master contains many important fixes since the last release. For example the [AppData file fix](https://github.com/micahflee/torbrowser-launcher/commit/887bd24bc4ca4b0bbaf757534a343c24341a98b0) that prevents the package from being broken in many GUI application centers like GNOME Software or KDE Discover.

/cc @micahflee

**Comment by AsciiWolf** [comment]
Any update here? :-)

**Comment by micahflee** [comment]
Made one! #528 528
