### ISSUE TITLE
Incorrectly detecting the language to start

### ISSUE THREAD

**Issue by yookoala** [micahflee/torbrowser-launcher#463]
Hello. My system language is zh_HK. Since there is no zh_HK locale, it falls back to zh_CN, which is the default zh language due to political power difference.

Both Taiwan and Hong Kong are mainly using Traditional Chinese (zh-hant) for daily lives and business. So for Hong Kong users, the natural fallback for zh_HK would be zh_TW instead of zh_CN. Is it possible to change the launcher to add this behaviour instead of the default one?

**Comment by rogers0** [comment]
@yookoala 

I uploaded 0.3.2-10 to debian, and included your patches.
- https://tracker.debian.org/news/1122382/accepted-torbrowser-launcher-032-10-source-into-unstable/

If you use debian, you can install it from backports.
- https://wiki.debian.org/TorBrowser#Debian_10_.22Buster.22
