### ISSUE TITLE
tor browser error code GENERIC_VERIFY_FAIL

### ISSUE THREAD

**Issue by BradDeA** [micahflee/torbrowser-launcher#474]
I am trying to run tor browser on elementary OS

**Comment by setuidroot** [comment]
@BradDeA I applaud you for not using Windows (as it's spyware in of itself.)  Elementary OS is nice and simple.

But as much as I want to help you... I can't without some idea of the problem.

Logs?  Crashes?  What?

I'll get on TeamViewer and set it up for you if you'd like... but you'd be trusting that I wouldn't do anything malicious (and you have my word on that) but you shouldn't usually trust random people online.

I want to help you hoping you'll switch to Linux and tell your friends Linux does everything Windows can do and more lol.

**Comment by BradDeA** [comment]
@setuidroot Well my first problem is it takes forever to launch, or does not launch at all, though that could be due to my laptop just being slow, I am unsure of that. It opens multiple processes called "gpg" witch causes my computer to almost max the CPU and tor wont start doing anything until I end one of the "gpg" processes. If it does launch it goes through first time install, but then freezes at the verifying signature part. Then it crashes and gives me this error ( see photo I've attached ). If I hit start to try again I just get this error over and over. i usually have to resort to ending all the "gpg" that pop up in my system monitor to get it to close entirely as it creates more of these in my system monitor as its trying to launch.
![Screenshot from 2020-06-02 11-36-33](https://user-images.githubusercontent.com/65321477/83541460-ac09ec00-a4c7-11ea-8723-54c2d64be5cd.png)

**Comment by pmq96** [comment]
Hi I have the same problem on Elementary OS, I also tried:

`gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir" --refresh-keys --keyserver keyserver.ubuntu.com`

But I got "connection refused", also changing the keyserver

**Comment by tintin67** [comment]
Hello, i am having the same problem on linux mint 19.3 xfce.

![Screenshot_2020-06-03_13-01-56](https://user-images.githubusercontent.com/39829676/83629498-7da91100-a59a-11ea-89bf-8b2d00667b86.png)

**Comment by pmq96** [comment]
I found the solution:

-Download TOR from here: https://www.torproject.org/download/

-Go in the directory, then through terminal write: tar -xvfz *file.tar*

-Then start the process from that folder with ./

The only method that worked for me. I tried everything I found on the web, also installing from repo or “AppStore” but nothing worked.
