### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by MaheepChaudhary** [micahflee/torbrowser-launcher#476]
Error_Code: GENERIC_VERIFY_FAIL

**Comment by antechrestos** [comment]
Same here

**Comment by antechrestos** [comment]
@MaheepChaudhary I had the same behaviour while using the one in official ubuntu repo.

Following the [installation guide](https://github.com/micahflee/torbrowser-launcher#installing-from-the-ppa) fixed the issue. I guess version in official repo is obsolete.

**Comment by MaheepChaudhary** [comment]
Thank you

**Comment by ganou2007** [comment]
Try to install Torbrowser, but I got:
SIGNATURE VERIFICATION FAILED!
Error Code:GENERIC_VERIFY_FAIL
You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key. Click Start to refresh the keyring and try again. If the message persists report the above error here:

I tried several times, but got the same failed message as above.
OS: Ubuntu 18.04.4

**Comment by ganou2007** [comment]
Based on antechrestos's link fixed the issue.
