### ISSUE TITLE
Signature Verification Failed

### ISSUE THREAD

**Issue by jdubblu** [micahflee/torbrowser-launcher#477]
GENERIC_VERIFY_FAIL

Related? Firefox suddenly noting my "...browser is being managed by your organization", but this is my own machine (Ubuntu 18.04) unrelated to others; also, it takes noticeably longer longer to load pages now -- especially news-related sites. fyi

**Comment by jdubblu** [comment]
Thunk to read the earlier posts on this issue and now resolved.

**Comment by ganou2007** [comment]
Try to install Torbrowser, but I got:
SIGNATURE VERIFICATION FAILED!
Error Code:GENERIC_VERIFY_FAIL
You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key. Click Start to refresh the keyring and try again. If the message persists report the above error here:

I tried several times, but got the same failed message as above. 
OS: Ubuntu 18.04.4
