### ISSUE TITLE
Update Tor Browser Signing Key

### ISSUE THREAD

**Issue by sysrqb** [micahflee/torbrowser-launcher#481]
The expiration dates were extended.

**Comment by sysrqb** [comment]
https://lists.torproject.org/pipermail/tbb-dev/2020-July/001123.html

**Comment by Toadfield** [comment]
how can I use that key?

**Comment by 10101000** [comment]
> how can I use that key?

You can either download the updated public key directly from [torproject.org](https://lists.torproject.org/pipermail/tbb-dev/attachments/20200722/82030b51/attachment-0001.key) (the old key format) or you can download @sysrqb's [version](https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc) (new keyring format) and replace tor-browser-developers.asc. The location is probably package dependent, in my case this is `/usr/share/torbrowser-launcher/tor-browser-developers.asc`.

**Comment by nathanfranke** [comment]
`wget https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc`
`sudo mv tor-browser-developers.asc /usr/share/torbrowser-launcher/`
