### ISSUE TITLE
signature verification failed

### ISSUE THREAD

**Issue by DasX** [micahflee/torbrowser-launcher#485]
Bug: signature verification failed

Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2

OS: Kali Linux WSL 2 / Windows 2004

Already tried to refresh keys etc.

**Comment by teixeira-de-sousa** [comment]
I've got exactly the same error, but on Arch Linux

**Comment by skymoo** [comment]
Same on Fedora

**Comment by nathanfranke** [comment]
Related to #481

**Comment by fabio-blanco** [comment]
Same on Ubuntu 18.04

**Comment by maxine2604** [comment]
I get the same error code on Ubuntu 20.04

**Comment by foudary** [comment]
Same error happening on OpenSUSE Tumbleweed.

**Comment by spectra122** [comment]
On Debian 10 buster the same problem

**Comment by Zakgeki** [comment]
Same issue on Manjaro.

**Comment by spectra122** [comment]
SIGNATURE VARIFICATION FAILED 
Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2 : Key expired
You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key.

A copy of the Tor Browser files you downloaded have been saved here:
[ path where the file is saved tar.xz.verification_failed and tar.xz.asc.verification_failed] 

Click START to refresh the keyring and try again

But even after trying again the same

**Comment by nathanfranke** [comment]
Can we please stop bumping this? Yes. We are all getting the same issue. Use the 👍 reaction.

**Comment by 10101000** [comment]
If you're unwilling to wait you can [update tor-browser-developers.asc manually](https://github.com/micahflee/torbrowser-launcher/issues/481#issuecomment-681585974).

**Comment by vaevictis12** [comment]
bump

**Comment by debajit** [comment]
This fixed the issue for me https://github.com/micahflee/torbrowser-launcher/issues/481#issuecomment-681585974

**Comment by Parasolka93** [comment]
SIGNATURE VARIFICATION FAILED
Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2 : Key expired
You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key.
A copy of the Tor Browser files you downloaded have been saved here:
/home/user/.var/app/com.github.micahflee.torbrowser-launcher/cache/torbrowser/download/tor-browser-linux64-9.5.4_ru.tar.xz failed
/home/user/.var/app/com.github.micahflee.torbrowser-launcher/cache/torbrowser/download/tor-browser-linux64-9.5.4_ru.tar.xz.verification_failed failed
Click START to refresh the keyring and try again

without any success  after restarting

**Comment by jony0008** [comment]
On Debian bullseye the same problem

**Comment by Robbiexd** [comment]
same issue on debian 10 buster and pop os 20.04

**Comment by Parasolka93** [comment]
> Grab Key. Put it into Tor-Browser Launcher's folder.
> 
> wget -v 'https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc' ; sudo cp -v ~/tor-browser-developers.asc /usr/share/torbrowser-launcher/ ; torbrowser-launcher ; echo "DONE"
> 
> This will replace the Key(old/expired) of the same name in there. Everything works now. Don't forget to thumbs up. thx

Tanks, it's working

**Comment by AsciiWolf** [comment]
@micahflee Would it be possible to release a new torbrowser-launcher version with this issue fixed?

**Comment by isingomaLinu** [comment]
> > Grab Key. Put it into Tor-Browser Launcher's folder.
> > wget -v 'https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc' ; sudo cp -v ~/tor-browser-developers.asc /usr/share/torbrowser-launcher/ ; torbrowser-launcher ; echo "DONE"
> > This will replace the Key(old/expired) of the same name in there. Everything works now. Don't forget to thumbs up. thx
> 
> Tanks, it's working

worked fine for mint 19.3

**Comment by anmarko** [comment]
Sorry, it isn't working on Ubuntu 20.04 
Error message during installation:
"The version of Tor Browser you have installed is earlier than it should be, which could be a sign of an attack!"
Installation on hold

**Comment by AsciiWolf** [comment]
@anmarko That is a different issue, see #498.

**Comment by paulrajib** [comment]
For Ubuntu 18.04, the command
"~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/start-tor-browser --verbose" execute/run the browser fine but I am trying to put it in the start-tor-browser.desktop file
sudo nano /home/raj/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
replacing "--detach" with "--verbose" 
and then trying to start from the app icon but doesn't work :( .
It starts the tor launcher and try to update again though the version is 10.0
and also replace the "--verbose" with "--detach" by itself
and then shows
"The version of Tor Browser you have installed is earlier than it should be, which could be a sign of an attack!"
again.
:(

**Comment by nathanfranke** [comment]
@paulrajib Works fine for me
This is my command
```
sh -c '"/home/nathanfranke/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/start-tor-browser" --verbose || ([ !  -x "/home/nathanfranke/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/start-tor-browser" ] && "$(dirname "$*")"/Browser/start-tor-browser --verbose)' dummy %k
```

(Copied from `Exec` in the desktop file)

**Comment by anmarko** [comment]
Thanks  AsciiWolf !

I've done a new installation, it's really easy:
https://linuxconfig.org/how-to-install-tor-browser-in-ubuntu-18-04-bionic-beaver-linux
It works also for UBUNTU 20.04

Before deleting of the complete old TOR-directory I've only saved the bookmarks from the "bookmarks backup" folder

**Comment by ruzon82** [comment]
error code:110775B5D101FB36BC6C911BEB774491D9FF06E2: key expired

**Comment by ruzon82** [comment]
Помогите!error code:110775B5D101FB36BC6C911BEB774491D9FF06E2: key expired. Англиского не знаю,что делать?

**Comment by ruzon82** [comment]
Перезагружал, всё равно  error code:110775B5D101FB36BC6C911BEB774491D9FF06E2: key expired      o.s.linux64

**Comment by ruzon82** [comment]
Ответьте, пожалуйста,что мне надо сделать.

**Comment by Orphan-Crippler** [comment]
Been trying to install tor for about an hour now. Have tried all the public key refreshing suggestions and whatnot. Still getting the Key Expired failure. can some kind soul please help me.

**Comment by Winsgame** [comment]
└─$ ./start-tor-browser.desktop --register-app
zsh: segmentation fault  ./start-tor-browser.desktop --register-app
