### ISSUE TITLE
SIGNATURE VERIFICATION FAILED

### ISSUE THREAD

**Issue by bankingmy** [micahflee/torbrowser-launcher#487]
ERROR CODE: 10775B5D101FB36BC6C911BEB774491D9FF06E2 Key Expired

**Comment by DasX** [comment]
identical with #485

**Comment by henkvancann** [comment]
Got this too: SIGNATURE VERIFICATION FAILED. But a different error code in Ubuntu 18.04

error code: GENERIC_VERIFY_FAIL
