### ISSUE TITLE
Signature verification issue key expired

### ISSUE THREAD

**Issue by olgaVnyc** [micahflee/torbrowser-launcher#491]
But  as  I checked apt-key list there is no expired key. I tried to referesh-it did not work, I can't remove it either.

**Comment by Brigithubert** [comment]
Same here

**Comment by zerthimon** [comment]
same here
ubuntu 20.04, installed torbrowser-launcher from ubuntu official repo

**Comment by Renifer** [comment]
"SIGNATURE VERIFICATION FAILED"

"You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key."
"A copy of the Tor Browser files you downloaded have been saved"
"Click Start to refresh the keyring and try again.  if the message persists report the above error code"





I do not have networking problems.
I cannot install or use Tor Browser.

Operating System: Fedora 32
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.8.4-200.fc32.x86_64
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31.3 GiB of RAM

**Comment by randoclt** [comment]
Solution trouvée plus bas

wget -v 'https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc' ; sudo cp -v ~/tor-browser-developers.asc /usr/share/torbrowser-launcher/ ; torbrowser-launcher ; echo "DONE"

**Comment by vinyanalista** [comment]
openSUSE Leap 15.2 affected as well.

**Comment by bdmorin** [comment]
> Solution trouvée plus bas
> 
> wget -v 'https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc' ; sudo cp -v ~/tor-browser-developers.asc /usr/share/torbrowser-launcher/ ; torbrowser-launcher ; echo "DONE"

This command worked, however torbrowser still complains of expired keys.

**Comment by few-bits** [comment]
> Solution trouvée plus bas
> 
> wget -v 'https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc' ; sudo cp -v ~/tor-browser-developers.asc /usr/share/torbrowser-launcher/ ; torbrowser-launcher ; echo "DONE"

thanks a lot!

**Comment by sammothxc** [comment]
Kali Linux (2020-07-01) affected as well, fixed with solution from @randoclt

**Comment by archiecarrot123** [comment]
> Solution trouvée plus bas
> 
> wget -v 'https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc' ; sudo cp -v ~/tor-browser-developers.asc /usr/share/torbrowser-launcher/ ; torbrowser-launcher ; echo "DONE"

Works, might want to replace cp with mv?

**Comment by artforlife** [comment]
> Solution trouvée plus bas
> 
> wget -v 'https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc' ; sudo cp -v ~/tor-browser-developers.asc /usr/share/torbrowser-launcher/ ; torbrowser-launcher ; echo "DONE"

Did not work for me on Ubuntu 18.04 LTS.

**Comment by drzraf** [comment]
Alternative solution:
` curl -s https://openpgpkey.torproject.org/.well-known/openpgpkey/torproject.org/hu/kounek7zrdx745qydx6p59t9mqjpuhdf | gpg --import --homedir ~/.local/share/torbrowser/gnupg_homedir/ -`

**Comment by darkmac78** [comment]
> Alternative solution:
> ` curl -s https://openpgpkey.torproject.org/.well-known/openpgpkey/torproject.org/hu/kounek7zrdx745qydx6p59t9mqjpuhdf | gpg --import --homedir ~/.local/share/torbrowser/gnupg_homedir/ -`

Still got browser version is earlier than it should be....

**Comment by drzraf** [comment]
This second blocker comes from https://github.com/micahflee/torbrowser-launcher/pull/499 (you need to patch your .py by hand)

**Comment by biplabro** [comment]
> > Solution trouvée plus bas
> > wget -v 'https://github.com/sysrqb/torbrowser-launcher/raw/develop/share/torbrowser-launcher/tor-browser-developers.asc' ; sudo cp -v ~/tor-browser-developers.asc /usr/share/torbrowser-launcher/ ; torbrowser-launcher ; echo "DONE"
> 
> Did not work for me on Ubuntu 18.04 LTS.

same here.

**Comment by arvidjaar** [comment]
https://2019.www.torproject.org/docs/signing-keys.html.en
https://support.torproject.org/tbb/how-to-verify-signature/

```
gpg: key 4E2C6E8793298290: public key "Tor Browser Developers (signing key) <torbrowser@torproject.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
pub   rsa4096 2014-12-15 [C] [expires: 2020-08-24]
      EF6E286DDA85EA2A4BA7DE684E2C6E8793298290
uid           [ unknown] Tor Browser Developers (signing key) <torbrowser@torproject.org>
sub   rsa4096 2018-05-26 [S] [expires: 2020-09-12]
```

All keys are expired. It has nothing to do with launcher, it is tor project issue.

**Comment by darkmac78** [comment]
What worked for me was totally uninstalling the version that came with the distro and installing the version from the project website.

**Comment by BillDietrich** [comment]
No update on this ?  No one assigned ?  A lot of users are dead in the water because of this.  TB hasn't worked for me for a week now.  I'm on Ubuntu MATE 20.04
