### ISSUE TITLE
Signature verification error.

### ISSUE THREAD

**Issue by KingdomB** [micahflee/torbrowser-launcher#492]
Please note that I have a persistent signature verification error:

Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2:Key expired

[download.zip](https://github.com/micahflee/torbrowser-launcher/files/5178305/download.zip)

**Comment by arichter6** [comment]
Ditto here, on antiX 19.2

**Comment by alastair87** [comment]
I'm also seeing this with the flatpak on Mint 20.

**Comment by KingdomB** [comment]
> I'm also seeing this with the flatpak on Mint 20.

I'm running Mint 20 as well.

**Comment by CJones217** [comment]
same here. Using pamac on manjaro 20.0.3
