### ISSUE TITLE
SIGNATURE VERIFICATION FAILED!

### ISSUE THREAD

**Issue by muftidenk** [micahflee/torbrowser-launcher#495]
![error](https://user-images.githubusercontent.com/69018776/92339494-dde6ac00-f0cf-11ea-9161-be38ee562912.png)

**Comment by MiguelAngelVega** [comment]
Got the same problem, is there any solution?

**Comment by reynaldiaznan123** [comment]
Solution here https://community.parrotsec.org/t/signature-verification-failed-in-tor-browser-launcher/15170

To Parrot OS 4.10

**Comment by kartikynwa** [comment]
So is it because the asc file in the released package is now defunct? What should maintainers do for now? For Void, I can for example add a patch to change the included file and add a revision bump. But if a new release is made with the update file, it won't be necessary.
