### ISSUE TITLE
The solution for the maintainer and a better workaround for the signature verification error.

### ISSUE THREAD

**Issue by Ulfnic** [micahflee/torbrowser-launcher#496]
# Maintainer Solution

As solved on the Destination Linux forum by PatPlusLinux and I: https://discourse.destinationlinux.network/t/tor-browser-on-ubuntu-20-04-1/2629/11

The keys appear to be coming from keys.openpgp.org by the default. PatPlusLinux checked the source for torbrowser_launcher/common.py and at line 206:

`'--keyserver', 'hkps://keys.openpgp.org',`

When I run:
`gpg -v --homedir ~/.local/share/torbrowser/gnupg_homedir --keyserver keys.openpgp.org --recv-keys 0x4E2C6E8793298290`

**It gives error:** `new key but contains no user ID - skipped`

Of 3 alternative key servers I tried, all of them worked and allowed torbrowser-launcher launched Tor:
- keyserver.ubuntu.com
- pgp.mit.edu
- keys.gnupg.net

When PatPlusLinux built the .deb changing hkps://keys.openpgp.org for hkps://keyserver.ubuntu.com everything also worked so that's the fix.

# User Solution

**Note:** The following instructions are for Ubuntu 20 so the path `~/.local/share/torbrowser/gnupg_homedir/` may need to be changed to suit your distro. You also won't have this directory until you start the torbrowser-launcher for the first time.

### How to install torbrowser-launcher from scratch:
`sudo add-apt-repository ppa:micahflee/ppa`
`sudo apt update`
`sudo apt install torbrowser-launcher`
`torbrowser-launcher`
While torbrowser-launcher is downloading Tor, open another Terminal and install the correct key:
`gpg --homedir ~/.local/share/torbrowser/gnupg_homedir --keyserver keyserver.ubuntu.com --recv-keys 0x4E2C6E8793298290`
(Allow a few minutes for command to complete)

### How to fix a broken installation:
`gpg --homedir ~/.local/share/torbrowser/gnupg_homedir --delete-keys torbrowser@torproject.org`
`gpg --homedir ~/.local/share/torbrowser/gnupg_homedir --keyserver keyserver.ubuntu.com --recv-keys 0x4E2C6E8793298290`
(Allow a few minutes for command to complete)

# Resources

**0x4E2C6E8793298290 is the gpg key used for the Tor Browser:**
http://keys.gnupg.net/pks/lookup?search=0x4E2C6E8793298290&fingerprint=on&op=index

**Comment by littlediobolic** [comment]
Can confirm that deleting the keys that were currently imported in `~/.local/share/torbrowser/gnupg` and replacing them with the ones at _keyserver.ubuntu.com_ fixed my verification issues

**Comment by nunesgh** [comment]
I could not manage to successfully perform your suggested steps.

The `torbrowser-launcher` command finishes running much faster than the `gpg --homedir ~/.local/share/torbrowser/gnupg_homedir --keyserver keyserver.ubuntu.com --recv-keys 0x4E2C6E8793298290` command, so by the time Tor Browser Launcher starts the installation of the browser, the correct keys are not yet available and I receive the following warning:

> The version of Tor Browser you have installed is earlier than it should be, which could be a sign of an attack!

After this warning appears, the installation process gets stuck and does not complete, but Tor Browser Launcher assumes the browser is installed, even though it does not launch.

I have also tried to run your 'fix a broken installation' steps with no success.

**Comment by clarityandobscurity** [comment]
This happens:

```
# gpg --homedir ~/.local/share/torbrowser/gnupg_homedir --keyserver keyserver.ubuntu.com --recv-keys 0x4E2C6E8793298290
gpg: key 4E2C6E8793298290: 76 duplicate signatures removed
gpg: key 4E2C6E8793298290: 121315 signatures not checked due to missing keys
gpg: error writing keyring '/home/user/.local/share/torbrowser/gnupg_homedir/pubring.kbx': Provided object is too large
gpg: key 4E2C6E8793298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" 121371 new signatures
gpg: Total number processed: 1
gpg:         new signatures: 121371
gpg:           not imported: 1
```
