### ISSUE TITLE
Faulty version checking with release of Tor Browser 10

### ISSUE THREAD

**Issue by rmsacks** [micahflee/torbrowser-launcher#498]
When upgrading to Tor Browser version 10.0, I was shown the following message and could not continue the installation process:

`The version of Tor Browser you have installed is earlier than it should be, which could be a sign of an attack!`

The issue seems to come from [this](https://github.com/micahflee/torbrowser-launcher/blob/275a2b82e3a3ea4027f664ecb7d9472ae4032c25/torbrowser_launcher/launcher.py#L420) line because the string comparison of `"7.5.2" <= "10.0"` returns `False` when it is logically `True`.

**Comment by Sandwichs-del** [comment]
What does the message even mean?

Does it mean that the DOWNLOADED version is LOWER, so it was NOT installed?
Or it means that the DOWNLOADED version was installed, despite being LOWER?

**Comment by rmsacks** [comment]
> What does the message even mean?
> 
> Does it mean that the DOWNLOADED version is LOWER, so it was NOT installed?
> Or it means that the DOWNLOADED version was installed, despite being LOWER?

Looking at the code again, I _think_ the downloaded version does get installed correctly. Then, when you run `torbrowser-launcher` with this new version installed, it checks to make sure the installed version ("10.0") is greater than or equal to a hard-coded version ("7.5.2"). Since the string "10.0" is less than "7.5.2" in python, `torbrowser-launcher` does **not** start the new, installed version Tor Browser and gives the warning message.

So, since the new version was actually installed correctly, you should be able to still run Tor Browser directly by skipping `torbrowser-launcher` and using the command `~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/start-tor-browser --verbose`. 

**Note**: If you get the following error when doing this,

`./firefox.real: error while loading shared libraries: libstdc++.so.6: failed to map segment from shared object`

it is due to apparmor. I fixed this by making this change to `/etc/apparmor.d/torbrowser.Browser.firefox`:

```diff
@@ -73,6 +73,7 @@ profile torbrowser_firefox @{torbrowser_firefox_executable} {
   owner @{torbrowser_home_dir}/TorBrowser/Tor/ r,
   owner @{torbrowser_home_dir}/TorBrowser/Tor/*.so mr,
   owner @{torbrowser_home_dir}/TorBrowser/Tor/*.so.* mr,
+  owner @{torbrowser_home_dir}/TorBrowser/Tor/libstdc++/*.so.* mr,

   # parent Firefox process when restarting after upgrade, Web Content processes
   owner @{torbrowser_firefox_executable} pxmr -> torbrowser_firefox,
```

and running this command as root to update the profile:

`apparmor_parser -r /etc/apparmor.d/torbrowser.Browser.firefox`

**Comment by paulrajib** [comment]
For Ubuntu 18.04, the command
"~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/start-tor-browser --verbose" execute/run the browser fine but I am trying to put it in the start-tor-browser.desktop file
sudo nano /home/raj/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
replacing "--detach" with "--verbose"
and then trying to start from the app icon but doesn't work :( .
It starts the tor launcher and try to update again though the version is 10.0
and also replace the "--verbose" with "--detach" by itself
and then shows
"The version of Tor Browser you have installed is earlier than it should be, which could be a sign of an attack!"
again.
:(

**Comment by dmknght** [comment]
I have a custom patch for this problem at `launcher.py`. Hope somebody can help me test this and confirm.
![Screenshot at 2020-09-25 10-28-09](https://user-images.githubusercontent.com/29118926/94197140-e21f1180-fea4-11ea-81ae-20679cfded80.png)

**Comment by succerror** [comment]
[`packaging`](packaging.pypa.io/en/latest/) lib might be handy here.

```python
from packaging.version import parse as parse_version

print(parse_version('1.2.3') > parse_version('1.2.3.1'))
# False
print(parse_version('1.2.4') > parse_version('1.2.3.1'))
# True
```

**Comment by anmarko** [comment]
I've done a new installation, it's really easy:
https://linuxconfig.org/how-to-install-tor-browser-in-ubuntu-18-04-bionic-beaver-linux

Before deleting of the complete old TOR-directory I've saved the bookmarks.
