### ISSUE TITLE
Can not launch Tor in Ubuntu 20.04 running command torbrowser-launcher

### ISSUE THREAD

**Issue by rohan-paul** [micahflee/torbrowser-launcher#504]
After running command `torbrowser-launcher` get the following error

```
gpg.errors.BadSignatures Key expired
...

...
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/gpg2'
```

**Comment by jsrosalg** [comment]
I been trying to reinstall Tor, after it gived an error, after many intents with different recommendations always get the same message error, (see the attached image), also I attached my Ubuntu configuration
![Screenshot from 2020-09-24 11-50-41_crop](https://user-images.githubusercontent.com/71821789/94132520-b6c60380-fe5f-11ea-9740-d0fd2e085a90.png)
![Screenshot_20200924_120348_crop](https://user-images.githubusercontent.com/71821789/94132549-bcbbe480-fe5f-11ea-8569-d9c7c68a6ee9.png)

**Comment by jsrosalg** [comment]
Thanks in advance for your help

**Comment by rohan-paul** [comment]
@jsrosalg - just in case, if you have been completely unable to reinstall Tor here's what I did, which is completely Uninstall current version and Reinstall from Tor's official page.

Downloaded the latest .tar.xz file From [Official Site](https://www.torproject.org/download/)

Then > Extract > Go into extracted directory > Give execution right to the file named “start-tor-browser.desktop” and run command

`./start-tor-browser`

That is, just follow the [Official guide](https://tb-manual.torproject.org/installation/)

**Comment by tdelaney58** [comment]
I have the same problem. I solved the _No such file or directory: '/usr/bin/gpg2'_ with `sudo apt-get install gnupg`, but the invalid key problem persists. I also completely uninstalled and reinstalled the tor stuff via synaptic package manager, but that did not help.

**Comment by kpcyrd** [comment]
@tdelaney58 you need to install [gnupg2](https://packages.debian.org/search?keywords=gnupg2)

**Comment by jsrosalg** [comment]
I hve installed and problem persist.

**Comment by jsrosalg** [comment]
today I found and alternative that works in my system:

https://flathub.org/apps/details/com.github.micahflee.torbrowser-launcher

<just using the two terminal commands.

I hope it works for you, but at the moment I was no able to automatically do that Tor use my default bittorent app for open links.
