### ISSUE TITLE
[Question] Which you recommend: firejail sandbox or flatpak sandbox ?

### ISSUE THREAD

**Issue by Nokia808** [micahflee/torbrowser-launcher#507]
Hi. I'm Fedora user & I was using torbrowser-launcher from my official Fedora repositories as .rpm until recently when I faced the version compression issue after update Tor to version 10. So, I remove .rpm & installed flatpak from FlatHub because I saw that you recommend this in your "read me" to be with newest version....

When I was using .rpm package, I was run it with firejail as "firejail torbrowser-launcher" ....

Now, a question jump to my mind, that I would like to ask: which is more secure, firejail sandbox or flatpak sandbox ? Please note that I targeted the out of box profile of both without manual user customization.

Best.

**Comment by AsciiWolf** [comment]
Both should be pretty secure, at least in my opinion. :-)
