### ISSUE TITLE
signature verification failed.

### ISSUE THREAD

**Issue by TheOneTrueGuy** [micahflee/torbrowser-launcher#509]
Have repeatedly tried several repair methods found on search including updating and replacing the gpg key. none have worked.
Error code: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Key expired.

**Comment by lindsaymacvean** [comment]
![image](https://user-images.githubusercontent.com/1574178/95028955-51161a80-069c-11eb-976a-eb686cec7208.png)
