### ISSUE TITLE
SIGNATURE VERIFICATION FAILED!

### ISSUE THREAD

**Issue by hersoncruz** [micahflee/torbrowser-launcher#510]
`Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Key expired`
Running on Debian Linux 10

**Comment by yast1963** [comment]
The same error, Ubuntu 18.04.5 LTS

**Comment by DaphneSultana** [comment]
The same error since the version 10 automatic update on 23rd September. Ubuntu 20.04 LTS.

**Comment by ivostoykov** [comment]
same error here  Ubuntu 18.04 LTS. just updated Tor (26 Sep)

**Comment by mnovozhylov** [comment]
+1
