### ISSUE TITLE
Tor Browser Error -- will not launch

### ISSUE THREAD

**Issue by surlyc** [micahflee/torbrowser-launcher#511]
When I try to start the Tor Browser I get:
SIGNATURE VERIFICATION FAILED!
Error Code:  GENERIC_VERIFY_FAIL

The error message said to "report the above error code here"

I am using Kubuntu 18.04.  This occurred after installing tor, torbrowser-launcher, tor-geoipdb, and torsocks.

**Comment by direclown** [comment]
I'm having the same issue and I also have an Ubuntu distro. Like the one above it says
"SIGNATURE VERIFICATION FAILED! 
Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Key expired

You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key.

![tor browser error](https://user-images.githubusercontent.com/13476456/94341072-97041c00-ffd4-11ea-9cd5-e236b0f55121.png)

This seemed to occur after I did a software update, so maybe it's trying to run an older version of the Tor Browser?

**Comment by XabierV** [comment]
Same here, it tries to download a new version but complains about the key being expired. Working on Kubuntu 20.04

**Comment by AngelHair** [comment]
I got the same error as direclown.  I am running Ubuntu 18.04.5 LTS.
![Screenshot from 2020-10-08 16-06-09](https://user-images.githubusercontent.com/14369583/95508726-7303eb80-0981-11eb-8d8e-669494969e3f.png)

**Comment by davgross** [comment]
Today's update seems to have fixed this. Thanks.

**Comment by surlyc** [comment]
I just now tried to install this again (Kubuntu 18.04 using Muon Package Manager).  I get the same error message as before:

![TorBrowserBundleMsg](https://user-images.githubusercontent.com/71914392/96071036-d3959b80-0e4d-11eb-8ba3-4cce9e85623d.png)

**Comment by direclown** [comment]
Does it help if you completely purge any previous versions of Tor on your system and update the launcher from the terminal?

**Comment by surlyc** [comment]
This worked.

I ran purge and autoremove from the terminal on everything Tor.  Then I
followed the installation instructions using Flatpack here:

https://github.com/micahflee/torbrowser-launcher

and here:

https://flatpak.org/setup/Ubuntu/

The browser downloaded, installed, and ran without a hitch.

Thank you very much.

**Comment by direclown** [comment]
Yes, I did the same, and it's working fine now! Thanks to Micah and the developers!!
