### ISSUE TITLE
SIGNATURE VERIFICATION FAILED!

### ISSUE THREAD

**Issue by Keith-Njagi** [micahflee/torbrowser-launcher#512]
Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2:Key expired

I'm having an issue with Tor Browser refusing to launch once I open it.
I keep getting the above error and the wizard seems to keep restarting the download after I click on start.
I've tried sudo apt remove torbrowser-launcher and reinstalling it again but the issue persists.

**Comment by tgeek77** [comment]
Same here. Running version 0.3.2 on OpenSUSE Leap.

**Comment by RimaitosLab** [comment]
same here, it seems the tor project has updated its keys. I've manually checked and the signatures are fine. It's just the launcher which doesn't accept the key.

Is there a way to manually add the key or do we have to wait for an update?

**Comment by freedriven** [comment]
Same problem here for the version in the debs (Ubuntu 20.04).
(FYI, downloading the tar from torproject.org, and running from command line, works.)

**Comment by kozmo2k4** [comment]
Same error: "Signature Verification Failed. Key Expired".
Ubuntu 18.04.

**Comment by DirtyDean** [comment]
I've had a look at this by running the TorBrowser-Launcher in Bash to see if there is an error.  The Tor Browser I installed via the launcher had stop working after the update to V10.0 this week.  Subsequently, I have attempted to reinstall it using the Launcher to see if this fixed the issue (failing miserably).  Error messages as below:

Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.2
https://github.com/micahflee/torbrowser-launcher
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Latest version: 10.0
Downloading https://dist.torproject.org/torbrowser/10.0/tor-browser-linux64-10.0_en-US.tar.xz.asc
Downloading https://dist.torproject.org/torbrowser/10.0/tor-browser-linux64-10.0_en-US.tar.xz
Verifying Signature
Refreshing local keyring...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 589, in verify
    c.verify(signature=sig, signed_data=signed)
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 541, in verify
    raise errors.BadSignatures(results[1], results=results)
gpg.errors.BadSignatures: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Key expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 600, in run
    verify()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 594, in verify
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/launcher.py", line 603, in run
    self.common.refresh_keyring()
  File "/usr/lib/python3/dist-packages/torbrowser_launcher/common.py", line 196, in refresh_keyring
    p = subprocess.Popen(['/usr/bin/gpg2', '--status-fd', '2',
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/gpg2'

I checked /usr/bin/ but found no gpg2 file.  I then looked in the repositories (using Synaptic and found apps gnups2 and gpgv2.  As an experiment I installed them and ran TorBrowser-Launcher again in Bash.  This time I didn't see any errors in the console, but I did get this error on the desktop
![Screenshot from 2020-09-27 01-26-35](https://user-images.githubusercontent.com/71951623/94353170-a7180c00-0065-11eb-9220-44bc132a1618.png)

My initial thoughts it might be that the signature key has expired.  I have downloaded the Tor Browser.tar.xz directly from the Tor Project and running via Bash from the unzipped folder.   That seems to launch OK without issue, possibly ruling out the signature issue.
I've sadly no solution, but I hope the information I've provided with be of help to the dev(s).

**Comment by dusk-comes** [comment]
seems the issue is keyring itself or a server where it was downloaded. my list include 2 keys: from tortorbrowser@torproject.org which I added manually and the last which was downloaded during deb package's installation. I can verify torbrowser package by the first key. Contrary, verification is failed when I use the second key.

**Comment by EmilGus** [comment]
Same problem here, I'm running Ubuntu 18.04.5 LTS.

**Comment by LorenRiccie** [comment]
Same here, Ubuntu Ubuntu 20.04.1 LTS
