### ISSUE TITLE
SIGNATURE VERIFICATION FAILED!

### ISSUE THREAD

**Issue by anarcho70** [micahflee/torbrowser-launcher#515]
![Signature verification failed](https://user-images.githubusercontent.com/71951960/94353299-2c36fd00-0035-11eb-97c6-b11749d894ce.png)

Has anyone found a fix for this? This happened after I updated TOR. :(

**Comment by helozjisky** [comment]
the same here, Pls update :)

**Comment by slproxy** [comment]
I have the exact same problem. 

SIGNATURE VERIFICATION FAILED!
Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Key expired
You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verificatic
A copy of the Tor Browser files you downloaded have been saved here:
/home/parallels/.cache/torbrowser/download/tor-browser-linux64-10.0_en-US.tar.xz.verification_failed
/home/parallels/.cache/torbrowser/download/tor-browser-linux64-10.0_en-US.tar.xz.asc.verification_failed
Click Start to refresh the keyring and try again. If the message persists report the above error code here:
https://github.com/micahflee/torbrowser-launcher/issues

**Comment by tthtlc** [comment]
yes same problem for me today.

My workaround is to download it from another site:

tor-browser-linux64-10.0_en-US.tar.xz
https://dist.torproject.org/torbrowser/10.0/tor-browser-linux64-10.0_en-US.tar.xz

and unxz and run the "/start-tor-browser.desktop" from there.

**Comment by JuliusGM** [comment]
Yesterday morning I had the same problem.
I'm using Ubuntu 18.04.05.
After several tries and getting no results, I've search alternatives and found this one:

https://www.wikihow.com/Install-Tor-on-Linux

Actually is the same solution told by tthtlc.

It functions perfectly, but do not try to use your old onion button.
Instead go to the path where is the file start-tor-browser.desktop and try to open that file. It will appear that is not trustable or something like that, ignore it and open it and close the tor browser.

As soon as you close the tor browser you will see the onion icon in that folder.
Just copy that to your main desktop.
Run tor from there anytime you want.

**Comment by ethpi** [comment]
Same for me with Ubuntu 20.04.1.
![grafik](https://user-images.githubusercontent.com/20401857/94688881-78808680-032e-11eb-98a2-1d690b6f4921.png)

**Comment by anarcho70** [comment]
Hi, I see you closed my ticket and I am pretty new to Linux. Can you tell
me what I need to type in to fix this issue?

**Comment by micahflee** [comment]
This issue was fixed in torbrowser-launcher 0.3.3. To get the new version, first uninstall it from the package repositories:

```
sudo apt remove torbrowser-launcher -y
```

And then install it from flathub instead, there are instructions to do that here: https://flathub.org/apps/details/com.github.micahflee.torbrowser-launcher
