### ISSUE TITLE
Signature Verification Failed

### ISSUE THREAD

**Issue by b7284genie** [micahflee/torbrowser-launcher#517]
I've been trying to update my Tor Browser for a couple of days, but it keeps saying that it cannot verify the signature key. I will attach the screenshot.

My system is running Arch Linux.

![Tor Browser Error](https://user-images.githubusercontent.com/61214435/94678387-b8149600-0361-11eb-9342-caeb091a3a1f.png)

**Comment by BillDietrich** [comment]
Same for me in Ubuntu MATE 20.04.  Tor has been dead in the water for a week now.

**Comment by b7284genie** [comment]
Bugger

**Comment by b7284genie** [comment]
Cheers
