### ISSUE TITLE
SIGNATURE VERIFICATION FAILED:

### ISSUE THREAD

**Issue by gasu2000** [micahflee/torbrowser-launcher#519]
SIGNATURE VERIFICATION FAILED:

Error Code EB77449.D5FFOGED: Firma incorrecta

You might be under attack, there might be network problem, or you may be missing a recently added Tor Browser verification key
A copy of the Tor Browser files you downloaded have been saved her:

/.cache/torbrowser/download/tor-browser-linux64-10.0_en-US.tar.xz.verification_failed
/.cache/torbrowser/download/tor-browser-linux64-10.0_en-US.tar.xz.asc.verification_failed

Click Start to refresh the keyring and try again. If the message persist report the above error code here:
https://github.com/micahflee/torbrowser-launcher/issues

**Comment by nohing** [comment]
I got the same problem
![Errore_Tor_Verifica_Chiave](https://user-images.githubusercontent.com/36953233/94902653-d3ce8800-0498-11eb-89bf-5fe84ae508fe.png)

**Comment by greenhorn200** [comment]
I'm having it as well still.

**Comment by docaltmed** [comment]
Can confirm on Kubuntu 20.04

**Comment by unheatedgarage** [comment]
Gentoo testing branch -- checking in and standing by...

**Comment by gasu2000** [comment]
My SO is Debian GNU/Linux 10 (buster).

Best regards.

Gasu2000

**Comment by jschinnerer** [comment]
Similar or same error just now on Ubuntu 18.04.5 LTS.
Screenshot attached. 
Refreshed/retried twice after initial error; gives same error all three times.
![install-error-Screenshot_2020-10-03_13-00-42](https://user-images.githubusercontent.com/1641535/95000839-30a16f80-0579-11eb-97eb-b7c26edf174f.png)

**Comment by cckanka** [comment]
Same issue, running Ubuntu Mate 18.04

**Comment by Dev380** [comment]
Same

**Comment by Dev380** [comment]
Can confirm on Pop!_OS based on Ubuntu 20

**Comment by lindsaymacvean** [comment]
Same here 
![image](https://user-images.githubusercontent.com/1574178/95028942-304dc500-069c-11eb-8dc2-d2ddd0b312ac.png)

**Comment by galaxy119** [comment]
gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pool.sks-keyservers.net


fixed the issue for me.

**Comment by greenhorn200** [comment]
> gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pool.sks-keyservers.net
> 
> fixed the issue for me.

How long did it take Terminal to run the command and get Tor running? 

**sudo gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pool.sks-keyservers.net
[sudo] password for user: 
gpg: WARNING: unsafe ownership on homedir '/home/user/.local/share/torbrowser/gnupg_homedir'
gpg: refreshing 1 key from hkp://pool.sks-keyservers.net
gpg: key 4E2C6E8793298290: 2 duplicate signatures removed
gpg: key 4E2C6E8793298290: 121412 signatures not checked due to missing keys
gpg: key 4E2C6E8793298290: 2 signatures reordered
gpg: error writing keyring '/home/user/.local/share/torbrowser/gnupg_homedir/pubring.kbx': Provided object is too large
gpg: key 4E2C6E8793298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" 121412 new signatures
gpg: Total number processed: 1
gpg:         new signatures: 121412
gpg:           not imported: 1**

This was the feed back it gave me after a long wait. Like, a half hour wait. 

And then when I treid to open Tor Browser again it still wouldn't open.

**Comment by greenhorn200** [comment]
> gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pool.sks-keyservers.net
> 
> fixed the issue for me.

Follow up to previous post: 

I just tried to run Tor Again after letting it sit and run this command as super user. 

it's still not working. 

Tor is not fixed.

**Comment by gasu2000** [comment]
Hi.
This issue has been solved, so there is no need  to keep working on it. 

Step:
This issue has been solved, so there is no need  to keep working on it. Write on terminal.
1.- Update your SO.
2.- Desinstall TOR or erase folder.
3.- Download TOR, https://www.torproject.org/dist/torbrowser/10.0/tor-browser-linux64-10.0_en-US.tar.xz
4.- Decompressed file.
5.- Open terminal from folder.
6.- Write on terminal, $ ./start-tor-browser.desktop.
7.- Wait....

**Comment by gasu2000** [comment]
Process on Debian 10 (buster)

![Error1](https://user-images.githubusercontent.com/49823192/95544958-373d4600-09c2-11eb-888d-bec6e209fe09.jpg)
![Image1](https://user-images.githubusercontent.com/49823192/95544966-3ad0cd00-09c2-11eb-8375-3eb5093257e1.jpg)
![Image2](https://user-images.githubusercontent.com/49823192/95544973-3f958100-09c2-11eb-89ca-359017b4de57.jpg)
![Image3](https://user-images.githubusercontent.com/49823192/95544987-4623f880-09c2-11eb-9099-7cd77b4058aa.jpg)
![Image4](https://user-images.githubusercontent.com/49823192/95545004-5340e780-09c2-11eb-9d32-832bd0bb579e.jpg)

**Comment by gasu2000** [comment]
Hi.
This issue has been solved, so there is no need to keep working on it.

Step:
This issue has been solved, so there is no need to keep working on it.
Write on the terminal.
1.- Update your SO.
2.- Desinstall TOR or erase folder.
3.- Download TOR,
https://www.torproject.org/dist/torbrowser/10.0/tor-browser-linux64-10.0_en-US.tar.xz
4.- Decompressed file.
5.- Open terminal from folder.
6.- Write on terminal, $ ./start-tor-browser.desktop.
7.- Wait....

**Comment by jschinnerer** [comment]
Regressed on Ubuntu 18.04.5 LTS.
Tor browser installed OK after removing previous failed install.

**Comment by gasu2000** [comment]
Hi.
This issue has been solved, so there is no need to keep working on it.

Step:
This issue has been solved, so there is no need to keep working on it.
Write on the terminal.
1.- Update your SO.
2.- Desinstall TOR or erase folder.
3.- Download TOR,
https://www.torproject.org/dist/torbrowser/10.0/tor-browser-linux64-10.0_en-US.tar.xz
4.- Decompressed file.
5.- Open terminal from folder.
6.- Write on terminal, $ ./start-tor-browser.desktop.
7.- Wait....


Process on Debian 10 (buster)
![Error1](https://user-images.githubusercontent.com/49823192/95634638-f855d180-0a4f-11eb-9b62-b7d5e9c2acff.jpg)
![Image1](https://user-images.githubusercontent.com/49823192/95634641-f986fe80-0a4f-11eb-8e45-c1935d70cf35.jpg)
![Image2](https://user-images.githubusercontent.com/49823192/95634646-fbe95880-0a4f-11eb-99ca-1075c73aedb3.jpg)
![Image3](https://user-images.githubusercontent.com/49823192/95634651-fdb31c00-0a4f-11eb-9ade-a4f570657149.jpg)
![Image4](https://user-images.githubusercontent.com/49823192/95634665-04da2a00-0a50-11eb-8e45-226c4afd7fce.jpg)
