### ISSUE TITLE
Comparing versions is incorrect

### ISSUE THREAD

**Issue by avk700** [micahflee/torbrowser-launcher#520]
Function check_min_version() in launcher.py works incorrect if installed version of Tor Browser is '10.0' and variable self.min_version in last version 0.3.2-9 of torbrowser-launcher is '7.5.2'.
I think it should be used something like that:
[https://stackoverflow.com/questions/1714027/version-number-comparison-in-python](https://stackoverflow.com/questions/1714027/version-number-comparison-in-python)

**Comment by DavidPesticcio** [comment]
FYI

https://github.com/micahflee/torbrowser-launcher/pull/499#issuecomment-703119911
