### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by Dev380** [micahflee/torbrowser-launcher#522]
Tor refuses to update. It just says "Signature verification failed" repeatedly.

**Comment by lindsaymacvean** [comment]
same here. 

![image](https://user-images.githubusercontent.com/1574178/95028921-08f6f800-069c-11eb-88ae-6ed9e509916c.png)

**Comment by CaptainYukinoshitaHachiman** [comment]
same here.

**Comment by michal25** [comment]
Same problem here.

$ gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu
gpg: aktualizuje se 1 klíč z hkp://pgp.mit.edu
gpg: obnovení dat na serveru klíčů se nezdařilo: Žádná data

$ gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pool.sks-keyservers.net
gpg: aktualizuje se 1 klíč z hkp://pool.sks-keyservers.net
gpg: key 4E2C6E8793298290: 75 duplicate signatures removed
gpg: key 4E2C6E8793298290: 121340 podpisů neověřeno, protože chybí klíče
gpg: key 4E2C6E8793298290: 2 signatures reordered
gpg: chyba při zápisu souboru klíčů (keyring) „/home/michal/.local/share/torbrowser/gnupg_homedir/pubring.kbx“: Dodaný objekt je příliš dlouhý
gpg: klíč 4E2C6E8793298290: „Tor Browser Developers (signing key) <torbrowser@torproject.org>“ 121413 nových podpisů
gpg: Celkový počet zpracovaných klíčů: 1
gpg:         nové podpisy: 121413
gpg:           neimportováno: 1

**Comment by arnoldpinklanefloyd** [comment]
same problem herex-special/nautilus-clipboard
copy
file:///media/patrick/My%20Passport/Schermafdruk%20van%202020-10-05%2013-41-04.jpg

**Comment by arnoldpinklanefloyd** [comment]
same problem here

![afbeelding](https://user-images.githubusercontent.com/72388549/95080524-819b9a00-0718-11eb-92f2-64f292d44bce.png)

**Comment by Dimensional** [comment]
Manually checking the signatures confirms it's not expired, so the launcher is trying to read from an incorrect public key.

```
gpg --verify tor-browser-linux64-10.0_en-US.tar.xz.asc tor-browser-linux64-10.0_en-US.tar.xz

gpg: Signature made Tue 22 Sep 2020 02:14:53 AM CDT
gpg:                using RSA key EB774491D9FF06E2
gpg: Good signature from "Tor Browser Developers (signing key) <torbrowser@torproject.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
     Subkey fingerprint: 1107 75B5 D101 FB36 BC6C  911B EB77 4491 D9FF 06E2
```

**Comment by michal25** [comment]
But signature verification failed also in fresh installation.
Why?
![Screenshot_20201006_142031](https://user-images.githubusercontent.com/5064337/95201016-9e4ed500-07df-11eb-864c-1097e57b77d3.png)

**Comment by Dimensional** [comment]
> 
> 
> But signature verification failed also in fresh installation.
> Why?
> ![Screenshot_20201006_142031](https://user-images.githubusercontent.com/5064337/95201016-9e4ed500-07df-11eb-864c-1097e57b77d3.png)

No idea. It was doing that for me when I uninstalled and reinstalled. If I had to guess, it's temporarily pulling an old public key and using that instead of the most recent one or checking to see if it's already in the computer's GnuPG database.

**Comment by Senk42** [comment]
I'm having the same issue and it was a brand new installation as well. Fresh install of OS even.

**Comment by Dev380** [comment]
Weird. For me I just reinstalled through Snap and it worked.

**Comment by michal25** [comment]
The problem is not solved yet.

Here is an fresh installation of torbrowser-launcher from 
https://github.com/micahflee/torbrowser-launcher

And the problem persist

**Comment by michal25** [comment]
![Screenshot_20201007_140121](https://user-images.githubusercontent.com/5064337/95329793-d3265f00-08a7-11eb-84a7-2f7c8d6d3d8c.png)
