### ISSUE TITLE
Signature Verification Failed

### ISSUE THREAD

**Issue by dezvolt** [micahflee/torbrowser-launcher#533]
![Screenshot from 2020-10-10 15-40-55](https://user-images.githubusercontent.com/69096826/95664606-2221fd80-0b0f-11eb-9596-cfd93d109d65.png)

**Comment by kingkill33** [comment]
Signature verification failed!
Error Code: Generic_verify_fail
Error code reported as requested after 3 failed attempts

![Screenshot from 2020-10-11 13-18-51](https://user-images.githubusercontent.com/72692238/95677352-2872b100-0bc5-11eb-8d96-76887d916567.png)

**Comment by clsyeung** [comment]
i have the same problem with same error message

![Screenshot_20201011_193722](https://user-images.githubusercontent.com/63544910/95677629-41c03100-0bb6-11eb-8170-73469ac05ef2.png)

**Comment by jorre-vannieuwenhuyze** [comment]
Same issue here since Ubuntu update

**Comment by micahflee** [comment]
This is fixed in torbrowser-launcher 0.3.3. Uninstall it from the package repositories:

```
sudo apt remove torbrowser-launcher -y
```

And then install it from flathub instead: https://flathub.org/apps/details/com.github.micahflee.torbrowser-launcher
