### ISSUE TITLE
SIGNATURE VERIFICATION FAILED! 

### ISSUE THREAD

**Issue by JASEINS** [micahflee/torbrowser-launcher#536]
Error Code: GENERIC_VERIFY_FAIL

Three options come next, and verification seems to be the one (vs attack or network problem). 

![Screenshot 201019b](https://user-images.githubusercontent.com/73117693/96459615-2a48ff80-11d7-11eb-856b-5534085590b4.png)

No Tor in Bionic Ubuntu MATE. :(

**Comment by alex27riva** [comment]
I tried importing the key with `curl -s https://openpgpkey.torproject.org/.well-known/openpgpkey/torproject.org/hu/kounek7zrdx745qydx6p59t9mqjpuhdf |gpg --import -`
But I have not fixed...
