### ISSUE TITLE
check_min_version() fails

### ISSUE THREAD

**Issue by dtgilles** [micahflee/torbrowser-launcher#539]
[check_min_version()](https://github.com/micahflee/torbrowser-launcher/blob/0e020dce1319361230784000f88b166bea1061d3/torbrowser_launcher/launcher.py#L463) fails
* string compare is not the best method to check if version is higher than the minimal required number
* BUT it worked quite a long time, so perhaps it is a valid workaround to set [minimal version](https://github.com/micahflee/torbrowser-launcher/blob/0e020dce1319361230784000f88b166bea1061d3/torbrowser_launcher/launcher.py#L75) to something like 10.0.0?

**Comment by davidbaumann** [comment]
Will be fixed with #320
