### ISSUE TITLE
Tor exited during startup. This might be due to an error in your torrc file, a bug in Tor or another program on your system, or faulty hardware. Until you fix the underlying problem and restart Tor, Tor Browser will not start.

### ISSUE THREAD

**Issue by birdofprey** [micahflee/torbrowser-launcher#541]
OS：Debian Gnu/Linux 10.7
Tor: 10.5a6
error:
Tor exited during startup. This might be due to an error in your torrc file, a bug in Tor or another program on your system, or faulty hardware. Until you fix the underlying problem and restart Tor, Tor Browser will not start.

**Comment by FabianRoSan** [comment]
I updated to Tor ver. 11.0.3 on Microsoft Windows [Versión 10.0.19044.1415], no logs, no errors, only in console browser:
"_Could not load engine blockchair-onion@search.mozilla.org: Error: Extension is invalid SearchService.jsm:609:17
Resource  of root-node was not found. 2 resource-command.js:724:17
Tried to send a 'target-destroyed-form' event on an already destroyed actor 'watcher' Actor.js:58:15
Error: \_initWorker called too early! Please read the session file from disk first. SessionFile.jsm:375:15
NS_ERROR_CONNECTION_REFUSED: Component returned failure code: 0x804b000d (NS_ERROR_CONNECTION_REFUSED) [nsIScriptableInputStream.available] tor-control-port.js:81
    onInputStreamReady resource://torbutton/modules/tor-control-port.js:81_
"

**Comment by Tetonne** [comment]
on macOS : delete lock folder in 
~/Library/Application\ Support/TorBrowser-Data/Tor/
it. will solve the issue

**Comment by vis-v** [comment]
I couldn't find the file
