### ISSUE TITLE
torbrowser launch issue in fedora 33

### ISSUE THREAD

**Issue by estranged2030** [micahflee/torbrowser-launcher#543]
![Screenshot from 2020-12-22 22-12-59](https://user-images.githubusercontent.com/59946803/102912035-f32aef00-44a2-11eb-952b-badff07fde59.png)

PLEASE REFER THE SCREENSHOT ATTACHED FOR TOR BROWSER LAUNCH ISSUE ON FEDORA 33

**Comment by AsciiWolf** [comment]
Same issue on Tor Browser Flatpak (https://github.com/flathub/com.github.micahflee.torbrowser-launcher/issues/14).

/cc @micahflee

**Comment by AsciiWolf** [comment]
#934

**Comment by AsciiWolf** [comment]
#534
