### ISSUE TITLE
Error Code. Pop! OS v 20.10

### ISSUE THREAD

**Issue by MotherOfPerls** [micahflee/torbrowser-launcher#544]
Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Key Expired
If the message persists report the above error

**Comment by Gladox114** [comment]
Maybe it's way less secure but because of that error I installed the .deb version in the pop_shop which worked but maybe not that isolated like a flatpak. Not sure if this is important.

**Comment by AsciiWolf** [comment]
Same issue as #543.

**Comment by AsciiWolf** [comment]
@MotherOfPerls Do you use a Flatpak Tor Browser Launcher or a regular deb one?

**Comment by MotherOfPerls** [comment]
I fixed the issue. Instead of downloading it from the pop shop (package manager), I just downloaded it from the website and it worked fine lol.

**Comment by jtagcat** [comment]
Duplicate of #534
