### ISSUE TITLE
Signature Verification Failed via flatpak (user app) 0.3.3

### ISSUE THREAD

**Issue by mcl21014** [micahflee/torbrowser-launcher#545]
Seems the signature has changed again. Please fix when possible. Nice to have Tor Browser integrated into Linux via the application grid in GNOME.

**Comment by ijann** [comment]
The same thing happens to me, someone knows which server has the verification correctly 

![52286e6c-9d32-4e02-b1e6-a9af06d1accd](https://user-images.githubusercontent.com/2209203/103323938-e880d480-4a23-11eb-8047-921600c54b6d.jpg)

**Comment by Manoj-Sri** [comment]
My signature verification also failed

![Screen Capture_torbrowser-launcher_20201230153151](https://user-images.githubusercontent.com/49629253/103344286-29c0c500-4ab4-11eb-972d-73a1b9df464a.jpg)

**Comment by ishanveersg** [comment]
Same for me

**Comment by PreciousWarrior** [comment]
Yep. Can Confirm

**Comment by AsciiWolf** [comment]
Already reported [here](https://github.com/flathub/com.github.micahflee.torbrowser-launcher/issues/14). I am currently trying to find a fix/workaround for this issue.

**Comment by AsciiWolf** [comment]
As a workaround, I have [manually added](https://github.com/flathub/com.github.micahflee.torbrowser-launcher/pull/16) a patch to update the shipped Tor Browser developers key. It does not fix the key auto update mechanism that does not work in a Flatpak version of Tor Browser Launcher for some reason. However, it at least solves the current situation with the key being expired.

**Comment by mcl21014** [comment]
Good job. Can confirm myself the workaround will let it download now.

**Comment by reno-a** [comment]
Good news. 
Upgrade 0.3.4 it's work.
