### ISSUE TITLE
AppArmor denials that have no consequences

### ISSUE THREAD

**Issue by u451f** [micahflee/torbrowser-launcher#547]
This is a bug reported by Paul Wise (pabs) at Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980155:

"When I start torbrowser-launcher I get apparmor denials like the following. There don't appear to be any consequences for this denial, the Tor Browser window starts up and works just fine. Possibly the Firefox sandboxing uses this file but I'm not sure."

`Jan 15 20:22:03 audit[874474]: AVC apparmor="DENIED" operation="open" profile="torbrowser_firefox" name="/proc/874474/cgroup" pid=874474 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000`

I guess this can be ignored, but I'm noting it here just in case.

**Comment by rogers0** [comment]
@intrigeri 
I still got apparmor warning below on my buster-backports system, kernel 4.19.0-16-amd64:
```
[534312.197665] audit: type=1400 audit(1621703579.666:68): apparmor="DENIED" operation="open" profile="torbrowser_firefox" name="/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us" pid=1741 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

So probably need one more line:
+  /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us r,

**Comment by intrigeri** [comment]
Hi,

> I still got apparmor warning below on my buster-backports system, kernel 4.19.0-16-amd64:
> ```
> [534312.197665] audit: type=1400 audit(1621703579.666:68): apparmor="DENIED" operation="open" profile="torbrowser_firefox" name="/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us" pid=1741 comm="firefox.real" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> ```
>
> So probably need one more line:
> +  /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us r,

Can you please test 811494c6cf0cc0a7a96e647ba0f022f4d03713be?

Cheers!

**Comment by rogers0** [comment]
@intrigeri
Yes, it works well now.
Thanks for your support!
