### ISSUE TITLE
Signature Verification Failed (linux64-10.0.9) - Key Expired

### ISSUE THREAD

**Issue by sudo-dax** [micahflee/torbrowser-launcher#548]
Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2

**Comment by s2ep2** [comment]
Same here. Same error code. 
Machine info:
OS: Linux Mint 20 x86_64 
Kernel: 5.4.0-65-generic 
Shell: bash 5.0.17 
DE: Cinnamon 
Terminal: gnome-terminal 
CPU: Intel Pentium G4500 (2) @ 3.500GHz 
GPU: Intel HD Graphics 530 
Memory: 4476MiB / 7842MiB 
CPU Usage: 26% 
Disk (/): 15G / 40G (40%) 

Thank you!

**Comment by kevinowyang** [comment]
I'm getting the same error code, too.  Thanks for the help!

**Comment by kevinowyang** [comment]
I'm having the same error. Thanks for the help in advance!

**Comment by linley434** [comment]
Same here,same error code
 Debian kernel 5.9.6-2 (2020-11-17)
DE: Mate

**Comment by shinobody** [comment]
Same here, same error code.
OS: Ubuntu 20.04.2 LTS 64 bit
DE: Gnome

**Comment by BushyBoi69** [comment]
Same here. same error code.
OS: OpenSUSE Tumbleweed x64_64
DE: KDE Plasma 5.22.0
Kernel: 5.12.9-1-default
