### ISSUE TITLE
Version Check URL Down

### ISSUE THREAD

**Issue by XeroOl** [micahflee/torbrowser-launcher#549]
The version check information is failing to download, preventing the browser from downloading. This happens regardless of which mirror I choose in the `--settings` GUI.
The failing download is this URL: `https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US`
It appears to come from [this line](https://github.com/micahflee/torbrowser-launcher/blob/v0.3.3/torbrowser_launcher/common.py#L198) in the source code.

To reproduce:
```
git clone https://github.com/micahflee/torbrowser-launcher
cd torbrowser-launcher
./torbrowser-launcher
```
This is printed to the console:
```
By Micah Lee, licensed under MIT
version 0.3.3
https://github.com/micahflee/torbrowser-launcher
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Download Error: 404
```

**Comment by vedgy** [comment]
I encountered exactly the same issue on Manjaro GNU/Linux with [torbrowser-launcher](https://archlinux.org/packages/community/any/torbrowser-launcher) Arch package. Looks like only Windows releases have been uploaded here: https://aus1.torproject.org/torbrowser/update_3/release/. There are files for all platforms here: https://aus1.torproject.org/torbrowser/update_3/release.old/.

**Comment by vedgy** [comment]
https://blog.torproject.org/new-release-tor-browser-10011: the latest release Tor Browser 10.0.11 is "Windows Only". Can this be fixed in *torbrowser-launcher* somehow? What is the easiest secure workaround?

**Comment by vedgy** [comment]
*torbrowser-launcher* works fine now: https://aus1.torproject.org/torbrowser/update_3/release/ lists XML files for all platforms.
