### ISSUE TITLE
SIGNATURE VERIFICATION FAILED!

### ISSUE THREAD

**Issue by BigSirofBigSur** [micahflee/torbrowser-launcher#550]
Error Code: EB774491D9FF06E2
Running on openSUSE with all latest packages installed, traffic routed through Tor (Browser), download via official dist.

**Comment by u451f** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977730 there is a similar bug report on Debian.

**Comment by u451f** [comment]
See #545 and #548

**Comment by macintosh-p** [comment]
Same issue and similar error code (same error code as above but with a prefix 110775B5D101FB36BC6C6C911B)
Ubuntu focal 20.04. fully updated and patched.
Linux; 5.8.0-45-generic kernel
torbrowser-launcher;  0.3.2-9ubuntu1
tor; 0.4.2.7-1
Error occurred on fresh install and subsequent retry.

**Comment by antierrors** [comment]
![image](https://user-images.githubusercontent.com/81534789/112767936-434bad00-8fce-11eb-869f-d4d6a57e7acb.png)

**Comment by antierrors** [comment]
thank you for your timely response...
however it didn't work.
from terminal >
The version of Tor Browser you have installed is earlier than it should be, which could be a sign of an attack!
DONE

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by reno-a** [comment]
Hello,
The code error is differnent, but it's the same problem signature verification with flatpak version (0.33).
