### ISSUE TITLE
Launcher does not detect Tor Browser as being installed on non english user session

### ISSUE THREAD

**Issue by u451f** [micahflee/torbrowser-launcher#552]
This is a bug initially reported at Debian with a patch:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=983198

It happens that though the launcher works it doesn't detect torbrowser as being installed. It causes two issues:

-  The 'Settings' window points status as Not Installed;
- The 'Browser launcher' keeps running the routines to download and verify the 'first installation'.

I realized that reload the settings after rebuilding paths makes the launcher work as expected.

Plus, load_settings() is not checking changes at 'installed' directive to rewrite the settings file ('settings.json').

Reported by Marcelo S Mota

**Comment by u451f** [comment]
[08-Fix-installation-detection.txt](https://github.com/micahflee/torbrowser-launcher/files/6121961/08-Fix-installation-detection.txt)

**Comment by kpcyrd** [comment]
hey, can you test if #585 resolves this issue for you?

**Comment by Knebergish** [comment]
Hello all.
I am experiencing the same issue with "Tor Browser Launcher" from Flatpak: every time I start, the browser installation status is "Not Installed".
If I run the application with the "LANG=en_US.UTF-8" env, then everything works correctly.
