### ISSUE TITLE
Question: Is the version in Flathub sandboxed? 

### ISSUE THREAD

**Issue by rany2** [micahflee/torbrowser-launcher#553]
Programs in flatpak can't access Linux's regular sandboxing features like user namespaces or SUID sandbox and so they must use "flatpak-spawn" instead. For example, Chromium needs to get patched to be properly sandboxed and Chrome/Electron/etc. programs need to use Zypak (which uses flatpak-spawn behind the scenes) to have sandboxing.  

Does the version in Flathub do that?

**Comment by intrigeri** [comment]
I understand the Flatpak version of torbrowser-launcher is developed on https://github.com/flathub/com.github.micahflee.torbrowser-launcher, which may be a better place to ask such questions.

This being said, here's what I see in GNOME Software:

![sandboxed](https://user-images.githubusercontent.com/2395100/119252260-b884ca00-bb9a-11eb-9e69-2cc9f3153ba1.png)
![permissions](https://user-images.githubusercontent.com/2395100/119252267-c1759b80-bb9a-11eb-966e-512c19f763d2.png)

The detailed configuration is https://github.com/flathub/com.github.micahflee.torbrowser-launcher/blob/master/com.github.micahflee.torbrowser-launcher.yaml

So, my understanding is that the Flatpak version of torbrowser-launcher is sandboxed by Flatpak itself (that is, really, by bubblewrap), but I don't see anything special being done to allow Tor Browser to make use of Firefox' own sandboxing features _within the Flatpak sandbox_.
