### ISSUE TITLE
Key expired

### ISSUE THREAD

**Issue by markusk1505** [micahflee/torbrowser-launcher#556]
I wanted to use installed Tor-browser. As I am demanded i have clicked start to refresh the keyring. And the message persists.
Error Message says:
SIGNATURE VERIFICATION FAILED!
Error Code: 110775B5D101FB36BC6C911BEB774491D9FF06E2: Key expired
Thanks

**Comment by rico-fuentes** [comment]
I also get this error.:
SIGNATURE VERIFICATION FAILED !
Error code :....  Key expired
what is to do ?

**Comment by rico-fuentes** [comment]
It worked when I installed through   Tor Launcher Browser Settings.
Solved!
