### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by lopbox** [micahflee/torbrowser-launcher#559]
error code: 110775B5D101FB36BC6C911BEB774491D9FF06E2 key expired
![Screenshot_20210411_002243](https://user-images.githubusercontent.com/1247044/114285081-f6031d00-9a5c-11eb-9c95-4f52c385ed8a.png)

**Comment by TragicWarrior** [comment]
ditto

![image](https://user-images.githubusercontent.com/8481559/115075359-92477c80-9ec0-11eb-99b8-e4f935f22304.png)

**Comment by ryteu** [comment]
![Screenshot from 2021-06-19 13-23-15](https://user-images.githubusercontent.com/47901580/122650586-cf6afd80-d101-11eb-9aef-18372ed51d3b.png)

Same here.
