### ISSUE TITLE
No arm64 package available

### ISSUE THREAD

**Issue by nektro** [micahflee/torbrowser-launcher#560]
https://packages.debian.org/sid/torbrowser-launcher

**Comment by rogers0** [comment]
@nektro 
this project is merely a downloader.
please request upstream to provide such binary:
- https://www.torproject.org/download

**Comment by davidbaumann** [comment]
Currently, there is not tbb for arm64, so the package would be useless.
https://forum.torproject.net/t/tor-browser-for-arm-linux/5240
