### ISSUE TITLE
First ever problem installing Tor

### ISSUE THREAD

**Issue by fosko** [micahflee/torbrowser-launcher#569]
Hi I've installed Ubuntu 20 in my ThinkPad x250  i7-5. Even if I know nothing about IT I've been using Ubuntu since 2008, and Tor was always a simple installation. Not this time. For any reason the easy way of installing Tor from Ubuntu Software failed to connect to Tor (telling me "are you connected to the internet?"). Then I could see there was a problem also in my Firefox and Opera browsers; this one told me the error was I didn't activated DNS over HTTPS (first time I have to do such thing). I was wondering if it was a result of using Mobile Data instead of a router to connect to the internet.
This morning Tor Launcher seems to work, but it fails to verify signature and adviced me to post a comment in here.
![Screenshot from 2021-06-14 11-55-59](https://user-images.githubusercontent.com/85874471/121878176-b3cfb380-cd0b-11eb-8aa1-a78f10fd2362.png)

Can anyone help me? Is my ISP (phone) doing something wrong? (I can run TAILS with no probs at all, but I'm not in my office but in the countryside so I'd rather avoid prone-to-break-USB these days.

Thx a lot

**Comment by fosko** [comment]
SOLVED THX TO https://github.com/micahflee/torbrowser-launcher/issues/564

**Comment by micahflee** [comment]
Fixed in torbrowser-launcher 0.3.4
