### ISSUE TITLE
Signature verification failed. 

### ISSUE THREAD

**Issue by ryteu** [micahflee/torbrowser-launcher#580]
![Screenshot from 2021-06-19 13-23-15](https://user-images.githubusercontent.com/47901580/122650836-02fa5780-d103-11eb-9b22-a77bc45232d4.png)

**Comment by AsciiWolf** [comment]
I am currently working on a Flatpak update that will resolve this issue.

**Comment by hermann-san** [comment]
Problem for me was the same via  Linux Mint app store. [Downloading the tar file](https://www.torproject.org/download/) is working also easily for now

**Comment by AsciiWolf** [comment]
I have just pushed Flatpak update that fixes this issue. It should be available in a few hours.

**Comment by heindel** [comment]
![image](https://user-images.githubusercontent.com/13623940/131307654-3d13f69e-7330-4580-80df-3c23aaeb4678.png)

**Comment by heindel** [comment]
now it works :thinking:
