### ISSUE TITLE
[RFE] Wayland support

### ISSUE THREAD

**Issue by AsciiWolf** [micahflee/torbrowser-launcher#581]
Originally discussed [here](https://github.com/flathub/com.github.micahflee.torbrowser-launcher/issues/18). I am not sure whether this is a problem with Tor Browser Launcher or Tor Browser itself. However, if possible, it would be great if Tor Browser launched using Tor Browser Launcher could support Wayland. It would improve its security a lot.

**Comment by AsciiWolf** [comment]
```
Launching './Browser/start-tor-browser --detach'...
Tor Browser must be run within the X Window System.
Exiting.
```

It looks like that the Tor Browser itself does not support Wayland.

**Comment by pabs3** [comment]
FYI, Tor Browser 10.5 now supports Wayland:

https://blog.torproject.org/new-release-tor-browser-105
https://gitlab.torproject.org/legacy/trac/-/issues/31729

**Comment by pabs3** [comment]
Please note that the current torbrowser-launcher apparmor config blocks Wayland:

https://github.com/micahflee/torbrowser-launcher/issues/591

**Comment by AsciiWolf** [comment]
Thanks. I think that AppArmor is not used inside Flatpak.

I will reopen this ticket since the Wayland support will require a Flatpak manifest update.

**Comment by AsciiWolf** [comment]
Oops, I forgot that this is the upstream ticket, not the Flatpak one. Sorry!
