### ISSUE TITLE
apparmor blocks Tor Browser >= 10.5 starting with MOZ_ENABLE_WAYLAND set

### ISSUE THREAD

**Issue by pabs3** [micahflee/torbrowser-launcher#591]
Since Tor Browser 10.5 ([release notes](https://blog.torproject.org/new-release-tor-browser-105), [tbb#31729](https://gitlab.torproject.org/legacy/trac/-/issues/31729)) when the MOZ_ENABLE_WAYLAND environment variable is set, the Firefox build that is part of Tor Browser will try to use Wayland IPC and if that fails then Tor Browser will not start. The current torbrowser.Browser.firefox apparmor profile denies access to the relevant Wayland IPC files/sockets:

```
Jul 07 08:23:15 audit[437003]: AVC apparmor="DENIED" operation="mknod" profile="torbrowser_firefox" name="/dev/shm/wayland.mozilla.ipc.0" pid=437003 comm="Compositor" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
```

I was able to workaround this issue using this command:

```
sudo sh -c 'echo "owner /dev/shm/wayland.mozilla.ipc.[0-9]* rw," > /etc/apparmor.d/local/torbrowser.Browser.firefox ; apparmor_parser -r /etc/apparmor.d/torbrowser.Browser.firefox'
```

**Comment by travankor** [comment]
Confirm this works as well. Do you mind sending a PR with the fix as well?

**Comment by pabs3** [comment]
As I haven't contributed to this project yet I'd prefer someone else do it.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
