### ISSUE TITLE
signature verification failed

### ISSUE THREAD

**Issue by stangershwin** [micahflee/torbrowser-launcher#600]
![Screenshot from 2021-09-16 15-11-00](https://user-images.githubusercontent.com/90866891/133671294-eba05710-37af-4a07-b781-7c07a560e07c.png)

**Comment by GourangNagar** [comment]
Yes, I just faced the same issue

**Comment by Zeon556g** [comment]
me too

**Comment by Zeon556g** [comment]
> me too

Now it worked, actually it installed it, because the browser appeared but i had removed when i notice that so i installed it again and when i installed it again it didn't showed up the signature verification failed message.
