### ISSUE TITLE
Can't launch on Fedora 35 + KDE 5.23

### ISSUE THREAD

**Issue by ghost** [micahflee/torbrowser-launcher#604]
`Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/__init__.py", line 92, in main
    gui.move(
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'
`

**Comment by nocyber** [comment]
Tested on Fedora 35 with repo install and python 3.10.  It works fine for me today.
