### ISSUE TITLE
SIGNATURE VERIFICATION FAILED! 

### ISSUE THREAD

**Issue by Otsudo** [micahflee/torbrowser-launcher#607]
I see there are other issues identical to mine in here. So I'm just posting to show this issue isnt limited to their setup/device. I'm running ubuntu 20.04 and I just installed it last week. 
![Screenshot from 2021-10-24 11-50-04](https://user-images.githubusercontent.com/89806562/138604392-02f6564a-be69-4f66-b381-8b6a38d1c689.png)

**Comment by u451f** [comment]
Which version of torbrowser-launcher are you running? How did you install it?

**Comment by u451f** [comment]
duplicate #605 
duplicate #606
