### ISSUE TITLE
font error with the new version for tor.

### ISSUE THREAD

**Issue by kheshav-coder** [micahflee/torbrowser-launcher#609]
my tor browser just upgraded itself just now and after restarting it, all the fonts seem to crash... I even tried to change the font in the settings but that doesn't seem to work either.
![tor](https://user-images.githubusercontent.com/61469266/140961659-ab18775c-cea6-42ba-9b4d-872e347821b6.png)
.

**Comment by meskio** [comment]
I think this issue is from Tor Browser: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40703

**Comment by kheshav-coder** [comment]
@meskio thank you very much dude i solved the problem !!! using the information you provided.:)

**Comment by kron4eg** [comment]
Removing $HOME/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/fontconfig/fonts.conf helped

**Comment by xDazlD** [comment]
Removing fonts.conf caused a fingerprint change in my test so probably not a great idea, but it does fix the problem.

**Comment by kron4eg** [comment]
after recent tor-browser (11.0.3) update everything is back to normal.
