### ISSUE TITLE
Verifiecation failed

### ISSUE THREAD

**Issue by Peteyprof** [micahflee/torbrowser-launcher#614]
SIGNATURE VERIFICATION FAILED

error code : 110775B5D101FB36BC6C911BEB774491D9FF06E2 : key exprired

**Comment by Rinnekioku** [comment]
I have the same issue I hope, somebody will answer how to fix it

**Comment by michelep** [comment]
the same for me :-(

**Comment by kaisar2019** [comment]
same for me please
