### ISSUE TITLE
Cannot be started on Arch Linux. (TypeError)

### ISSUE THREAD

**Issue by FoxMaccloud** [micahflee/torbrowser-launcher#617]
I'm not able to start the torbrowser after installing it via the package manager on Arch Linux. 

```
$ torbrowser-launcher
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Traceback (most recent call last):
  File "/usr/bin/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/__init__.py", line 92, in main
    gui.move(
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'float'
  move(self, int, int): argument 1 has unexpected type 'float'
  ```

**Comment by FoxMaccloud** [comment]
Found others that has the same issue;
https://bugzilla.redhat.com/show_bug.cgi?id=2007439

**Comment by jaydn** [comment]
Commenting it out is fine for now and will allow it to download and launch, line only centers the window, looks like there is PR open already awaiting review #599

**Comment by AlvaroParker** [comment]
In line 93 and 94 I change the division to force to be an integer:
Original lines:
`gui.move(`
`    (desktop.width() - window_size.width()) / 2,`
`    (desktop.height() - window_size.height()) / 2,`
`    )`
Modified to:
`gui.move(`
`    int((desktop.width() - window_size.width()) / 2),`
`    int((desktop.height() - window_size.height()) / 2),`
`    )`
That solve the launching error for me.

**Comment by kpcyrd** [comment]
I've applied #599 downstream to the Arch Linux package in 0.3.5-4 :+1:
