### ISSUE TITLE
Brand new install

### ISSUE THREAD

**Issue by evodefense** [micahflee/torbrowser-launcher#619]
E53D989A9E2D47BF bad signature I've had repeat failure with same error code

**Comment by evodefense** [comment]
I was able to work around / resolve user error with following 

Parrot os using anonsurf causes this issue 

Upon turning off anon surf tor browser launches perfectly

**Comment by DonRichards** [comment]
Same issue, fresh install on Ubuntu 22.04

**Comment by DonRichards** [comment]
In case this helps. ![2022-02-04_16-06](https://user-images.githubusercontent.com/2738244/152603812-3b2a96b0-f339-492c-a3f1-0940ca586566.png)

**Comment by jason91340** [comment]
Reinstalling can solve 99% of issues.
Reinstall the launcher.

**Comment by DonRichards** [comment]
This is a fresh install and is the first time I started it.
