### ISSUE TITLE
Signature verification failed downloading for the first time

### ISSUE THREAD

**Issue by znoteer** [micahflee/torbrowser-launcher#621]
Tried to launch torbrowser-launcher on Debian 11.2 and received the error

Signature verification failed!
Error code: E53D989A9E2D47BF: No public key

I tried 2 more times after the initial failure, but both ended the same as the first attempt.

If more information is needed, please ask me for it.

**Comment by peszpesz** [comment]
I have the same problem on Ubuntu 20.04.3 LTS.

**Comment by optimizer-1111** [comment]
Same here, fully updated, no joy, same error.

**Comment by marcelo-trajano** [comment]
[https://pgnfqru.media.bublupcdn.com/1aYr8X0WEp6eX6vg_s2mtw/images/full_007-im-15d6f78a-b809-4440-84d7-4e85649900de.jpg](url)

**Comment by znoteer** [comment]
I was able to make this work a few days later.  It's no longer an issue for me.

**Comment by peszpesz** [comment]
> I was able to make this work a few days later. It's no longer an issue for me.

Could you pls share your solution?

**Comment by peszpesz** [comment]
Wow, just tried and worked. Probably solved in the new tor version.

**Comment by znoteer** [comment]
For the sake of the archive, and since I didn't make it clear in my "it works"
post, as you discovered yourself, my solution was simply to retry a couple
of days later.

-- 
Znoteer
***@***.***

**Comment by soufianetahiri** [comment]
The very same issue here

![image](https://user-images.githubusercontent.com/17729335/150767592-f71ede3e-b1a3-4074-ad5b-921a86732f14.png)

**Comment by soufianetahiri** [comment]
Well, problem solved, be sure you are not installing something else at the same time, I was updating my distribution while trying to install torlauncher, which was the cause of my problem.

**Comment by lelandw** [comment]
Installing on Ubuntu 18.04, I get the same as above, only with Error Code: GENERIC_VERIFY_FAIL.  Same after reboot.

**Comment by znoteer** [comment]
I should have closed this issue with my last comment. Closing now

**Comment by BarbzYHOOL** [comment]
i have this error and it makes no sense

**Comment by natnael-bedru** [comment]
I have the same issue here .. i have just updated and it pops up 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=22.0.4
DISTRIB_CODENAME=Sikaris
![Screenshot_20230221_230236](https://user-images.githubusercontent.com/116979329/220446629-bc1bad45-1aa6-4de1-87b1-dec69247bc3f.png)

**Comment by prasadsnet** [comment]
getting this error:

![image](https://github.com/micahflee/torbrowser-launcher/assets/123559571/ad12646e-d61c-4309-b348-5cad5212c488)
