### ISSUE TITLE
Tor: no install

### ISSUE THREAD

**Issue by MAGA6226** [micahflee/torbrowser-launcher#623]
I use many versions of Linux and this is the first time I find I'm not able to install the Tor browser and got the following error message:

SIGNATURE VERIFICATION FAILED!

Error Code: E53D989A9E2D47BF: No public key

You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key.

A copy of the Tor Browser files you downloaded have been saved here:
/home/linux/.cache/torbrowser/download/tor-browser-linux64-11.0.4_en-US.tar.xz.verification_failed
/home/linux/.cache/torbrowser/download/tor-browser-linux64-11.0.4_en-US.tar.xz.asc.verification_failed

Click Start to refresh the keyring and try again. If the message persists report the above error code here:
https://github.com/micahflee/torbrowser-launcher/issues

Can someone help clarify?
![torPublicKeyError](https://user-images.githubusercontent.com/69598431/152663292-e657ee6c-3491-482d-8755-8b6ea5ec7c52.png)

**Comment by jason91340** [comment]
I have the same question,even the same error code
I solved that by this way.You can try it.
"
Step1 sudo apt install flatpak 
Srep2 flatpak install flathub com.github.micahflee.torbrowser-launcher -y
Step3 flatpak run com.github.micahflee.torbrowser-launcher
"
maybe some errors are appeared on step2
such as "error: No remote refs found similar to ‘flathub’"
"flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo" can solve it.
And now start menu or application controller would appear another "Tor Browser"
Click that and anything will be solved! :)
(My English is not good. Sorry about that! )

**Comment by matthewoots** [comment]
> I have the same question,even the same error code I solved that by this way.You can try it. " Step1 sudo apt install flatpak Srep2 flatpak install flathub com.github.micahflee.torbrowser-launcher -y Step3 flatpak run com.github.micahflee.torbrowser-launcher " maybe some errors are appeared on step2 such as "error: No remote refs found similar to ‘flathub’" "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo" can solve it. And now start menu or application controller would appear another "Tor Browser" Click that and anything will be solved! :) (My English is not good. Sorry about that! )

@jason91340 Answer worked for me

**Comment by rxt2332** [comment]
> 
Hey

When I do the "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo", it asks for authentication & is requiring a password. Its not letting me type anything in & the text curser is not flashing. Any idea on what to do?

Thanks

![received_2118659658312363](https://user-images.githubusercontent.com/103609524/163290335-c8a3ae9d-b01c-4d79-a7c9-3502c5cb3aa0.jpeg)
s

**Comment by u451f** [comment]
Well, the issue clearly states what your problem could be:

1. You might be under attack,
2. there might be a network problem, 
3. or you may be missing a recently added Tor Browser verification key.

And then says: it managed to download the files, but it could not find the verification key. So you seem to have been suffering from 3)

You did not state how you installed TBB in first place. Reinstalling can be a solution, and apparently it helped in your case :)
