### ISSUE TITLE
TorBrowser-Launcher Bug since v11.0 - How to fix?

### ISSUE THREAD

**Issue by notbad24** [micahflee/torbrowser-launcher#626]
Hi guys!

I need help to fix my problem with TorBrowser since v11.0 - I'm now on v11.6 (Linux-x64)

Since TorBrowser v11.0 my TorBrowser crashes after about 4-5 minutes 
every time. (can connect to the Tor network and also access websites).

TorBrowser-socks-port is open, checked with nmap.

This message appears every time:

**Tor unexpectedly exited. This might be due to a bug in Tor itself, another program on your system, or faulty hardware. Until you restart Tor, the Tor Browser will not able to reach any websites. If the problem persists, please send a copy of your Tor Log to the support team.**

I have tried everything possible already, changed my iptables, without success.

Changed TorBrowser socks-port and control-port.
Default setting does not work either.

Tried on another machine, same problem.

The following messages appear when I start TorBrowser v11.6 with --verbose: (after TorBrowser v11.6 crash)

> Fontconfig warning: "./Browser/TorBrowser/Data/fontconfig/fonts.conf", line 85: unknown element "blank"
> Fontconfig warning: "./Browser/TorBrowser/Data/fontconfig/fonts.conf", line 85: unknown element "blank"

> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5181:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default

> [notice] Owning controller connection has closed -- exiting now.
> [notice] Catching signal TERM, exiting cleanly.

Sound card **disabled/not present** to use the TorBrowser. It ran with v10 and the versions before without problems.

What could be the reason for this?
How can I fix this?

I miss the TorBrowser v10, that at least ran smoothly.

Please help to fix the problem.
Thanks in advance.

**Comment by davidbaumann** [comment]
This does not look like a problem of torbrowser-launcher .
To make sure, please download Tor Browser [directly](url).
