### ISSUE TITLE
get a documentation for and finalized version of RecommendedTBBVersions

### ISSUE THREAD

**Issue by adrelanos** [micahflee/torbrowser-launcher#63]
At the moment [RecommendedTBBVersions](https://check.torproject.org/RecommendedTBBVersions) looks like this.

```
[
"2.3.25-15-MacOS",
"2.3.25-15-Windows",
"2.3.25-15-Linux",
"2.3.25-16-Linux",
"2.4.17-rc-1-MacOS",
"2.4.17-rc-1-Windows",
"2.4.17-rc-1-Linux",
"2.4.18-rc-1-MacOS",
"2.4.18-rc-1-Windows",
"2.4.18-rc-1-Linux",
"2.4.18-rc-2-Linux",
"3.0-beta-1-Linux",
"3.0-beta-1-MacOS",
"3.0-beta-1-Windows"
]
```

[This time only the 64 bit version was updated.](https://blog.torproject.org/blog/64-bit-gnulinux-tor-browser-bundles-updated)

On the [download page](https://www.torproject.org/dist/torbrowser/linux/),

* 2.3.25-15 32 bit exists.
* 2.3.25-15 64 bit exists.
* 2.3.25-16 32 bit does not exist.
* 2.3.25-16 64 bit exists.

How are scripts supposed to know 2.3.25-15 is the latest recommended version for 32 bit? Because 2.3.25-15 precedes 2.3.25-16 in the list? Where is this documented?

torbrowser-launcher will probably break again and again when  RecommendedTBBVersions changes its format. Would it make sense to ask The Tor Project about documentation for and finalized version of RecommendedTBBVersions?

**Comment by adrelanos** [comment]
Posted a bunch of tickets related to this.

better support for TBB / TPO software downloaders:
https://trac.torproject.org/projects/tor/ticket/14386

finalize RecommendedTBBVersions format:
https://trac.torproject.org/projects/tor/ticket/14383

have a permanent link to RecommendedTBBVersions:
https://trac.torproject.org/projects/tor/ticket/14384

use a download similar folder layout as TBB:
https://trac.torproject.org/projects/tor/ticket/14385

**Comment by micahflee** [comment]
Now that TBL isn't checking RecommendTBBVerisons, this issue isn't relevant anymore.
