### ISSUE TITLE
not running tor browser in Elementary ios

### ISSUE THREAD

**Issue by elementary69** [micahflee/torbrowser-launcher#631]
![pantalla](https://user-images.githubusercontent.com/101528359/158079701-152a8ab5-ee8d-448e-8175-b3d56a3908ab.jpeg)
Good night,
I have been trying to boot the Tor browser for a long time and there is no way, I always get the same error. I've installed solutions that have worked for other people, but I'm always stuck in the same place. (Verifying keys)
Working with Elementary IOS 5.1.7

**Comment by u451f** [comment]
I am not sure if this is a problem with torbrowser-launcher or rather a problem with your OpenPGP setup. I never used elementary, but my understanding is that it's a linux distribution. Check if you have the signing key:

`gpg --list-keys torbrowser@torproject.org`

to start with. Eventually fetch the relevant key manually.

Or install torbrowser from torproject.org and use the signature verification.

The only difference, as far as I know, is that torbrowser-launcher has AppArmor policies (which provide some additional security but only if AppArmor is even enabled on your OS) while TBB from Torproject (what we call upstream) does not have these policies.

**Comment by u451f** [comment]
Also see https://github.com/micahflee/torbrowser-launcher/issues/624#issuecomment-1108902340
