### ISSUE TITLE
Tor Browser Signing Key Expired - Do the Devs even care???

### ISSUE THREAD

**Issue by FrostBlade5** [micahflee/torbrowser-launcher#634]
Many people have this issue, no solution.

Instead of ignoring me and bullying me could you go ahead and explain what's going on?

**Comment by u451f** [comment]
The key is not expired:

```
$ gpg --list-key torbrowser
pub   rsa4096/0x4E2C6E8793298290 2014-12-15 [C] [expires: 2025-07-21]
  Schl.-Fingerabdruck = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
uid                Tor Browser Developers (signing key) <torbrowser@torproject.org>
sub   rsa4096/0xE53D989A9E2D47BF 2021-09-17 [S] [expires: 2023-09-17]
```

However, you might have an old version of the key on your machine. Try refreshing your PGP keyring. IMO, torbrowser-launcher does that automatically nowadays when you reinstall - but I'm not 100% sure.

Also, you did not say how you install (using apt install, from source or using flatpak, or whatever obscure installation there is on proprietary systems) nor did you describe when exactly you see which error.

**Comment by u451f** [comment]
Also see https://github.com/micahflee/torbrowser-launcher/issues/624#issuecomment-1108902340

**Comment by niccokunzmann** [comment]
> Devs even care???

Please be friendly.
