### ISSUE TITLE
Error Code: E53D989A9E2D47BF: No public Key

### ISSUE THREAD

**Issue by suciokhan** [micahflee/torbrowser-launcher#639]
Hello. Attempted install via following on Ubuntu 20.04:
```
1. sudo apt update && upgrade -y
2. sudo apt install torbrowser-launcher
3. Launched torbrowser-launcher through GUI
4. Told it to download *without* using Tor (since it's not installed yet)
5. Wait for download & key verification
6. SIGNATURE VERIFICATION FAILED! Multiple attempts, same message saying to post here.

**Comment by suciokhan** [comment]
Side note, I also attempted to install from flatpak and I have a similar problem.

Ran this:

`flatpak install flathub com.github.micahflee.torbrowser-launcher -y`

Got this:

`error: Unable to load summary from remote flathub: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)`

**Comment by vhns** [comment]
I can reproduce the same issue on Debian stable.

**Comment by opennota** [comment]
A freshly-installed Ubuntu 22.04.1. The same issue, the same public key.

**Comment by vattik** [comment]
Try just running the command:
```shell
curl -s https://keys.openpgp.org/vks/v1/by-fingerprint/EF6E286DDA85EA2A4BA7DE684E2C6E8793298290 |gpg --import -
```
and reboot system.
