### ISSUE TITLE
window grouping under wayland doesn't work properly

### ISSUE THREAD

**Issue by thjderjktyrjkt** [micahflee/torbrowser-launcher#640]
I don't know if this is an upstream issue, but i'll report it here first.

`StartupWMClass=Tor Browser` (in desktop files) and `--class "Tor Browser"` (in `start-tor-browser` script) are used to make sure Tor Browser is not mixed up with Firefox.

But `-class` option only works with X11. Under Wayland it doesn't work, instead a separate window with generic Wayland icon is shown. And if Firefox is installed (natively), Tor Browser is displayed and grouped with Firefox icon.

`--name` option is the appropriate option to be used under Wayland (as documented [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1577056)). 

This should be easily fixed by appending `--name "Tor Browser"` after `--class "Tor Browser"` in `/var/data/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/start-tor-browser`

Flathub version BTW.

**Comment by thjderjktyrjkt** [comment]
so yeah, this is an upstream issue. [relevant part](https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/blob/master/projects/tor-browser/RelativeLink/start-tor-browser#L347)

**Comment by thjderjktyrjkt** [comment]
alternate way to workaround (not fix) it is to use X11 instead of Wayland, by removing the `MOZ_ENABLE_WAYLAND=1` and disabling `x11` socket, as `--class` is supported under X11 session. But why not more security?

**Comment by thjderjktyrjkt** [comment]
issue: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41015

fix: https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/merge_requests/466

**Comment by davidbaumann** [comment]
Thanks for updating the issue here!
