### ISSUE TITLE
Tor browser launcher does nothing on Ubuntu 22.04 kde plasma

### ISSUE THREAD

**Issue by matt32106** [micahflee/torbrowser-launcher#641]
after launching Torbrowser launcher, it says it is downloading something but then nothing happens

```
$ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.3
https://github.com/micahflee/torbrowser-launcher
QApplication: invalid style override 'kvantum' passed, ignoring it.
        Available styles: Breeze, Oxygen, Windows, Fusion
Your version of Tor Browser is out-of-date. Downloading the newest version.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
$
```

**Comment by rustyx** [comment]
This project isn't needed anymore, use the official Tor browser.

1. Visit https://www.torproject.org/download/ and download the Linux version
2. Unpack it
    `tar xJf ~/Downloads/tor-browser-linux64-11.5.1_en-US.tar.xz`
3. Register it
    `cd tor-browser_en-US`
    `./start-tor-browser.desktop --register-app`
4. Use "**Tor Browser**" application normally

**Comment by alabamatoy** [comment]
@rustyx doesnt seem to work, all sorts of permission problems.  start-tor-browser.desktop is mode 700 so got permission denied, changed it to 755, then got "/usr/bin/env: ‘./Browser/execdesktop’: Permission denied" and I cannot seem to get past that.  Ubuntu 22.04

**Comment by matt32106** [comment]
FWIW I managed to make the script work by modifyng the code (replace localisation by ALL) and then when it spits an error about the file it cannot find, I created a symlink to the right directory. Quick and dirty but works.
