### ISSUE TITLE
error code: GENERIC_VERIFY_FAIL

### ISSUE THREAD

**Issue by algreen702021** [micahflee/torbrowser-launcher#645]
Can't verify signature on Ubuntu 18.04
regards
AL

**Comment by John-Wilson-Redcar** [comment]
Same problem on various distros..
![Screenshot_2022-08-09_21-00-04](https://user-images.githubusercontent.com/110937041/183750172-9a61a0fd-ef49-420c-bd54-84912174b891.png)

**Comment by ahs9** [comment]
roger that

**Comment by Bill-Overman** [comment]
Same Issue as John-Wilson-Re...

Running Linux Mint 19.2
Python was pre-installed for other purposes.

**Comment by danmcne** [comment]
Same issue

SIGNATURE VERIFICATION FAILED!
Error Code: GENERIC_VERIFY_FAIL

You might be under attack, there might be a network problem, or you may be missing a recently added Tor Browser verification key.



Refreshing the keyring doesn't seem to help

**Comment by davidbaumann** [comment]
Duplicate of #633
