### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by pax2you4now** [micahflee/torbrowser-launcher#648]
hi,
-when I launch:
 torbrowser-launcher
-I receive this message:
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.3
https://github.com/micahflee/torbrowser-launcher
Launching Tor Browser.
Running /home/pax/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/start-tor-browser.desktop
  File "/home/pax/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/./Browser/execdesktop", line 7
    if [ "$#" -ge 1 ]
                  ^
SyntaxError: invalid syntax
-data maybe useful:
os linux debian 11.3
Tor version 0.4.5.10

**Comment by davidbaumann** [comment]
Try latest flatpak please.
