### ISSUE TITLE
Tor Browser not work with Vimeo in Ubuntu 22.10

### ISSUE THREAD

**Issue by ejsc1** [micahflee/torbrowser-launcher#651]
Problem with Codecs:
![image](https://user-images.githubusercontent.com/48624942/198057652-56119fc0-c0ef-467f-a0c6-397330cdf7d9.png)

![image](https://user-images.githubusercontent.com/48624942/198056408-d0ab5c23-8847-4714-aad4-b8a339284eab.png)

**Comment by davidbaumann** [comment]
As [torbrowser-launcher](https://github.com/micahflee/torbrowser-launcher) is mostly to download and update tbb, this might be the wrong place.
Please check if the problem persists when downloading Tor Browser Bundle [directly](https://www.torproject.org/download/) .
