### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by lediedu** [micahflee/torbrowser-launcher#652]
Error Code: GENERIC VERIFY_FAIL

keeps poppong up with using tor-browser. Unable to start, several times reinstalled, error keeps showing up.

**Comment by Nederlansk** [comment]
I'm having the same problem. Using Ubuntu 18.04.

**Comment by Archimedes2** [comment]
Same problem here - Linux Mint Tara 19

**Comment by who170845** [comment]
in debian or ubuntu you have to remove tor browser that you installed `sudo apt-get remove`
after that install it again with following command `sudo apt install -y tor torbrowser-launcher`

**Comment by nrozron** [comment]
Hello,
Same problem with Ubuntu 18.04, the 3 commands didn't solved it.
Regards

**Comment by davidbaumann** [comment]
Please try the latest version from flatpak.
