### ISSUE TITLE
Job for tor.service failed because the control process exited with error code. See "systemctl status tor.service" and "journalctl -xeu tor.service" for details.

### ISSUE THREAD

**Issue by CyberGhazi786** [micahflee/torbrowser-launcher#658]
I tried all the ways but got this errors.

Job for tor.service failed because the control process exited with error code.
See "systemctl status tor.service" and "journalctl -xeu tor.service" for details.

How to fix it :-(

Method Used Here Is : https://gist.github.com/valyakuttan/ce4afb62288120cd5ecef0fde4ea63c4#file-install-tor-on-arch-linux-md

**Comment by davidbaumann** [comment]
This issue seems not related to torbrowser-launcher.
