### ISSUE TITLE
Completely broken for 12.0 because of hardcoded locale

### ISSUE THREAD

**Issue by copiummax** [micahflee/torbrowser-launcher#659]
When it tries to fetch the browser for the first time it 404's because it hardcodes this resource:
`/torbrowser/12.0/tor-browser-linux64-12.0_en-US.tar.xz.asc`
instead of this one
`/torbrowser/12.0/tor-browser-linux64-12.0_ALL.tar.xz.asc`
because it hardcodes the locale instead of getting it from the initial endpoint

**How to reproduce:**
You can reproduce by just launching torbrowser-launcher for the first time

**Comment by AsciiWolf** [comment]
Same issue with the Flathub.org Flatpak.

**Comment by Relected** [comment]
yup, i can reproduce it as well, cuz it searches for torbrowser/12.0/tor-browser-linux64-12.0_en-US.tar.xz.asc which doesnt exist

**Comment by nullsurface** [comment]
Reproduced on void linux today.

**Comment by baselab** [comment]
Same here on both void and ubuntu.
