### ISSUE TITLE
Adopt unofficial Tor Browser Ports to provide ARM support

### ISSUE THREAD

**Issue by Anderhar** [micahflee/torbrowser-launcher#662]
While Tor Project still does not provide arm64 binaries for Linux platform, all interested users have the opportunity to get them unofficially from [Tor Browser Ports](https://sourceforge.net/projects/tor-browser-ports/files/). Apparently, the same audience could benefit if this source could be adopted to bring TB Launcher to ARM compatibility. (It just needs to add some notification, so that each user can evaluate the potential risks individually.)

**Comment by davidbaumann** [comment]
There is progress on an official build for arm
https://forum.torproject.net/t/tor-browser-for-arm-linux/5240
