### ISSUE TITLE
On Fedora Rawhide: The new tbb release is installed in a Different directory instead of upgrading the exsiting installation.

### ISSUE THREAD

**Issue by alimirjamali** [micahflee/torbrowser-launcher#665]
Hi.

On Fedora Rawhide, Tor Browser Launcher did not recognize the already installed tbb at:
`~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US`
And installed a fresh copy at:
`~/.local/share/torbrowser/tbb/x86_64/tor-browser`

I believe the above task should have been an upgrade rather than a fresh install, preserving user configuration and data.

Minor annoyance for me. I was able to copy browser profile from the original tbb to the new bundle (I keep some bookmarks and open tabs in tbb on this specific machine).

Best regardsm
Ali

**Comment by davidbaumann** [comment]
Should rename the directory: https://github.com/micahflee/torbrowser-launcher/commit/acd8246d5538c6f639f1952b764c25a68655a01b

But I guess if you had 2 locales installed before, the wrong one might have been renamed.
