### ISSUE TITLE
Flatpak version not working

### ISSUE THREAD

**Issue by hellomelter234** [micahflee/torbrowser-launcher#668]
Whenever I install torbrowser-launcher from source or the Debian repositories, I got an error 404 error. So, I tried to use flatpak, but got these errors:

> qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

I reinstalled the app but it didn't work. I have no idea what these errors are and what they mean. I couldn't find any working solutions.

**Comment by AsciiWolf** [comment]
The Flatpak version should work fine on both X11 and Wayland. It looks like there may be something wrong with your system.

**Comment by davidbaumann** [comment]
I installed a fresh Debian x64 with Gnome, installed the flatpak and cannot confirm the problem.
