### ISSUE TITLE
Security design doc: https://check.torproject.org/RecommendedTBBVersions is down

### ISSUE THREAD

**Issue by rugk** [micahflee/torbrowser-launcher#674]
https://github.com/micahflee/torbrowser-launcher/blob/main/security_design.md#downgrade-attacks has a 404 link to https://check.torproject.org/RecommendedTBBVersions in it.

That does not imply a lot of confidence… :stuck_out_tongue_winking_eye: 

Just joking here, I guess you just missed to update the link to the correct one, but I also don't know which the correct one is, so I could not fix it right away. :wink: 

## Screenshot

![grafik](https://user-images.githubusercontent.com/11966684/212431476-15d8d822-1bc1-4ecf-8d8e-f44b48c88d67.png)
![grafik](https://user-images.githubusercontent.com/11966684/212431497-cc55feba-f24d-486d-9a6f-7f7fbe466a37.png)

**Comment by davidbaumann** [comment]
Hello,
thanks for the hint, the proper URL would be https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions/
I cannot make a PR at the moment.

**Comment by davidbaumann** [comment]
Actually the URL has been changed in  to https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/ALL in [#e07beac325b7bd716b7a053dcd5664c113e67458](https://github.com/micahflee/torbrowser-launcher/commit/e07beac325b7bd716b7a053dcd5664c113e67458)
